import type { SharedProductRecord } from "./supabase";

export type ShelfPeriod = "AM" | "PM";
export interface ShelfEntry { productId:string; addedAt:string; openedAt?:string; paoMonths?:number; periods:ShelfPeriod[]; }
export interface ShelfFinding { kind:"overlap"|"irritation"|"gap"|"sequence"; tone:"good"|"watch"|"neutral"; titleZh:string; titleEn:string; detailZh:string; detailEn:string; }
export interface NeedVerdict { level:"good-addition"|"optional"|"mostly-duplicate"|"not-recommended"; labelZh:string; labelEn:string; reasonZh:string; reasonEn:string; }

const KEY="skincare101-my-shelf-v1";
export function loadShelf():ShelfEntry[]{try{const raw=localStorage.getItem(KEY);const parsed=raw?JSON.parse(raw):[];return Array.isArray(parsed)?parsed:[]}catch{return[]}}
export function saveShelf(entries:ShelfEntry[]){try{localStorage.setItem(KEY,JSON.stringify(entries))}catch{}}
export function addToShelf(entries:ShelfEntry[],productId:string):ShelfEntry[]{if(entries.some(x=>x.productId===productId))return entries;return [...entries,{productId,addedAt:new Date().toISOString(),periods:[]}]}
export function removeFromShelf(entries:ShelfEntry[],productId:string){return entries.filter(x=>x.productId!==productId)}

const norm=(s:string)=>s.toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]+/g," ");
const text=(p:SharedProductRecord)=>norm([p.category,p.mainCategory,p.productSubtype,...(p.productFunctions||[]),...(p.formulaBestFor||[]),...(p.formulaAlsoWorksFor||[]),p.formulaSummary||"",p.formulaVerdict||""].join(" "));
function features(p:SharedProductRecord){const t=text(p),out=new Set<string>();const map:[string,RegExp][]=[
 ["cleanse",/clean|洁面|卸妆/],["hydrate",/hydrat|moist|保湿|补水|humect/],["barrier",/barrier|屏障|ceramide|脂质/],["bright",/bright|pigment|whiten|焕白|美白|色沉/],["acne",/acne|blemish|控油|痘|salicyl/],["antiage",/anti.?age|wrinkle|retinol|retinal|抗老|皱/],["soothe",/sooth|calm|舒缓|敏感|centella/],["spf",/sunscreen|spf|防晒/]
 ];for(const[k,r]of map)if(r.test(t))out.add(k);return out}
function irritationSignals(p:SharedProductRecord){const t=norm([...(p.ingredients||[]),p.formulaSummary||"",...(p.formulaCaveats||[])].join(" "));const s=new Set<string>();if(/retinol|retinal|维a|视黄/.test(t))s.add("retinoid");if(/glycolic|lactic|mandelic|salicylic|aha|bha|果酸|水杨酸|乳酸|杏仁酸/.test(t))s.add("acid");if(/benzoyl peroxide|过氧化苯甲酰/.test(t))s.add("bpo");if(/ascorbic acid|左旋维c|抗坏血酸/.test(t))s.add("ascorbic");return s}
export function analyzeShelfRoutine(products:SharedProductRecord[],entries:ShelfEntry[],period:ShelfPeriod):ShelfFinding[]{const selected=entries.filter(e=>e.periods.includes(period)).map(e=>products.find(p=>p.id===e.productId)).filter(Boolean) as SharedProductRecord[];const findings:ShelfFinding[]=[];if(!selected.length)return findings;
 const byFeature=new Map<string,SharedProductRecord[]>();for(const p of selected)for(const f of features(p)){const a=byFeature.get(f)||[];a.push(p);byFeature.set(f,a)}
 for(const[f,ps]of byFeature)if(ps.length>=2&&!["hydrate","soothe"].includes(f)){findings.push({kind:"overlap",tone:"neutral",titleZh:"功能有明显重叠",titleEn:"Meaningful functional overlap",detailZh:`${ps.slice(0,3).map(p=>p.brand+" "+p.name).join("、")} 都主要覆盖 ${f}。不是不能一起用，但通常没必要层层叠加。`,detailEn:`${ps.slice(0,3).map(p=>p.brand+" "+p.name).join(", ")} substantially overlap on ${f}. They can coexist, but stacking them is usually unnecessary.`})}
 const sig=new Map<string,number>();for(const p of selected)for(const s of irritationSignals(p))sig.set(s,(sig.get(s)||0)+1);const strong=[...sig.entries()].reduce((n,[k,v])=>n+((k==="retinoid"||k==="acid"||k==="bpo")?v:0),0);if(strong>=2)findings.push({kind:"irritation",tone:"watch",titleZh:"这一套的刺激负荷偏高",titleEn:"This routine has a higher irritation load",detailZh:"同一时段叠加多个强活性并不等于“成分相克”，但对耐受要求更高。建议错开频率或分不同晚使用。",detailEn:"This is not a simplistic ingredient-conflict rule. Multiple strong actives in one session raise tolerance demands; consider alternating nights or lowering frequency."});
 const all=new Set(selected.flatMap(p=>[...features(p)]));if(period==="AM"&&!all.has("spf"))findings.push({kind:"gap",tone:"watch",titleZh:"早间缺少明确防晒",titleEn:"AM routine is missing clear sunscreen",detailZh:"如果这些是你完整的早间步骤，防晒是比再加一瓶精华更优先的缺口。",detailEn:"If this is your full AM routine, sunscreen is a higher-priority gap than adding another serum."});if(!all.has("hydrate")&&!all.has("barrier"))findings.push({kind:"gap",tone:"neutral",titleZh:"基础保湿/屏障支持偏少",titleEn:"Limited hydration/barrier support",detailZh:"活性成分很多时，先补基础支持通常比继续加功效型产品更有价值。",detailEn:"When actives dominate, basic hydration/barrier support is usually more useful than another treatment."});return findings}

export function doINeedThis(candidate:SharedProductRecord,owned:SharedProductRecord[]):NeedVerdict{const cf=features(candidate);const sameCategory=owned.filter(p=>norm(p.category)===norm(candidate.category));let best=0;for(const p of owned){const pf=features(p);const overlap=[...cf].filter(x=>pf.has(x)).length;const score=cf.size?overlap/cf.size:0;best=Math.max(best,score)}const candidateStrong=irritationSignals(candidate);const ownedStrong=new Set(owned.flatMap(p=>[...irritationSignals(p)]));if(candidateStrong.size&&[...candidateStrong].some(x=>ownedStrong.has(x))&&best>=.5)return{level:"not-recommended",labelZh:"暂不建议买",labelEn:"Not recommended",reasonZh:"你已有功能高度相近的强活性产品；这次新增更可能增加刺激负荷，而不是补足新的护理缺口。",reasonEn:"You already own a closely overlapping strong active. This is more likely to add irritation load than fill a new routine gap."};if(best>=.75||sameCategory.length>=2)return{level:"mostly-duplicate",labelZh:"大概率重复",labelEn:"Mostly duplicate",reasonZh:"你现有产品已经覆盖这款的主要角色。除非你明确想替换肤感、价格或耐受，否则没有明显必要。",reasonEn:"Your shelf already covers most of this product's role. Unless you want a texture, price or tolerance replacement, it adds little."};if(best>=.35)return{level:"optional",labelZh:"可有可无",labelEn:"Optional",reasonZh:"它有一定新价值，但不是明显缺口。先把现有产品组合用顺，再决定更合理。",reasonEn:"It adds something, but does not fill a clear gap. Use your current routine consistently before deciding."};return{level:"good-addition",labelZh:"有明确补位价值",labelEn:"Good addition",reasonZh:"和你现有护肤柜的主要功能重叠较低，更像是在补一个新角色，而不是重复购买。",reasonEn:"It has relatively low functional overlap with your shelf and is more likely to fill a new role than duplicate one."}}
