import { supabase, type SharedProductRecord } from "./supabase";

export type RoutinePeriod="AM"|"PM";
export type RoutineVisibility="private"|"public";
export interface RoutineItemInput{product?:SharedProductRecord|null;customProductName?:string;period:RoutinePeriod;stepOrder:number;stepCategory:string;frequency:string;usageNote?:string;}
export interface RoutineInput{title:string;description?:string;skinProfileId?:string|null;goals:string[];climate?:string;usageWeeks?:number|null;overallRating?:number|null;visibility:RoutineVisibility;items:RoutineItemInput[];}
export interface RoutineListItem{id:string;userId:string;skinProfileId?:string|null;title:string;description:string;goals:string[];climate?:string|null;usageWeeks?:number|null;overallRating?:number|null;visibility:RoutineVisibility;publishedAt?:string|null;createdAt:string;items:Array<{id:string;productId?:string|null;customProductName?:string|null;period:RoutinePeriod;stepOrder:number;stepCategory:string;frequency:string;usageNote:string;product?:{id:string;brand:string;name:string;brand_local_name?:string|null;brand_english_name?:string|null;product_local_name?:string|null;product_english_name?:string|null}|null}>;skinProfile?:{skin_answers:any;profile_answers:any;selected_symptoms:string[]}|null;}

function rawProductId(product?:SharedProductRecord|null){return product?.id?.replace(/^shared-/,"")||null;}
export async function saveRoutine(input:RoutineInput):Promise<string>{
 const{data:userData,error:userError}=await supabase.auth.getUser();if(userError)throw userError;if(!userData.user)throw new Error("请先登录后保存 Routine。");
 const now=new Date().toISOString();
 const{data:routine,error}=await supabase.from("user_routines").insert({user_id:userData.user.id,skin_profile_id:input.skinProfileId||null,title:input.title.trim()||"My Routine",description:(input.description||"").trim().slice(0,800),routine_goal:input.goals.slice(0,8),climate:input.climate||null,usage_weeks:input.usageWeeks||null,overall_rating:input.overallRating||null,visibility:input.visibility,published_at:input.visibility==="public"?now:null,updated_at:now}).select("id").single();
 if(error||!routine)throw error||new Error("无法保存 Routine。");
 if(input.items.length){const rows=input.items.map(item=>({routine_id:routine.id,product_id:rawProductId(item.product),custom_product_name:item.product?null:(item.customProductName||"").trim().slice(0,160)||null,period:item.period,step_order:item.stepOrder,step_category:item.stepCategory,frequency:item.frequency||"daily",usage_note:(item.usageNote||"").trim().slice(0,300),updated_at:now}));const{error:itemError}=await supabase.from("user_routine_items").insert(rows);if(itemError){await supabase.from("user_routines").delete().eq("id",routine.id);throw itemError;}}
 return routine.id;
}
export async function loadMyRoutines():Promise<RoutineListItem[]>{const{data,error}=await supabase.from("user_routines").select("id,user_id,skin_profile_id,title,description,routine_goal,climate,usage_weeks,overall_rating,visibility,published_at,created_at,user_routine_items(id,product_id,custom_product_name,period,step_order,step_category,frequency,usage_note,products(id,brand,name,brand_local_name,brand_english_name,product_local_name,product_english_name))").order("updated_at",{ascending:false});if(error)throw error;return(data||[]).map(mapRoutine);}
export async function loadPublicRoutines(limit=50):Promise<RoutineListItem[]>{const{data,error}=await supabase.from("user_routines").select("id,user_id,skin_profile_id,title,description,routine_goal,climate,usage_weeks,overall_rating,visibility,published_at,created_at,user_routine_items(id,product_id,custom_product_name,period,step_order,step_category,frequency,usage_note,products(id,brand,name,brand_local_name,brand_english_name,product_local_name,product_english_name)),skin_profiles(skin_answers,profile_answers,selected_symptoms)").eq("visibility","public").eq("status","active").order("published_at",{ascending:false}).limit(limit);if(error)throw error;return(data||[]).map(mapRoutine);}
export async function savePublicRoutine(routineId:string):Promise<void>{const{data:userData,error:userError}=await supabase.auth.getUser();if(userError)throw userError;if(!userData.user)throw new Error("请先登录后收藏 Routine。");const{error}=await supabase.from("saved_routines").upsert({user_id:userData.user.id,routine_id:routineId},{onConflict:"user_id,routine_id"});if(error)throw error;}
export async function deleteMyRoutine(routineId:string):Promise<void>{const{error}=await supabase.from("user_routines").delete().eq("id",routineId);if(error)throw error;}
function mapRoutine(row:any):RoutineListItem{return{id:row.id,userId:row.user_id,skinProfileId:row.skin_profile_id,title:row.title,description:row.description||"",goals:row.routine_goal||[],climate:row.climate,usageWeeks:row.usage_weeks,overallRating:row.overall_rating,visibility:row.visibility,publishedAt:row.published_at,createdAt:row.created_at,items:(row.user_routine_items||[]).map((i:any)=>({id:i.id,productId:i.product_id,customProductName:i.custom_product_name,period:i.period,stepOrder:i.step_order,stepCategory:i.step_category,frequency:i.frequency,usageNote:i.usage_note||"",product:i.products||null})).sort((a:any,b:any)=>a.period.localeCompare(b.period)||a.stepOrder-b.stepOrder),skinProfile:Array.isArray(row.skin_profiles)?row.skin_profiles[0]||null:row.skin_profiles||null};}
