import { createClient, type Session } from "@supabase/supabase-js";
import type { FormulaDna } from "../intelligence/formulaDna";

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || "https://tepiqcwytynhrjhtvnws.supabase.co";
const supabasePublishableKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "sb_publishable_J9GjGc-hNTEvpl-MTyRAiw__JuISs-T";
export const supabase = createClient(supabaseUrl, supabasePublishableKey, { auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true } });

export interface ProductEditorial {
  summary?:string;
  bestFor:string[];
  notIdealFor:string[];
  caveats:string[];
  evidenceLevel?:string;
}
export interface SharedProductRecord { id:string; brand:string; name:string; brandLocalName?:string; brandEnglishName?:string; productLocalName?:string; productEnglishName?:string; searchAliases?:string[]; sourceLocale?:string; category:string; mainCategory?:string; productSubtype?:string; productFunctions?:string[]; ingredients:string[]; ingredientListType:"full"|"partial"; dataCompleteness:number; sourceUrl:string; verifiedAt:string; formulaDna?:FormulaDna; formulaSummary?:string; formulaVerdict?:string; formulaBestFor?:string[]; formulaAlsoWorksFor?:string[]; formulaLessIdealFor?:string[]; formulaCaveats?:string[]; editorial?:ProductEditorial; popularityRank?:number; popularityBasis?:string; popularitySources?:string[]; popularityTier?:"multi-source-popular"|"retailer-bestseller"|"open-data-popular"; asiaAvailabilityStatus?:"cross_border_verified"|"unverified"; qualityFlags?:string[]; source:"shared"; }
export interface ProductDetailRecord extends SharedProductRecord { market:string; formulaId:string; fullIngredients:string[]; }
export interface ParsedSubmission { recognized:Array<{canonicalName:string}>; unknown:Array<{raw:string}>; coverage:number; }
export interface PublicProductExperience { id:string; productKey:string; skinType:string; sensitivity:string; concerns:string[]; reaction:"better"|"neutral"|"irritated"; texture:"love"|"okay"|"dislike"; repurchase:"yes"|"maybe"|"no"; note:string; updatedAt:string; }
export interface PublicProductExperienceInput { productKey:string; skinType:string; sensitivity:string; concerns:string[]; reaction:PublicProductExperience["reaction"]; texture:PublicProductExperience["texture"]; repurchase:PublicProductExperience["repurchase"]; note:string; }

export async function loadPublicProductExperiences(productKey:string):Promise<PublicProductExperience[]>{ const{data,error}=await supabase.from("product_experiences").select("id,product_key,skin_type,sensitivity,concerns,reaction,texture,repurchase,note,updated_at").eq("product_key",productKey).order("updated_at",{ascending:false}).limit(30); if(error)throw error; return(data||[]).map(row=>({id:row.id,productKey:row.product_key,skinType:row.skin_type,sensitivity:row.sensitivity,concerns:row.concerns||[],reaction:row.reaction,texture:row.texture,repurchase:row.repurchase,note:row.note||"",updatedAt:row.updated_at})); }
export async function savePublicProductExperience(input:PublicProductExperienceInput):Promise<void>{ const{data:userData,error:userError}=await supabase.auth.getUser(); if(userError)throw userError;if(!userData.user)throw new Error("请先登录，再公开提交使用体验。"); const{error}=await supabase.rpc("save_product_experience",{p_product_key:input.productKey,p_skin_type:input.skinType,p_sensitivity:input.sensitivity,p_concerns:input.concerns.slice(0,8),p_reaction:input.reaction,p_texture:input.texture,p_repurchase:input.repurchase,p_note:input.note.trim().slice(0,500)});if(error)throw error; }

export async function loadSharedProductCatalog():Promise<SharedProductRecord[]>{
 const pageSize=500;
 const fetchAll=async(table:string,select:string,configure?:(query:any)=>any)=>{
  const rows:any[]=[];
  for(let from=0;;from+=pageSize){
   let query=supabase.from(table).select(select).range(from,from+pageSize-1);
   if(configure)query=configure(query);
   const{data,error}=await query;
   if(error)throw error;
   const page=data||[];
   rows.push(...page);
   if(page.length<pageSize)break;
  }
  return rows;
 };
 const[data,notes]=await Promise.all([
  fetchAll("approved_product_catalog_summary","id,brand,name,brand_local_name,brand_english_name,product_local_name,product_english_name,search_aliases,source_locale,category,main_category,product_subtype,product_functions,ingredient_names,ingredient_list_type,data_completeness,source_url,popularity_sources,popularity_tier,asia_availability_status,formula_function_summary,formula_best_for,formula_also_works_for,formula_less_ideal_for,formula_caveats,formula_verdict",query=>query.order("brand",{ascending:true}).order("name",{ascending:true})),
  fetchAll("product_editorial_notes","product_id,recommendation_summary,best_for,not_ideal_for,caveats,evidence_level",query=>query.eq("locale","zh-CN").order("product_id",{ascending:true}))
 ]);
 const notesByProduct=new Map((notes||[]).map(note=>[note.product_id,note]));
 return(data||[]).map(row=>{const note=notesByProduct.get(row.id);return{id:`shared-${row.id}`,brand:row.brand||"未知品牌",name:row.name||"未命名产品",brandLocalName:row.brand_local_name||undefined,brandEnglishName:row.brand_english_name||undefined,productLocalName:row.product_local_name||undefined,productEnglishName:row.product_english_name||undefined,searchAliases:row.search_aliases||[],sourceLocale:row.source_locale||undefined,category:row.category||"其他",mainCategory:row.main_category||undefined,productSubtype:row.product_subtype||undefined,productFunctions:row.product_functions||[],ingredients:row.ingredient_names||[],ingredientListType:row.ingredient_list_type==="full"?"full":"partial",dataCompleteness:row.data_completeness||0,sourceUrl:row.source_url||"",verifiedAt:"",formulaSummary:row.formula_function_summary||undefined,formulaVerdict:row.formula_verdict||undefined,formulaBestFor:row.formula_best_for||[],formulaAlsoWorksFor:row.formula_also_works_for||[],formulaLessIdealFor:row.formula_less_ideal_for||[],formulaCaveats:row.formula_caveats||[],editorial:note?{summary:note.recommendation_summary||undefined,bestFor:note.best_for||[],notIdealFor:note.not_ideal_for||[],caveats:note.caveats||[],evidenceLevel:note.evidence_level||undefined}:undefined,popularitySources:row.popularity_sources||[],popularityTier:row.popularity_tier||undefined,asiaAvailabilityStatus:row.asia_availability_status||"unverified",qualityFlags:[] as string[],source:"shared"}});
}
export async function loadProductDetail(productId:string):Promise<ProductDetailRecord>{const id=productId.replace(/^shared-/,"");const[{data,error},{data:note}]=await Promise.all([supabase.from("approved_product_catalog").select("id,brand,name,brand_local_name,brand_english_name,product_local_name,product_english_name,source_locale,category,main_category,product_subtype,product_functions,market,source_url,formula_id,ingredient_names,ingredient_list_type,data_completeness,verified_at,formula_function_summary,formula_best_for,formula_also_works_for,formula_less_ideal_for,formula_caveats,formula_verdict").eq("id",id).limit(1).single(),supabase.from("product_editorial_notes").select("recommendation_summary,best_for,not_ideal_for,caveats,evidence_level").eq("product_id",id).eq("locale","zh-CN").maybeSingle()]);if(error)throw error;return{id:`shared-${data.id}`,brand:data.brand||"未知品牌",name:data.name||"未命名产品",brandLocalName:data.brand_local_name||undefined,brandEnglishName:data.brand_english_name||undefined,productLocalName:data.product_local_name||undefined,productEnglishName:data.product_english_name||undefined,sourceLocale:data.source_locale||undefined,category:data.category||"其他",mainCategory:data.main_category||undefined,productSubtype:data.product_subtype||undefined,productFunctions:data.product_functions||[],market:data.market||"global",formulaId:data.formula_id||"",ingredients:(data.ingredient_names||[]).slice(0,15),fullIngredients:data.ingredient_names||[],ingredientListType:data.ingredient_list_type==="full"?"full":"partial",dataCompleteness:data.data_completeness||0,sourceUrl:data.source_url||"",verifiedAt:data.verified_at||"",formulaSummary:data.formula_function_summary||undefined,formulaVerdict:data.formula_verdict||undefined,formulaBestFor:data.formula_best_for||[],formulaAlsoWorksFor:data.formula_also_works_for||[],formulaLessIdealFor:data.formula_less_ideal_for||[],formulaCaveats:data.formula_caveats||[],editorial:note?{summary:note.recommendation_summary||undefined,bestFor:note.best_for||[],notIdealFor:note.not_ideal_for||[],caveats:note.caveats||[],evidenceLevel:note.evidence_level||undefined}:undefined,source:"shared"};}

export async function sendSignInLink(email:string):Promise<void>{const redirectUrl=window.location.hostname==="localhost"?`${window.location.origin}${import.meta.env.BASE_URL}`:"https://littleruirui.github.io/skincare101/?auth=callback";const{error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:redirectUrl}});if(error)throw error;}
export async function signInWithPassword(email:string,password:string):Promise<void>{const{error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;}
export async function signUpWithPassword(email:string,password:string):Promise<void>{const{data,error}=await supabase.auth.signUp({email,password});if(error)throw error;if(!data.session)throw new Error("账号已创建，但数据库仍要求邮件确认。请关闭 Supabase Auth 的 Confirm email 后再注册。");}
export async function currentSession():Promise<Session|null>{const{data,error}=await supabase.auth.getSession();if(error)throw error;return data.session;}

function defaultProfileName(date=new Date()):string{const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,"0"),d=String(date.getDate()).padStart(2,"0"),h=String(date.getHours()).padStart(2,"0"),min=String(date.getMinutes()).padStart(2,"0");return `肤质档案 · ${y}-${m}-${d} ${h}:${min}`;}
export interface SkinProfileInput { skinAnswers:Record<string,string>; profileAnswers:Record<string,string>; selectedSymptoms:string[]; symptomAnswers:Record<string,Record<string,string>>; multiSelectAnswers:Record<string,Record<string,string[]>>; redFlag:string|null; }
export async function saveMySkinProfile(input:SkinProfileInput,name=""):Promise<void>{const{data:userData,error:userError}=await supabase.auth.getUser();if(userError)throw userError;if(!userData.user)throw new Error("请先登录再保存皮肤档案。");const{error:clearError}=await supabase.from("skin_profiles").update({is_active:false}).eq("user_id",userData.user.id).eq("is_active",true);if(clearError)throw clearError;const{error}=await supabase.from("skin_profiles").insert({user_id:userData.user.id,name:name.trim()||defaultProfileName(),is_active:true,skin_answers:input.skinAnswers,profile_answers:input.profileAnswers,selected_symptoms:input.selectedSymptoms,symptom_answers:input.symptomAnswers,multi_select_answers:input.multiSelectAnswers,red_flag:input.redFlag,updated_at:new Date().toISOString()});if(error)throw error;}

export interface ProductSubmissionInput { brand:string; productName:string; category:string; market:string; rawIngredients:string; parseResult:ParsedSubmission; ingredientsPhoto?:File|null; }
export async function submitProductContribution(input:ProductSubmissionInput):Promise<string>{const session=await currentSession();if(!session?.user)throw new Error("请先登录再提交产品。");const recognized=input.parseResult.recognized.map(i=>i.canonicalName),unknown=input.parseResult.unknown.map(i=>i.raw);if(!recognized.length)throw new Error("至少需要识别并确认一个标准成分。");const{data:draft,error:draftError}=await supabase.from("product_submissions").insert({brand:input.brand.trim(),product_name:input.productName.trim(),category:input.category,market:input.market,raw_ingredients:input.rawIngredients.trim(),parsed_ingredients:recognized,unknown_ingredients:unknown,data_completeness:input.parseResult.coverage,status:"draft"}).select("id").single();if(draftError||!draft)throw draftError||new Error("无法建立投稿草稿。");if(input.ingredientsPhoto){const extension=input.ingredientsPhoto.name.split(".").pop()?.toLowerCase()||"jpg",storagePath=`${session.user.id}/${draft.id}/ingredients.${extension}`;const{error:uploadError}=await supabase.storage.from("product-submissions").upload(storagePath,input.ingredientsPhoto,{cacheControl:"3600",contentType:input.ingredientsPhoto.type||"image/jpeg",upsert:false});if(uploadError)throw uploadError;const{error:imageRowError}=await supabase.from("submission_images").insert({submission_id:draft.id,kind:"ingredients",storage_path:storagePath});if(imageRowError){await supabase.storage.from("product-submissions").remove([storagePath]);throw imageRowError;}}const{error:submitError}=await supabase.from("product_submissions").update({status:"pending",submitted_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",draft.id);if(submitError)throw submitError;return draft.id;}
export async function loadMySubmissions(){const{data,error}=await supabase.from("product_submissions").select("id,brand,product_name,status,rejection_reason,created_at").order("created_at",{ascending:false}).limit(10);if(error)throw error;return data||[];}
export async function loadPendingReviewQueue(){const{data,error}=await supabase.from("product_submissions").select("id,brand,product_name,category,market,raw_ingredients,parsed_ingredients,unknown_ingredients,data_completeness,status,created_at,submission_images(storage_path,kind)").in("status",["pending","reviewing"]).order("created_at",{ascending:true});if(error)throw error;return Promise.all((data||[]).map(async(submission:any)=>{const image=submission.submission_images?.find((i:any)=>i.kind==="ingredients");if(!image)return{...submission,imageUrl:null};const{data:signed}=await supabase.storage.from("product-submissions").createSignedUrl(image.storage_path,900);return{...submission,imageUrl:signed?.signedUrl||null};}));}
export async function approveSubmission(id:string,sourceUrl?:string):Promise<void>{const{error}=await supabase.rpc("approve_product_submission",{p_submission_id:id,p_source_url:sourceUrl||null});if(error)throw error;}
export async function rejectSubmission(id:string,reason:string):Promise<void>{const{error}=await supabase.rpc("reject_product_submission",{p_submission_id:id,p_reason:reason});if(error)throw error;}