import React,{useEffect,useMemo,useState}from"react";
import{ArrowLeft,RefreshCw,ShieldCheck}from"lucide-react";
import{supabase}from"../lib/supabase";
import{useLanguage}from"../lib/i18n";
const BG="#F6F0E3",CARD="#FBF6EA",INK="#283027",LINE="#D7CDB8",SAGE="#2F5A40",MUTE="#6F6A5F",ROSE="#A96F68";
type Summary={registered_users_total:number;registered_users_7d:number;searches_total:number;zero_result_searches:number;routines_created:number;feedback_events:number;affiliate_clicks:number};
type EventRow={session_id:string|null;user_id:string|null;event_name:string;page_name:string|null;search_query:string|null;search_result_count:number|null;metadata:Record<string,unknown>|null;created_at:string};
type Period=1|7|30;
function metaText(e:EventRow,key:string){const v=e.metadata?.[key];return typeof v==="string"&&v.trim()?v.trim():""}
function dayKey(x:string){return x.slice(0,10)}
function errorText(err:unknown){if(err instanceof Error)return err.message;if(err&&typeof err==="object"){const x=err as Record<string,unknown>;return [x.message,x.details,x.hint,x.code].filter(Boolean).map(String).join(" · ")||"Analytics request failed"}return String(err)}
function pageLabel(name:string,t:(zh:string,en:string)=>string){const labels:Record<string,[string,string]>={home:["首页","Home"],mySkin:["我的肤质","My Skin"],explore:["发现","Discover"],routine:["护肤 Routine","Routine"],account:["我的","Me"],product_detail:["产品详情","Product detail"],play_niuma:["牛马测试","Play · Niuma"]};const hit=labels[name];return hit?t(hit[0],hit[1]):name}
async function loadEvents(days:number){const since=new Date(Date.now()-days*86400000).toISOString();const out:EventRow[]=[];for(let page=0;page<10;page++){const from=page*1000,to=from+999;const{data,error}=await supabase.from("analytics_events").select("session_id,user_id,event_name,page_name,search_query,search_result_count,metadata,created_at").gte("created_at",since).order("created_at",{ascending:false}).range(from,to);if(error)throw error;const rows=(data||[]) as EventRow[];out.push(...rows);if(rows.length<1000)break}return out}
export default function AdminAnalyticsPanel({onBack}:{onBack:()=>void}){const{t}=useLanguage();const[allowed,setAllowed]=useState<boolean|null>(null);const[summary,setSummary]=useState<Summary|null>(null);const[events,setEvents]=useState<EventRow[]>([]);const[period,setPeriod]=useState<Period>(7);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");const[loadedAt,setLoadedAt]=useState<Date|null>(null);
 async function refresh(){setBusy(true);setMsg("");try{const{data:isAdmin,error:a}=await supabase.rpc("is_admin");if(a)throw a;setAllowed(Boolean(isAdmin));if(!isAdmin)return;const e=await loadEvents(30);setEvents(e);setLoadedAt(new Date());const s=await supabase.from("admin_analytics_summary").select("*").maybeSingle();if(!s.error&&s.data)setSummary(s.data as Summary);else if(s.error)setMsg(t("核心访问数据已加载；注册/转化汇总暂不可用。","Core traffic data loaded; registration/conversion summary is temporarily unavailable."))}catch(err){setMsg(errorText(err))}finally{setBusy(false)}}useEffect(()=>{void refresh()},[]);
 const data=useMemo(()=>{const cut=Date.now()-period*86400000;return events.filter(e=>new Date(e.created_at).getTime()>=cut)},[events,period]);
 const metrics=useMemo(()=>{const sessions=new Set(data.map(e=>e.session_id).filter(Boolean));const visitorIds=new Set(data.map(e=>metaText(e,"visitor_id")).filter(Boolean));const users=new Set(data.map(e=>e.user_id).filter(Boolean));const pv=data.filter(e=>e.event_name==="journey_page_view"||e.event_name==="play_page_view").length;const product=data.filter(e=>e.event_name==="product_detail_view").length;const playStart=data.filter(e=>e.event_name==="play_start").length;const playDone=data.filter(e=>e.event_name==="play_complete").length;const skinClick=data.filter(e=>e.event_name==="skin_quiz_click").length;const search=data.filter(e=>e.event_name==="search").length;const legacySessions=new Set(data.filter(e=>!metaText(e,"visitor_id")).map(e=>e.session_id).filter(Boolean));const daysByVisitor=new Map<string,Set<string>>();data.forEach(e=>{const id=metaText(e,"visitor_id");if(!id)return;const set=daysByVisitor.get(id)||new Set<string>();set.add(dayKey(e.created_at));daysByVisitor.set(id,set)});const returning=[...daysByVisitor.values()].filter(x=>x.size>=2).length;return{sessions:sessions.size,visitors:visitorIds.size,legacySessions:legacySessions.size,loggedIn:users.size,pv,product,playStart,playDone,skinClick,search,returning,playRate:playStart?Math.round(playDone/playStart*100):0,skinRate:playDone?Math.round(skinClick/playDone*100):0,pagesPerSession:sessions.size?Math.round(pv/sessions.size*10)/10:0,productRate:pv?Math.round(product/pv*100):0}},[data]);
 const sources=useMemo(()=>{const map=new Map<string,Set<string>>();data.filter(e=>e.event_name==="session_start"||e.event_name==="play_page_view").forEach(e=>{const src=metaText(e,"traffic_source")||metaText(e,"utm_source")||"unknown / legacy";const id=metaText(e,"visitor_id")||e.session_id||"unknown";const set=map.get(src)||new Set<string>();set.add(id);map.set(src,set)});const rows=[...map.entries()].map(([source,set])=>({source,n:set.size})).sort((a,b)=>b.n-a.n).slice(0,12);const total=rows.reduce((s,x)=>s+x.n,0);return rows.map(x=>({...x,pct:total?Math.round(x.n/total*100):0}))},[data]);
 const pages=useMemo(()=>{const map=new Map<string,number>();data.filter(e=>e.event_name==="journey_page_view"||e.event_name==="product_detail_view"||e.event_name==="play_page_view").forEach(e=>{const name=e.page_name||metaText(e,"route")||e.event_name;map.set(name,(map.get(name)||0)+1)});return[...map.entries()].sort((a,b)=>b[1]-a[1]).slice(0,12)},[data]);
 const searches=useMemo(()=>{const map=new Map<string,{n:number,zero:number}>();data.filter(e=>e.event_name==="search"&&e.search_query?.trim()).forEach(e=>{const key=e.search_query!.trim();const row=map.get(key)||{n:0,zero:0};row.n++;if(e.search_result_count===0)row.zero++;map.set(key,row)});return[...map.entries()].map(([q,v])=>({q,...v})).sort((a,b)=>b.n-a.n).slice(0,12)},[data]);
 const trend=useMemo(()=>{const count=Math.min(period,14);const days:Array<{key:string,label:string,pv:number,sessions:Set<string>}>=[];for(let i=count-1;i>=0;i--){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-i);const key=d.toISOString().slice(0,10);days.push({key,label:d.toLocaleDateString(undefined,{month:"numeric",day:"numeric"}),pv:0,sessions:new Set()})}const map=new Map(days.map(x=>[x.key,x]));data.forEach(e=>{const d=map.get(dayKey(e.created_at));if(!d)return;if(e.event_name==="journey_page_view"||e.event_name==="play_page_view")d.pv++;if(e.session_id)d.sessions.add(e.session_id)});return days},[data,period]);
 const lastEvent=events[0]?.created_at?new Date(events[0].created_at):null;
 if(allowed===false)return <Page><button onClick={onBack} style={back}><ArrowLeft size={14}/>{t("返回","Back")}</button><h1>{t("无管理权限","Admin access required")}</h1></Page>;
 return <Page><button onClick={onBack} style={back}><ArrowLeft size={14}/>{t("返回管理后台","Back to admin")}</button><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12}}><div><div style={{fontSize:10,letterSpacing:".12em",color:SAGE,fontWeight:800}}>PEACED SKIN ANALYTICS</div><h1 style={{fontSize:32,margin:"7px 0 4px"}}>{t("经营数据","Growth dashboard")}</h1><div style={{fontSize:12,color:MUTE}}>{t("流量、回访、产品使用、搜索和 Play 转化。","Traffic, retention, product usage, search and Play conversion.")}</div></div><button onClick={()=>void refresh()} disabled={busy} style={icon} aria-label={t("刷新","Refresh")}><RefreshCw size={16}/></button></div>
 <div style={{display:"flex",gap:7,margin:"16px 0 8px"}}>{([1,7,30] as Period[]).map(x=><button key={x} onClick={()=>setPeriod(x)} style={{...pill,background:period===x?"#E8EFE7":"white",borderColor:period===x?SAGE:LINE,color:period===x?SAGE:MUTE}}>{x===1?t("近24小时","24H"):x+"D"}</button>)}</div>
 <div style={{fontSize:10.5,color:MUTE,marginBottom:14}}>{lastEvent?t(`最近事件：${lastEvent.toLocaleString()}`,`Latest event: ${lastEvent.toLocaleString()}`):t("暂无事件","No events yet")}{loadedAt?` · ${t("刷新","refreshed")} ${loadedAt.toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}`:""}</div>
 {msg&&<div style={{...card,color:ROSE}}>{msg}</div>}
 <div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:9,marginBottom:14}}><M label={t("已识别独立访客","Identified visitors")} v={metrics.visitors}/><M label={t("会话","Sessions")} v={metrics.sessions}/><M label={t("页面浏览","Page views")} v={metrics.pv}/><M label={t("回访访客","Returning")} v={metrics.returning}/><M label={t("每会话页面","Pages / session")} v={metrics.pagesPerSession}/><M label={t("产品详情","Product views")} v={metrics.product}/><M label={t("产品浏览率","Product engagement")} v={metrics.productRate} suffix="%"/><M label={t("搜索","Searches")} v={metrics.search}/><M label={t("Play 开始","Play starts")} v={metrics.playStart}/><M label={t("Play 完成","Play completes")} v={metrics.playDone}/><M label={t("Play 完成率","Play completion")} v={metrics.playRate} suffix="%"/><M label={t("Play→肤质测试","Play → Skin quiz")} v={metrics.skinRate} suffix="%"/><M label={t("登录用户活跃","Signed-in visitors")} v={metrics.loggedIn}/><M label={t("注册用户总数","Registered users")} v={summary?.registered_users_total||0}/></div>
 {metrics.legacySessions>0&&<div style={{...card,fontSize:11.5,color:MUTE,lineHeight:1.6}}>{t(`另有 ${metrics.legacySessions} 个旧会话发生在 visitor ID 埋点完善前，因此不会硬算成“独立访客”，避免把同一个人重复计算。`,`There are also ${metrics.legacySessions} legacy sessions from before visitor-ID tracking was complete. They are not forced into the unique-visitor count to avoid double counting.`)}</div>}
 <section style={card}><Title>{t("访问趋势","Traffic trend")}</Title><div style={{display:"grid",gap:8}}>{trend.map(x=>{const max=Math.max(1,...trend.map(y=>y.pv));return <div key={x.key} style={{display:"grid",gridTemplateColumns:"42px 1fr 58px",gap:8,alignItems:"center",fontSize:10.5}}><span style={{color:MUTE}}>{x.label}</span><div style={{height:8,borderRadius:999,background:"#ECE5D8",overflow:"hidden"}}><div style={{height:"100%",width:`${Math.max(x.pv?4:0,x.pv/max*100)}%`,background:SAGE,borderRadius:999}}/></div><span style={{textAlign:"right",color:MUTE}}>{x.pv} PV</span></div>})}</div></section>
 <section style={card}><Title>{t("来源","Traffic sources")}</Title>{sources.length?sources.map(x=><Row key={x.source}><b>{x.source}</b><span>{x.n} · {x.pct}%</span></Row>):<Empty>{t("新来源埋点上线后会从这里开始累计；旧数据会显示为 legacy。","New source tracking will accumulate here; older traffic appears as legacy.")}</Empty>}</section>
 <section style={card}><Title>{t("核心漏斗","Core funnel")}</Title><F label={t("已识别访客","Identified visitors")} value={metrics.visitors}/><F label={t("查看产品","Product view")} value={metrics.product}/><F label={t("Play 完成","Play complete")} value={metrics.playDone}/><F label={t("从 Play 进入肤质测试","Play → Skin quiz")} value={metrics.skinClick}/></section>
 <section style={card}><Title>{t("最常访问页面","Top pages")}</Title>{pages.length?pages.map(([name,n])=><Row key={name}><b>{pageLabel(name,t)}</b><span>{n}</span></Row>):<Empty>{t("暂无页面浏览。","No page views yet.")}</Empty>}</section>
 <section style={card}><Title>{t("最常搜索","Top searches")}</Title>{searches.length?searches.map(x=><Row key={x.q}><b>{x.q}</b><span>{x.n}{x.zero?` · ${x.zero} zero`:""}</span></Row>):<Empty>{t("暂无搜索。","No searches yet.")}</Empty>}</section>
 {summary&&<section style={card}><Title>{t("产品与转化辅助指标","Product & conversion")}</Title><Row><b>{t("近7天新增注册","New registrations · 7d")}</b><span>{summary.registered_users_7d}</span></Row><Row><b>{t("零结果搜索（累计）","Zero-result searches · all-time")}</b><span>{summary.zero_result_searches}</span></Row><Row><b>{t("Routine 创建（累计）","Routines created · all-time")}</b><span>{summary.routines_created}</span></Row><Row><b>{t("反馈（累计）","Feedback · all-time")}</b><span>{summary.feedback_events}</span></Row><Row><b>{t("Affiliate 点击（累计）","Affiliate clicks · all-time")}</b><span>{summary.affiliate_clicks}</span></Row></section>}
 <div style={{...card,fontSize:11.5,color:MUTE,lineHeight:1.65}}><ShieldCheck size={14} style={{verticalAlign:"-2px",marginRight:6}}/>{t("只有 is_admin() 通过的账号可以读取 Analytics。匿名 visitor ID 仅用于计算独立访客与回访，不记录完整 IP。","Only accounts passing is_admin() can read analytics. Anonymous visitor IDs are used for visitor/returning counts; full IP addresses are not stored.")}</div></Page>}
function Page({children}:{children:React.ReactNode}){return <div style={{minHeight:"100vh",background:BG,color:INK,padding:"22px 16px 64px"}}><div style={{maxWidth:820,margin:"0 auto"}}>{children}</div></div>}
function M({label,v,suffix=""}:{label:string;v:number;suffix?:string}){return <div style={{...card,marginBottom:0,padding:14}}><div style={{fontSize:10.5,color:MUTE}}>{label}</div><div style={{fontSize:26,fontWeight:750,marginTop:3}}>{v}{suffix}</div></div>}
function F({label,value}:{label:string;value:number}){return <div style={{display:"flex",justifyContent:"space-between",gap:12,padding:"9px 0",borderTop:`1px solid ${LINE}`,fontSize:12}}><b>{label}</b><span>{value}</span></div>}
function Title({children}:{children:React.ReactNode}){return <div style={{fontSize:11,fontWeight:750,color:SAGE,letterSpacing:".06em",marginBottom:8}}>{children}</div>}
function Row({children}:{children:React.ReactNode}){return <div style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) auto",gap:12,padding:"9px 0",borderTop:`1px solid ${LINE}`,fontSize:11.5}}>{children}</div>}
function Empty({children}:{children:React.ReactNode}){return <div style={{fontSize:11.5,color:MUTE,padding:"8px 0"}}>{children}</div>}
const card:React.CSSProperties={border:`1px solid ${LINE}`,borderRadius:18,padding:15,background:CARD,marginBottom:12};const back:React.CSSProperties={border:0,background:"transparent",padding:0,color:MUTE,fontSize:12,display:"flex",alignItems:"center",gap:6,cursor:"pointer",marginBottom:22};const icon:React.CSSProperties={border:`1px solid ${LINE}`,borderRadius:12,padding:9,background:"white",color:SAGE,cursor:"pointer"};const pill:React.CSSProperties={border:"1px solid",borderRadius:999,padding:"8px 12px",fontSize:11,fontWeight:750,cursor:"pointer"};