import React,{useEffect,useMemo,useState}from"react";
import{ArrowLeft,Database,RefreshCw,ShieldCheck,Users,MessageSquareWarning,Search,KeyRound}from"lucide-react";
import{supabase}from"../lib/supabase";
import{useLanguage}from"../lib/i18n";

const BG="#F6F0E3",CARD="#FBF6EA",INK="#283027",LINE="#D7CDB8",SAGE="#2F5A40",MUTE="#6F6A5F",ROSE="#A96F68";
type Summary={total_products:number;total_brands:number;brands_needing_profile:number;missing_english_name:number;missing_local_name:number;missing_source:number;duplicate_groups:number;open_reports:number;missing_searches:number;user_experiences:number};
type Dup={canonical_key:string;duplicate_count:number;labels:string[]};
type BrandGap={brand_key:string;brand_name:string;brand_local_name?:string|null;status:string;country_region?:string|null;segment?:string|null;product_count:number};
type Report={id:string;report_type:string;message:string;status:string;created_at:string;reporter_email?:string|null;product_id?:string|null};
type Experience={id:string;product_key:string;skin_type:string;sensitivity:string;reaction:string;texture:string;repurchase:string;note?:string|null;created_at:string};
type AuthUser={id:string;email:string;created_at:string;last_sign_in_at?:string|null};

export default function AdminDashboard({onBack}:{onBack:()=>void}){const{t}=useLanguage();const[allowed,setAllowed]=useState<boolean|null>(null);const[summary,setSummary]=useState<Summary|null>(null);const[dups,setDups]=useState<Dup[]>([]);const[brands,setBrands]=useState<BrandGap[]>([]);const[reports,setReports]=useState<Report[]>([]);const[experiences,setExperiences]=useState<Experience[]>([]);const[users,setUsers]=useState<AuthUser[]>([]);const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const[tab,setTab]=useState<"qa"|"feedback"|"users">("qa");const[q,setQ]=useState("");
 async function invoke(body:Record<string,unknown>){const{data,error}=await supabase.functions.invoke("admin-console",{body});if(error)throw error;return data}
 async function refresh(){setBusy(true);setMessage("");try{const{data:isAdmin,error:adminError}=await supabase.rpc("is_admin");if(adminError)throw adminError;setAllowed(Boolean(isAdmin));if(!isAdmin)return;const[s,d,b,r,e,u]=await Promise.all([supabase.from("admin_qa_summary").select("*").maybeSingle(),supabase.from("admin_duplicate_candidates").select("*").limit(50),supabase.from("admin_brand_gaps").select("*").limit(100),supabase.from("product_data_reports").select("id,report_type,message,status,created_at,reporter_email,product_id").order("created_at",{ascending:false}).limit(100),supabase.from("product_experiences").select("id,product_key,skin_type,sensitivity,reaction,texture,repurchase,note,created_at").order("created_at",{ascending:false}).limit(100),invoke({action:"listUsers",page:1,perPage:100})]);if(s.error)throw s.error;if(d.error)throw d.error;if(b.error)throw b.error;if(r.error)throw r.error;if(e.error)throw e.error;setSummary(s.data as Summary);setDups((d.data||[]) as Dup[]);setBrands((b.data||[]) as BrandGap[]);setReports((r.data||[]) as Report[]);setExperiences((e.data||[]) as Experience[]);setUsers((u?.users||[]) as AuthUser[])}catch(err){setMessage(err instanceof Error?err.message:String(err))}finally{setBusy(false)}}
 useEffect(()=>{void refresh()},[]);
 async function reset(email:string){if(!window.confirm(t(`给 ${email} 发送密码重置邮件？`,`Send a password reset email to ${email}?`)))return;setMessage("");try{await invoke({action:"sendPasswordReset",email,redirectTo:window.location.origin+window.location.pathname});setMessage(t("密码重置邮件已发送。管理员不会看到或设置用户的新密码。","Password reset email sent. Admins never see or set the user's new password."))}catch(err){setMessage(err instanceof Error?err.message:String(err))}}
 const filteredUsers=useMemo(()=>users.filter(x=>!q.trim()||x.email.toLowerCase().includes(q.toLowerCase())),[users,q]);
 if(allowed===false)return <Page><button onClick={onBack} style={back}><ArrowLeft size={14}/>{t("返回","Back")}</button><h1>{t("无管理权限","Admin access required")}</h1><p style={{color:MUTE}}>{t("这个后台只对管理员账号开放。","This console is available only to admin accounts.")}</p></Page>;
 return <Page><button onClick={onBack} style={back}><ArrowLeft size={14}/>{t("返回网站","Back to site")}</button><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center"}}><div><div style={{fontSize:10,letterSpacing:".12em",color:SAGE,fontWeight:800}}>SKINCARE101 ADMIN</div><h1 style={{fontSize:32,margin:"7px 0 4px"}}>{t("管理后台","Admin console")}</h1><div style={{fontSize:12,color:MUTE}}>{t("产品数据 QA、用户反馈、搜索缺口与账号支持集中在这里。","Product QA, feedback, search gaps and account support in one place.")}</div></div><button onClick={()=>void refresh()} disabled={busy} style={iconBtn}><RefreshCw size={16}/></button></div>{message&&<div style={{...card,color:message.includes("失败")?ROSE:SAGE,marginTop:14}}>{message}</div>}
 <div style={{display:"flex",gap:7,margin:"18px 0",overflowX:"auto"}}>{([['qa',t("数据 QA","Data QA"),Database],['feedback',t("用户反馈","Feedback"),MessageSquareWarning],['users',t("用户与密码","Users & access"),Users]] as const).map(([key,label,Icon])=><button key={key} onClick={()=>setTab(key)} style={{...pill,borderColor:tab===key?SAGE:LINE,background:tab===key?"#E9EEE9":"white",color:tab===key?SAGE:MUTE}}><Icon size={14}/>{label}</button>)}</div>
 {tab==='qa'&&<>{summary&&<div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:9}}><Metric label={t("产品","Products")} value={summary.total_products}/><Metric label={t("品牌待补资料","Brand profiles pending")} value={summary.brands_needing_profile} warn/><Metric label={t("疑似重复组","Duplicate groups")} value={summary.duplicate_groups} warn/><Metric label={t("缺来源","Missing sources")} value={summary.missing_source} warn/><Metric label={t("缺英文名","Missing English names")} value={summary.missing_english_name}/><Metric label={t("缺本地名","Missing local names")} value={summary.missing_local_name}/><Metric label={t("开放纠错","Open reports")} value={summary.open_reports} warn/><Metric label={t("零结果搜索","Missing searches")} value={summary.missing_searches}/></div>}<section style={card}><Title>{t("疑似重复产品","Duplicate candidates")}</Title>{dups.length?dups.map((x,i)=><Row key={x.canonical_key}><b>{x.duplicate_count}×</b><span>{(x.labels||[]).join(" / ")}</span></Row>):<Empty>{t("当前没有 canonical-key 完全重复。","No exact canonical-key duplicates right now.")}</Empty>}</section><section style={card}><Title>{t("品牌资料缺口","Brand profile gaps")}</Title>{brands.slice(0,50).map(x=><Row key={x.brand_key}><b>{x.brand_local_name||x.brand_name}</b><span>{x.product_count} {t("款","products")} · {x.status}{x.country_region?` · ${x.country_region}`:""}{x.segment?` · ${x.segment}`:""}</span></Row>)}</section></>}
 {tab==='feedback'&&<><section style={card}><Title>{t("产品数据纠错","Product data reports")}</Title>{reports.length?reports.map(x=><Row key={x.id}><b>{x.report_type} · {x.status}</b><span>{x.message||t("无说明","No note")} · {new Date(x.created_at).toLocaleDateString()}</span></Row>):<Empty>{t("暂无纠错反馈。","No data reports yet.")}</Empty>}</section><section style={card}><Title>{t("真实使用反馈","Product experiences")}</Title>{experiences.length?experiences.map(x=><Row key={x.id}><b>{x.reaction} · {x.skin_type}</b><span>{x.product_key} · {x.note||t("无文字备注","No written note")}</span></Row>):<Empty>{t("暂无使用反馈。","No user experiences yet.")}</Empty>}</section></>}
 {tab==='users'&&<section style={card}><Title>{t("用户账号","User accounts")}</Title><div style={{position:"relative",marginBottom:10}}><Search size={14} color={MUTE} style={{position:"absolute",left:11,top:12}}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t("搜索邮箱","Search email")} style={{width:"100%",boxSizing:"border-box",border:`1px solid ${LINE}`,borderRadius:12,padding:"10px 10px 10px 33px",background:"white"}}/></div>{filteredUsers.map(u=><div key={u.id} style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) auto",gap:10,alignItems:"center",padding:"11px 0",borderTop:`1px solid ${LINE}`}}><div style={{minWidth:0}}><b style={{fontSize:12,overflowWrap:"anywhere"}}>{u.email}</b><div style={{fontSize:10.5,color:MUTE,marginTop:3}}>{t("注册","Joined")}: {new Date(u.created_at).toLocaleDateString()} · {t("最近登录","Last sign-in")}: {u.last_sign_in_at?new Date(u.last_sign_in_at).toLocaleDateString():t("暂无","Never")}</div></div><button onClick={()=>void reset(u.email)} style={smallBtn}><KeyRound size={13}/>{t("发重置邮件","Send reset")}</button></div>)}</section>}
 <div style={{display:"flex",alignItems:"center",gap:6,fontSize:10.5,color:MUTE,marginTop:12}}><ShieldCheck size={14}/>{t("管理员只能发送安全的密码重置邮件，不能查看用户密码，也不会替用户直接设置新密码。","Admins can send secure reset emails but cannot view or directly set user passwords.")}</div></Page>}
function Page({children}:{children:React.ReactNode}){return <div style={{minHeight:"100vh",background:BG,color:INK,padding:"22px 16px 64px"}}><div style={{maxWidth:760,margin:"0 auto"}}>{children}</div></div>}
function Metric({label,value,warn}:{label:string;value:number;warn?:boolean}){return <div style={{...card,marginBottom:0,padding:14}}><div style={{fontSize:10.5,color:MUTE}}>{label}</div><div style={{fontSize:26,fontWeight:750,color:warn&&value?ROSE:INK,marginTop:3}}>{value}</div></div>}
function Title({children}:{children:React.ReactNode}){return <div style={{fontSize:11,fontWeight:750,color:SAGE,letterSpacing:".06em",marginBottom:8}}>{children}</div>}
function Row({children}:{children:React.ReactNode}){return <div style={{display:"grid",gap:3,padding:"9px 0",borderTop:`1px solid ${LINE}`,fontSize:11.5}}>{children}</div>}
function Empty({children}:{children:React.ReactNode}){return <div style={{fontSize:11.5,color:MUTE,padding:"8px 0"}}>{children}</div>}
const card:React.CSSProperties={border:`1px solid ${LINE}`,borderRadius:18,padding:15,background:CARD,marginBottom:12};const back:React.CSSProperties={border:0,background:"transparent",padding:0,color:MUTE,fontSize:12,display:"flex",alignItems:"center",gap:6,cursor:"pointer",marginBottom:22};const pill:React.CSSProperties={border:"1px solid",borderRadius:999,padding:"8px 11px",fontSize:11.5,fontWeight:650,display:"inline-flex",alignItems:"center",gap:6,whiteSpace:"nowrap",cursor:"pointer"};const iconBtn:React.CSSProperties={border:`1px solid ${LINE}`,borderRadius:12,padding:9,background:"white",color:SAGE,cursor:"pointer"};const smallBtn:React.CSSProperties={border:`1px solid ${LINE}`,borderRadius:10,padding:"7px 9px",background:"white",color:SAGE,fontSize:10.5,fontWeight:700,display:"inline-flex",alignItems:"center",gap:5,cursor:"pointer"};