import React from"react";
import{ArrowRight,Leaf,Sparkles}from"lucide-react";
import{useLanguage}from"../lib/i18n";
import{HandDrawnHero}from"./HandDrawnVisuals";
const PAPER="#F6F0E3",INK="#26352A",SAGE="#6F806F",GOLD="#C9A449",BLUSH="#E8D5C8";
type Props={onBegin:()=>void;onStartProfile:()=>void;onOpenSignIn:()=>void;onSignedIn:()=>void;alreadySignedIn?:boolean};
export default function FirstRunOnboarding({onBegin,onStartProfile,onOpenSignIn,alreadySignedIn=false}:Props){const{t}=useLanguage();function start(){onBegin();onStartProfile()}
return <div style={{minHeight:"100vh",background:PAPER,color:INK,display:"grid",placeItems:"center",padding:"30px 18px"}}><div style={{width:"100%",maxWidth:520}}><HandDrawnHero/><div className="peaced-brand" style={{display:"block",width:"fit-content",margin:"0 auto"}} aria-label="PEACED">PEACED</div><h1 style={{fontFamily:"Georgia,'Songti SC',serif",fontWeight:500,fontSize:38,lineHeight:1.13,textAlign:"center",margin:"12px 0"}}>{t("先认识你的皮肤，再决定买什么","Know your skin before choosing what to buy")}</h1><p style={{textAlign:"center",color:"#6E7069",fontSize:14,lineHeight:1.75,maxWidth:390,margin:"0 auto 25px"}}>{t("先完成一份简短的肤质问卷。问卷结束后，如果你想以后继续查看，我们再邀请你登录或注册；你的档案会自动同步到账号。","Start with a short skin questionnaire. When you finish, you can sign in or create an account if you want to keep it; your profile will sync automatically.")}</p><button onClick={start} style={primary}>{alreadySignedIn?t("重新开始我的护肤旅程","Restart my skincare journey"):t("开始我的护肤旅程","Start my skincare journey")} <ArrowRight size={16}/></button>{!alreadySignedIn&&<button onClick={onOpenSignIn} style={link}>{t("已经有账号？直接登录","Already have an account? Sign in")}</button>}</div></div>}
const primary:React.CSSProperties={width:"100%",border:0,borderRadius:999,padding:"13px 18px",background:INK,color:"white",display:"flex",alignItems:"center",justifyContent:"center",gap:8,cursor:"pointer",fontWeight:600};const link:React.CSSProperties={width:"100%",border:0,background:"transparent",color:SAGE,padding:13,cursor:"pointer",fontSize:12};
