import React,{useEffect}from"react";

const ZH_TO_EN:Record<string,string>={
 "我的护肤柜 · My Shelf":"My Shelf","用我的护肤柜搭配 · Use My Shelf":"Use My Shelf","我需要买吗？ · Do I need this?":"Do I need this?","发现数据有误？ · Report":"Report data issue","发现数据有误？ · Report an error":"Report an error","发现成分表有问题？":"Found a formula or product-data issue?","告诉我哪里不对。产品信息会自动带上，你不需要重新填写。提交后会创建一个 GitHub 数据纠错记录，方便后续核查和修正。":"Tell us what looks wrong. Product details are attached automatically. Submitting opens a GitHub data-correction record for review.","问题类型 · Issue type":"Issue type","哪里不对？· What looks wrong?":"What looks wrong?","取消":"Cancel","提交纠错 · Send report":"Send report","建议附官方品牌页、零售商成分页或包装照片来源。请不要提交姓名、电话等个人敏感信息。":"Please attach an official brand page, retailer ingredient page, or packaging source when possible. Do not submit personal information.","查看我的护肤柜":"View My Shelf","知道了":"Got it","成分缺失 · Missing ingredient":"Missing ingredient","成分顺序错误 · Wrong order":"Wrong ingredient order","成分名称错误 · Wrong ingredient name":"Wrong ingredient name","配方已更新 · Formula changed":"Formula changed","版本/地区不对 · Wrong version / market":"Wrong version / market","来源有问题 · Source issue":"Source issue","其他 · Other":"Other","非常适合":"Very suitable","适合":"Suitable","可以用":"Usable","谨慎尝试":"Try cautiously","不推荐":"Not recommended","配方体系 · 辅助参考":"Formula systems · supporting reference","数据可信度 · 高":"Data confidence · High","数据可信度 · 中":"Data confidence · Medium","数据可信度 · 较低":"Data confidence · Low","洁面":"Cleanser","卸妆":"Makeup remover","化妆水":"Toner","精华水":"Essence","精华":"Serum","面霜":"Moisturizer","乳液":"Lotion","乳液 / 面霜":"Lotion / moisturizer","防晒":"Sunscreen","面膜":"Mask","眼霜":"Eye cream","眼部":"Eye care","焕肤":"Exfoliant","祛痘":"Acne treatment","精华油":"Face oil",
 "返回上一题":"Back to previous question","返回首页":"Back to home","上一步":"Back","第一步 · 了解肤质":"Step 1 · Understand your skin type","第二步 · 基础信息":"Step 2 · Basic information","第三步 · 就医识别":"Step 3 · Safety screening","肤质":"Skin type","基础信息":"Basic info","安全提醒":"Safety check","状态分析":"Skin analysis","通常约3分钟完成":"Usually about 3 minutes","2个问题，帮助后续建议更贴近你的真实状态":"Two quick questions help tailor the analysis to your actual skin state.",
 "洗完脸不涂任何东西,1小时后T区和两颊分别是什么状态?":"One hour after cleansing, without applying anything, how do your T-zone and cheeks feel?","T区出油,两颊偏干或正常":"My T-zone gets oily, while my cheeks feel dry or normal","混合性":"Combination","整脸都出油":"My whole face gets oily","油性":"Oily","整脸紧绷、有点起皮":"My whole face feels tight or slightly flaky","干性":"Dry","比较舒适,没什么明显感觉":"Comfortable, with no obvious oiliness or tightness","中性":"Balanced",
 "换新产品时,皮肤容易泛红刺痛,还是基本没什么反应?":"When trying a new product, does your skin easily become red or sting, or does it usually tolerate it well?","比较容易有反应":"It reacts fairly easily","敏感叠加":"Sensitivity-prone","基本没什么反应":"It usually tolerates new products well","非敏感":"Relatively resilient",
 "你的年龄段是?":"What is your age range?","年龄会影响诊断权重——同样症状在不同年龄段更可能对应的病因不一样":"Age changes how different causes are weighted for the same visible skin concern.","18岁以下":"Under 18","18-30岁":"18–30","30-45岁":"30–45","45岁以上":"45+","性别":"Sex","用于判断部分周期性/激素相关问题是否适用,以及用药建议的安全边界":"Used only where cycle- or hormone-related factors and safety boundaries are relevant.","女":"Female","男":"Male","目前有没有怀孕或哺乳?":"Are you currently pregnant or breastfeeding?","这一步是用药建议前的安全检查,不影响病因诊断本身":"This is a safety check for treatment guidance and does not change the skin-type result itself.","是,目前怀孕或哺乳期":"Yes, currently pregnant or breastfeeding","没有":"No",
 "在选具体问题之前,先排除这几种情况":"Before choosing a specific concern, rule out these situations first","这几种不属于护肤品能处理的范畴,这一步只做一次——命中任意一项会直接建议就医,不会进入后面的症状选择":"These situations are outside the scope of skincare. This screening is shown once; selecting any of them will recommend medical evaluation instead of continuing to concern selection.",
 "边界清楚的红斑,上面覆盖较厚的银白色鳞屑,撕掉鳞屑容易点状出血":"Well-defined red patches covered with thick silvery-white scale that may show pinpoint bleeding when the scale is removed","有边界清楚的色素完全脱失斑(不是变浅,是完全变白)":"Well-defined areas with complete loss of pigment (fully white, not just lighter)","成簇的小水疱,伴刺痛或灼烧感":"Clusters of small blisters with stinging, pain, or burning","风团样红斑,通常24小时内自行消退,但此起彼伏反复出现":"Raised hive-like patches that usually fade within 24 hours but repeatedly appear in new areas","长期日晒部位(面部/手背)出现粗糙鳞屑性斑块,摸起来像砂纸":"Rough, scaly patches on chronically sun-exposed areas (face or backs of hands) that feel like sandpaper","都没有以上情况":"None of the above",
 "溶剂":"Solvent","保湿":"Moisturizing","防腐增效":"Preservative booster"
};

const DIAGNOSTIC_ZH_TO_EN:Record<string,string>={
 "急性起病":"Acute onset","慢性反复病程":"Chronic recurrent course","近期换新产品":"Recent product change","近期高频去角质":"Recent frequent exfoliation","环境变化诱发":"Triggered by environmental change","无明确外部诱因":"No clear external trigger","伴随刺痛/紧绷":"Stinging or tightness present","视觉泛红但无明显不适":"Visible redness without obvious discomfort","典型潮红触发模式":"Typical flushing trigger pattern","油腻鳞屑及典型部位":"Greasy scale in typical areas","急性突发":"Acute breakout","作息/饮食/压力变化":"Sleep, diet or stress changes","生理周期相关":"Cycle-related pattern","胸背/发际线分布":"Chest, back or hairline distribution","皮损大小高度均匀":"Highly uniform lesion size","瘙痒明显":"Prominent itching","常规祛痘处理无效":"No response to standard acne care","粉刺型表现":"Comedonal pattern","炎症性表现":"Inflammatory lesions","深层皮损":"Deep lesions","浅表皮损":"Superficial lesions","你选择了干燥/缺水相关表现":"You reported dryness or dehydration","你选择了毛孔相关表现":"You reported pore-related concerns","你选择了色沉相关表现":"You reported pigmentation concerns","你选择了细纹或抗老相关表现":"You reported fine lines or anti-aging concerns","一个月以上反复":"Recurrent for more than one month","没有明显潮红触发":"No clear flushing trigger","没有油腻鳞屑":"No greasy scaling",
 "热、酒精或情绪诱发且消退缓慢；继续刺激可能使泛红加重":"Triggered by heat, alcohol or emotion with slow fading; continued irritation may worsen redness","近期去角质叠加屏障不适；继续使用刺激性活性成分可能加重损伤":"Recent exfoliation plus barrier discomfort; continued use of irritating actives may worsen barrier damage","已报告近期去角质；继续去角质可能加重刺激和屏障损伤":"Recent exfoliation reported; further exfoliation may worsen irritation and barrier damage","已报告深层皮下病灶；结节或囊肿风险不能仅依靠护肤品处理":"Deep subcutaneous lesions reported; nodules or cysts cannot be managed with skincare alone","已报告常规祛痘或抗生素处理无效/加重；应避免继续盲目叠加活性成分":"Standard acne care or antibiotics were ineffective or worsened symptoms; avoid blindly layering more actives","已报告多年持续改变；护肤只能辅助管理，不能替代对可疑皮损的专业评估":"Long-term changes reported; skincare can support management but cannot replace professional assessment of suspicious lesions"
};

const EN_TO_ZH:Record<string,string>={"Back":"返回","Cleanser":"洁面","Toner / Essence":"化妆水 / 精华水","Serum":"精华","Treatment":"特殊护理","Moisturizer Cream":"乳液 / 面霜","Sunscreen":"防晒","Mask / Special":"面膜 / 特殊护理","My Routine":"我的 Routine","Barrier":"屏障修护","Singapore · Humid":"新加坡 · 湿热","Makeup remover":"卸妆","Exfoliant":"焕肤","Eye care":"眼部护理","Eye cream":"眼霜","Acne treatment":"祛痘护理","Essence":"精华水","Face oil":"精华油","Mask":"面膜","Moisturizer":"面霜","Lotion / moisturizer":"乳液 / 面霜","Toner / essence":"化妆水 / 精华水"};
const BILINGUAL_ZH:Record<string,string>={"我的护肤柜 · My Shelf":"我的护肤柜","用我的护肤柜搭配 · Use My Shelf":"用我的护肤柜搭配","我需要买吗？ · Do I need this?":"我需要买吗？","发现数据有误？ · Report":"发现数据有误？","发现数据有误？ · Report an error":"发现数据有误？","问题类型 · Issue type":"问题类型","哪里不对？· What looks wrong?":"哪里不对？","提交纠错 · Send report":"提交纠错","成分缺失 · Missing ingredient":"成分缺失","成分顺序错误 · Wrong order":"成分顺序错误","成分名称错误 · Wrong ingredient name":"成分名称错误","配方已更新 · Formula changed":"配方已更新","版本/地区不对 · Wrong version / market":"版本/地区不对","来源有问题 · Source issue":"来源有问题","其他 · Other":"其他"};
function lang(){return document.documentElement.lang.toLowerCase().startsWith("en")?"en":"zh"}
function translateExact(value:string,language:"zh"|"en"){const trimmed=value.trim();if(language==="en")return ZH_TO_EN[trimmed]||DIAGNOSTIC_ZH_TO_EN[trimmed]||trimmed;return BILINGUAL_ZH[trimmed]||EN_TO_ZH[trimmed]||trimmed}
function translateDiagnosticFragments(value:string){let next=value;for(const[zh,en]of Object.entries(DIAGNOSTIC_ZH_TO_EN))if(next.includes(zh))next=next.split(zh).join(en);return next}
function translateCompound(value:string,language:"zh"|"en"){const exact=translateExact(value,language);if(exact!==value.trim())return exact;const verdicts:Array<[string,string]>=[["暂不建议买","Not recommended"],["有明确补位价值","Good addition"],["大概率重复","Mostly duplicate"],["可有可无","Optional"],["有补位价值","Good addition"]];for(const[zh,en]of verdicts)if(value.trim()===`${zh} · ${en}`)return language==="en"?en:zh;const stage=value.trim().match(/^本阶段问题\s+(\d+)\/(\d+)$/);if(stage)return language==="en"?`Question ${stage[1]} of ${stage[2]}`:value;if(language==="en")return translateDiagnosticFragments(value);return value}
function processElement(el:Element,language:"zh"|"en"){if(el instanceof HTMLScriptElement||el instanceof HTMLStyleElement)return;for(const node of Array.from(el.childNodes))if(node.nodeType===Node.TEXT_NODE&&node.textContent){const old=node.textContent,lead=old.match(/^\s*/)?.[0]||"",trail=old.match(/\s*$/)?.[0]||"",core=old.trim();if(!core)continue;const next=translateCompound(core,language);if(next!==core)node.textContent=lead+next+trail}if(el instanceof HTMLInputElement||el instanceof HTMLTextAreaElement){if(el.placeholder){const next=translateExact(el.placeholder,language);if(next!==el.placeholder)el.placeholder=next}if(el instanceof HTMLInputElement&&el.value){const next=translateExact(el.value,language);if(next!==el.value)el.value=next}}if(el instanceof HTMLOptionElement){const next=translateExact(el.textContent||"",language);if(next!==(el.textContent||""))el.textContent=next}}
function processTree(root:Element,language:"zh"|"en"){processElement(root,language);for(const el of Array.from(root.querySelectorAll("*")))processElement(el,language)}function sweep(){const language=lang();processTree(document.body,language)}
export default function LanguageConsistencyGuard():React.ReactElement|null{useEffect(()=>{let frame=0;const queueFull=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(sweep)};queueFull();const observer=new MutationObserver(mutations=>{const language=lang();let needsFull=false;const added:Element[]=[];for(const m of mutations){if(m.type==="attributes"){needsFull=true;break}for(const node of Array.from(m.addedNodes))if(node instanceof Element)added.push(node);if(m.type==="characterData"&&m.target.parentElement)added.push(m.target.parentElement)}if(needsFull){queueFull();return}if(!added.length)return;cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{for(const el of added)processTree(el,language)})});observer.observe(document.documentElement,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:["lang"]});return()=>{cancelAnimationFrame(frame);observer.disconnect()}},[]);return null}
