import React,{useEffect,useMemo,useState}from"react";
import{AlertTriangle,ShieldCheck}from"lucide-react";
import{loadMySkinProfiles}from"../lib/mySkin";
import{loadSharedProductCatalog,supabase,type SharedProductRecord}from"../lib/supabase";
import{assessPregnancySafety,isPregnancySafetyMode,type PregnancySafetyAssessment}from"../lib/pregnancySafety";
import type{SkinProfileRecord}from"../lib/skinProfile";
import{useLanguage}from"../lib/i18n";

function norm(v:string){return(v||"").toLowerCase().replace(/[^a-z0-9\u3400-\u9fff]+/g,"").trim()}
function pageKind(){const page=document.querySelector<HTMLElement>(".site-content");const cls=page?.className||"";return cls.includes("page-product")?"product":cls.includes("page-routine")?"routine":"other"}
function findProduct(products:SharedProductRecord[]){const page=document.querySelector<HTMLElement>(".site-content");if(!page)return null;const h1=norm(page.querySelector("h1")?.textContent||"");if(!h1)return null;return products.find(p=>[p.productLocalName,p.productEnglishName,p.name].filter(Boolean).some(name=>norm(name||"")===h1))||products.find(p=>norm(`${p.brand}${p.name}${p.productLocalName||""}${p.productEnglishName||""}`).includes(h1))||null}
function routineProducts(products:SharedProductRecord[]){const page=document.querySelector<HTMLElement>(".site-content.page-routine")||document.querySelector<HTMLElement>(".page-routine");if(!page)return[];const text=norm(page.textContent||"");return products.filter(p=>{const names=[p.productLocalName,p.productEnglishName,p.name].filter(Boolean).map(x=>norm(x||"")).filter(x=>x.length>=5);return names.some(name=>text.includes(name))}).slice(0,24)}

export default function PregnancySafetyLayer(){
 const{language,t}=useLanguage();
 const[profile,setProfile]=useState<SkinProfileRecord|null>(null),[products,setProducts]=useState<SharedProductRecord[]>([]),[kind,setKind]=useState<"product"|"routine"|"other">("other"),[current,setCurrent]=useState<SharedProductRecord|null>(null),[routine,setRoutine]=useState<SharedProductRecord[]>([]),[open,setOpen]=useState(true);
 useEffect(()=>{let active=true;const reloadProfile=()=>loadMySkinProfiles().then(rows=>{if(active)setProfile(rows.find(x=>x.isActive)||rows[0]||null)}).catch(()=>{});reloadProfile();loadSharedProductCatalog().then(rows=>{if(active)setProducts(rows)}).catch(()=>{});const{data}=supabase.auth.onAuthStateChange(()=>setTimeout(reloadProfile,0));return()=>{active=false;data.subscription.unsubscribe()}},[]);
 useEffect(()=>{let timer:number|undefined;const scan=()=>{window.clearTimeout(timer);timer=window.setTimeout(()=>{const k=pageKind();setKind(k);if(k==="product"){setCurrent(findProduct(products));setRoutine([])}else if(k==="routine"){setCurrent(null);setRoutine(routineProducts(products))}else{setCurrent(null);setRoutine([])}setOpen(true)},80)};scan();const obs=new MutationObserver(scan);obs.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:["class"]});return()=>{window.clearTimeout(timer);obs.disconnect()}},[products]);
 const active=isPregnancySafetyMode(profile);
 const assessment=useMemo(()=>current?assessPregnancySafety(current):null,[current]);
 const routineAssessments=useMemo(()=>routine.map(product=>({product,assessment:assessPregnancySafety(product)})),[routine]);
 const routineRisk=routineAssessments.filter(x=>x.assessment.level==="avoid"||x.assessment.level==="caution"||x.assessment.level==="insufficient-data");
 if(!active||!open||kind==="other")return null;
 if(kind==="product"&&!assessment)return null;
 const highest:PregnancySafetyAssessment|null=kind==="product"?assessment:routineRisk.find(x=>x.assessment.level==="avoid")?.assessment||routineRisk.find(x=>x.assessment.level==="caution")?.assessment||routineRisk.find(x=>x.assessment.level==="insufficient-data")?.assessment||null;
 const tone=highest?.level==="avoid"?{bg:"#F8E8E4",border:"#C98B82",ink:"#784B45"}:highest?.level==="caution"||highest?.level==="insufficient-data"?{bg:"#FAF1DE",border:"#D4B56B",ink:"#6C5727"}:{bg:"#EAF1EA",border:"#91A58F",ink:"#405B43"};
 const Icon=highest?.level==="no-known-trigger"?ShieldCheck:AlertTriangle;
 return <aside role="status" aria-live="polite" style={{position:"fixed",right:14,top:"calc(env(safe-area-inset-top, 0px) + 76px)",zIndex:155,width:"min(390px,calc(100vw - 28px))",boxSizing:"border-box",border:`1px solid ${tone.border}`,borderRadius:18,padding:14,background:tone.bg,color:tone.ink,boxShadow:"0 12px 34px rgba(42,46,40,.16)"}}>
  <button onClick={()=>setOpen(false)} aria-label={t("关闭孕期提示","Close pregnancy notice")} style={{position:"absolute",right:9,top:8,border:0,background:"transparent",color:tone.ink,fontSize:18,cursor:"pointer"}}>×</button>
  <div style={{display:"flex",gap:9,alignItems:"flex-start",paddingRight:22}}><Icon size={17} style={{flexShrink:0,marginTop:2}}/><div style={{minWidth:0}}><div style={{fontSize:10,fontWeight:800,letterSpacing:".09em",marginBottom:4}}>{t("孕期 / 哺乳期安全模式","PREGNANCY / BREASTFEEDING SAFETY")}</div>{kind==="product"&&assessment?<><div style={{fontSize:15,fontWeight:800,marginBottom:5}}>{language==="zh"?assessment.labelZh:assessment.labelEn}</div><div style={{fontSize:12,lineHeight:1.55}}>{language==="zh"?assessment.summaryZh:assessment.summaryEn}</div>{assessment.triggers.length>0&&<div style={{marginTop:8,paddingTop:8,borderTop:`1px solid ${tone.border}`}}>{assessment.triggers.slice(0,4).map((x,i)=><div key={`${x.family}-${i}`} style={{fontSize:11,lineHeight:1.5,marginTop:i?5:0}}><b>{x.ingredient}</b> · {language==="zh"?x.reasonZh:x.reasonEn}</div>)}</div>}<div style={{fontSize:10.5,lineHeight:1.5,opacity:.78,marginTop:8}}>{language==="zh"?assessment.dataNoteZh:assessment.dataNoteEn}</div></>:<><div style={{fontSize:15,fontWeight:800,marginBottom:5}}>{routineRisk.length?t("这套 Routine 有孕期需要留意的项目","This routine has pregnancy-related cautions"):t("当前可识别步骤未发现明确孕期触发项","No known pregnancy trigger found in recognized steps")}</div>{routineRisk.slice(0,5).map(({product,assessment})=><div key={product.id} style={{fontSize:11.5,lineHeight:1.5,marginTop:5}}><b>{product.brand} · {product.productLocalName||product.productEnglishName||product.name}</b><br/>{language==="zh"?assessment.labelZh:assessment.labelEn}</div>)}<div style={{fontSize:10.5,lineHeight:1.5,opacity:.78,marginTop:8}}>{t("仅检查页面上能识别并且数据库已有成分表的产品；未识别产品不会被自动判为安全。","Only recognized products with ingredient data are checked. Unrecognized products are never assumed safe.")}</div></>}</div></div>
 </aside>
}
