import React,{useMemo,useRef,useState}from"react";
import html2canvas from"html2canvas";
import jsPDF from"jspdf";
import{ChevronRight,Download,ShieldCheck}from"lucide-react";
import type{SkinProfileRecord}from"../lib/skinProfile";
import{summarizeSkinProfile}from"../lib/skinProfile";
import type{SharedProductRecord}from"../lib/supabase";
import{personalizedScore,suitabilityFor,type BrowseConcern}from"../lib/productPresentation";
import{buildProfileDecisionModel,type DecisionConcern}from"../intelligence/profileDecisionModel";
import{rankProductsForProfile}from"../intelligence/profileProductRanking";
import{localizeSkinSummary,useLanguage}from"../lib/i18n";
import BilingualProductName from"./BilingualProductName";

const INK="#252724",CARD="#FCFBF8",LINE="#D8D6CE",SAGE="#536D5D",MUTE="#777870",SOFT="#F1F2E9",WARM="#F8F3E8",PREG="#FFF6E4";
const sans="-apple-system,BlinkMacSystemFont,'Segoe UI','PingFang SC','Microsoft YaHei',sans-serif";
const CONCERN_TO_BROWSE:Record<DecisionConcern,BrowseConcern>={redness:"redness",acne:"acne",pores:"pores",pigmentation:"pigmentation",aging:"aging",dryness:"hydration"};
const CONCERN_ZH:Record<DecisionConcern,string>={redness:"泛红",acne:"痘痘",pores:"毛孔",pigmentation:"色沉",aging:"细纹 / 抗老",dryness:"干燥 / 缺水"};
const CONCERN_EN:Record<DecisionConcern,string>={redness:"Redness",acne:"Acne",pores:"Pores",pigmentation:"Pigmentation",aging:"Aging",dryness:"Dryness"};
const ING_ZH:Record<string,string>={Glycerin:"甘油","Hyaluronic Acid":"透明质酸","Sodium Hyaluronate":"透明质酸钠",Panthenol:"泛醇",Betaine:"甜菜碱",Urea:"尿素",Ceramide:"神经酰胺",Cholesterol:"胆固醇",Phytosphingosine:"植物鞘氨醇",Squalane:"角鲨烷",Niacinamide:"烟酰胺","Centella Asiatica":"积雪草",Madecassoside:"羟基积雪草苷",Allantoin:"尿囊素",Bisabolol:"红没药醇","Beta-Glucan":"β-葡聚糖","Salicylic Acid":"水杨酸","Azelaic Acid":"壬二酸","Zinc PCA":"PCA 锌",Sulfur:"硫磺","Tranexamic Acid":"传明酸","Ascorbic Acid":"维生素C","Alpha-Arbutin":"α-熊果苷",Licorice:"甘草提取物",Retinol:"视黄醇 / A醇",Retinal:"视黄醛",Peptide:"肽类",Adenosine:"腺苷","Alcohol Denat.":"变性乙醇",Fragrance:"香精",Parfum:"香精",Menthol:"薄荷醇","Coconut Oil":"椰子油","Isopropyl Myristate":"肉豆蔻酸异丙酯","Glycolic Acid":"乙醇酸 / 果酸","Lactic Acid":"乳酸"};
function ing(name:string,lang:"zh"|"en"){return lang==="zh"?(ING_ZH[name]||name):name}
function uniq<T>(items:T[]){return Array.from(new Set(items))}
function confidenceText(value:string,lang:"zh"|"en"){if(lang==="en")return value.toUpperCase();return value==="high"?"高":value==="medium"?"中":"低"}
function concernLabel(value:DecisionConcern,lang:"zh"|"en"){return lang==="zh"?CONCERN_ZH[value]:CONCERN_EN[value]}
function aggregateEvidence(product:SharedProductRecord,profile:SkinProfileRecord,concerns:DecisionConcern[]){const results=concerns.map(c=>personalizedScore(product,profile,CONCERN_TO_BROWSE[c])).filter((x):x is NonNullable<typeof x>=>!!x&&x.recommendationAvailable&&x.score!=null);const pos=Array.from(new Map(results.flatMap(x=>x.positiveEvidence).map(x=>[x.name,x])).values());const neg=Array.from(new Map(results.flatMap(x=>x.negativeEvidence).map(x=>[x.name,x])).values());const systems=Array.from(new Map(results.flatMap(x=>x.systemEvidence).map(x=>[x.key,x])).values());return{pos,neg,systems}}
function mergedIngredientDirection(profile:SkinProfileRecord,concerns:DecisionConcern[]){const parts=concerns.map(c=>suitabilityFor(profile,CONCERN_TO_BROWSE[c]));const good=Array.from(new Set(parts.flatMap(x=>x.good.map(i=>i.name))));const risky=Array.from(new Set(parts.flatMap(x=>x.risky.map(i=>i.name))));return{good,risky}}
export default function SkinAnalysisReportV2({profile,products,onProduct}:{profile:SkinProfileRecord;products:SharedProductRecord[];onProduct:(p:SharedProductRecord,c:BrowseConcern)=>void}){
 const{t,language}=useLanguage();const ref=useRef<HTMLDivElement>(null);const[busy,setBusy]=useState(false);const summary=localizeSkinSummary(summarizeSkinProfile(profile),language);const model=buildProfileDecisionModel(profile);const concerns=model.concernWeights.map(x=>x.concern);const direction=mergedIngredientDirection(profile,concerns);const ranked=useMemo(()=>rankProductsForProfile(products,profile).slice(0,5),[products,profile]);const highFindings=model.diagnosticFindings.slice(0,5);const primaryIngredients=direction.good.slice(0,4),supportIngredients=direction.good.slice(4,9),riskIngredients=uniq([...direction.risky,...(model.pregnancySafetyOverride?["Retinol","Retinal"]:[])]).slice(0,10);
 async function download(){if(!ref.current||busy)return;setBusy(true);try{const canvas=await html2canvas(ref.current,{scale:2,useCORS:true,backgroundColor:CARD});const pdf=new jsPDF("p","mm","a4");const pw=210,ph=297,m=10,w=pw-m*2,h=canvas.height*w/canvas.width,img=canvas.toDataURL("image/png");let y=m;pdf.addImage(img,"PNG",m,y,w,h);let remaining=h-(ph-m*2);while(remaining>0){pdf.addPage();y=m-(h-remaining);pdf.addImage(img,"PNG",m,y,w,h);remaining-=ph-m*2}pdf.save(language==="zh"?"我的肤质分析报告.pdf":"My-Skin-Analysis-Report.pdf")}finally{setBusy(false)}}
 return <><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10,margin:"26px 0 10px"}}><div><div style={{fontSize:10.5,letterSpacing:".14em",color:SAGE,fontWeight:800}}>{t("个性化分析报告","PERSONALIZED ANALYSIS")}</div><div style={{fontSize:20,fontWeight:760,marginTop:4}}>{t("我的肤质分析报告","My Skin Analysis Report")}</div></div><button onClick={()=>void download()} disabled={busy} style={{border:`1px solid ${LINE}`,borderRadius:10,padding:"9px 12px",background:CARD,color:SAGE,fontSize:11.5,fontWeight:700,display:"flex",alignItems:"center",gap:6,cursor:"pointer"}}><Download size={14}/>{busy?t("生成中…","Preparing…"):t("下载 PDF","Download PDF")}</button></div><div ref={ref} style={{border:`1px solid ${LINE}`,borderRadius:12,padding:20,background:CARD,fontFamily:sans,color:INK}}>
 <header style={{borderBottom:`2px solid ${SAGE}`,paddingBottom:15,marginBottom:15}}><div style={{fontSize:10,color:SAGE,fontWeight:800,letterSpacing:".16em"}}>SKINCARE101 · EVIDENCE-BASED PROFILE</div><h2 style={{fontSize:25,margin:"6px 0 5px"}}>{t("肤质与产品匹配分析","Skin & Product Match Analysis")}</h2><div style={{fontSize:11,color:MUTE}}>{profile.name}</div></header>
 <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:13}}><Metric label={t("肤质类型","Skin type")} value={summary.skinType}/><Metric label={t("敏感程度","Sensitivity")} value={summary.sensitivity}/></div>
 {model.pregnancySafetyOverride&&<div style={{border:"1px solid #C8AD7A",background:PREG,padding:12,display:"flex",gap:9,marginBottom:14}}><ShieldCheck size={18} color="#8A6536"/><div><b style={{fontSize:12,color:"#805F33"}}>{t("孕期 / 哺乳期安全规则优先","Pregnancy / breastfeeding safety override")}</b><div style={{fontSize:11.2,color:"#665846",lineHeight:1.6,marginTop:3}}>{t("安全过滤优先于功效评分。维A类候选产品直接排除，不进入 Top 5；报告不会把“扣几分”当作安全处理。","Safety filtering precedes efficacy scoring. Retinoid candidates are excluded from the Top 5 rather than merely receiving a small penalty.")}</div></div></div>}
 <Section no="01" title={t("你的皮肤表现","Reported skin concerns")}><div style={{display:"flex",flexWrap:"wrap",gap:6}}>{concerns.map((c,i)=><span key={c} style={{border:`1px solid ${i===0?SAGE:LINE}`,background:i===0?SOFT:"white",padding:"6px 8px",fontSize:11.5,fontWeight:700,color:i===0?SAGE:INK}}>{concernLabel(c,language)} · {Math.round(model.concernWeights[i].weight*100)}%</span>)}</div><p style={{fontSize:11.5,color:MUTE,lineHeight:1.65,margin:"9px 0 0"}}>{t("权重用于多目标排序，不代表医学严重程度。所有你选择的关注项都会进入产品综合评分。","Weights are used for multi-objective ranking and do not represent medical severity. Every selected concern contributes to product scoring.")}</p></Section>
 <Section no="02" title={t("可能机制与鉴别方向","Possible mechanisms & differential")}><p style={{fontSize:11.5,color:MUTE,lineHeight:1.65,margin:"0 0 7px"}}>{t("症状不等于原因。以下结果来自问卷实际走过的 decision-tree 分支，只表达倾向和需要鉴别的方向，不构成医学确诊。","A symptom is not the same as a cause. These results come from the decision-tree branches you actually answered and indicate tendencies for differential consideration, not a medical diagnosis.")}</p>{highFindings.length?highFindings.map((f,i)=><div key={`${f.key}-${i}`} style={{padding:"10px 0",borderTop:i?`1px solid ${LINE}`:"none"}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><b style={{fontSize:13.5}}>{language==="zh"?f.labelZh:f.labelEn}</b><b style={{fontSize:11,color:f.level==="high"?"#9A693E":SAGE}}>{f.score}%</b></div>{f.supporting.length>0&&<div style={{fontSize:11.3,color:"#586057",lineHeight:1.58,marginTop:4}}>{t("支持证据：","Supporting evidence: ")}{f.supporting.slice(0,3).join(t("；","; "))}</div>}{f.contradicting.length>0&&<div style={{fontSize:10.8,color:MUTE,lineHeight:1.55,marginTop:3}}>{t("削弱证据：","Contradicting evidence: ")}{f.contradicting.slice(0,2).join(t("；","; "))}</div>}</div>):<div style={{fontSize:11.5,color:MUTE}}>{t("当前回答不足以形成需要突出显示的鉴别方向。","Current answers do not support a differential finding strong enough to highlight.")}</div>}</Section>
 <Section no="03" title={t("成分与配方策略","Ingredient & formula strategy")}><IngredientGroup title={t("优先方向","PRIMARY DIRECTIONS")} items={primaryIngredients} lang={language} body={t("优先选择能同时覆盖多个关注问题、且与你当前耐受状态兼容的成分与配方体系。","Prioritize ingredients and formula systems that address multiple concerns while fitting your current tolerance.")}/><IngredientGroup title={t("辅助 / 维稳","SUPPORT & STABILITY")} items={supportIngredients} lang={language} body={t("作为保湿、舒缓或屏障支持的底座，不需要为了凑齐成分而叠加很多产品。","Use these as hydration, soothing or barrier-support foundations; do not stack products just to collect ingredients.")}/><IngredientGroup title={t("谨慎 / 回避信号","CAUTION / AVOIDANCE")} items={riskIngredients} lang={language} muted body={model.pregnancySafetyOverride?t("孕期安全规则优先；同时仍需结合浓度、配方位置、使用面积与医生建议判断其他活性成分。","Pregnancy safety rules take priority; other actives still require context on concentration, formula position, application area and clinician guidance."):t("这里是需要结合浓度、位置、频率与耐受判断的风险信号，不等同于所有情况下绝对禁用。","These are context-dependent caution signals rather than universal bans.")}/></Section>
 <Section no="04" title={t("Top 5 产品匹配与证据","Top 5 product matches & evidence")}><p style={{fontSize:11.2,color:MUTE,lineHeight:1.6,margin:"0 0 9px"}}>{t("综合分 = 70% 多 concern 匹配 + 15% 肤质适配 + 10% 敏感/耐受 + 5% 数据质量；安全 override 在评分前执行。","Composite score = 70% multi-concern fit + 15% skin-type fit + 10% sensitivity/tolerance + 5% data quality; safety overrides run before scoring.")}</p><div style={{display:"grid",gap:9}}>{ranked.map((match,index)=>{const evidence=aggregateEvidence(match.product,profile,concerns);return <button key={match.product.id} onClick={()=>onProduct(match.product,CONCERN_TO_BROWSE[concerns[0]||"redness"])} style={{border:`1px solid ${LINE}`,background:"white",padding:13,textAlign:"left",cursor:"pointer",fontFamily:sans,color:INK}}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"flex-start"}}><div style={{minWidth:0,flex:1}}><div style={{display:"flex",gap:7,flexWrap:"wrap",alignItems:"center",marginBottom:5}}><b style={{fontSize:10.5,color:SAGE}}>#{index+1}</b><b style={{fontSize:10.5,color:SAGE}}>{t("综合匹配","MATCH")} {match.score}%</b><span style={{fontSize:10,color:MUTE}}>{t("置信度","Confidence")} {confidenceText(match.confidence,language)}</span><span style={{fontSize:10,color:MUTE}}>{t("有效证据","Evidence")} {match.evidenceCount}</span></div><BilingualProductName product={match.product} compact/><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:4,marginTop:8}}><Mini label={t("多目标","Concerns")} value={`${match.concernScore}`}/><Mini label={t("肤质","Skin")} value={`${match.skinTypeScore}`}/><Mini label={t("耐受","Tolerance")} value={`${match.sensitivityScore}`}/><Mini label={t("数据","Data")} value={`${match.dataQualityScore}`}/></div><div style={{fontSize:10.8,color:"#596158",lineHeight:1.55,marginTop:7}}><b>{t("覆盖：","Coverage: ")}</b>{concerns.map(c=>`${concernLabel(c,language)} ${match.coveredConcerns.includes(c)?"✓":"—"}`).join(" · ")}</div>{evidence.pos.length>0&&<div style={{fontSize:10.8,color:"#596158",lineHeight:1.55,marginTop:4}}><b>{t("加分证据：","Positive evidence: ")}</b>{evidence.pos.slice(0,4).map(x=>`${ing(x.name,language)} #${x.ingredientPosition}`).join(" · ")}</div>}{evidence.systems.length>0&&<div style={{fontSize:10.8,color:MUTE,lineHeight:1.55,marginTop:3}}><b>{t("配方体系：","Formula systems: ")}</b>{evidence.systems.slice(0,3).map(x=>x.label).join(" · ")}</div>}{evidence.neg.length>0&&<div style={{fontSize:10.8,color:"#8A5A42",lineHeight:1.55,marginTop:3}}><b>{t("注意：","Caution: ")}</b>{evidence.neg.slice(0,3).map(x=>`${ing(x.name,language)} #${x.ingredientPosition}`).join(" · ")}</div>}</div><ChevronRight size={15} color={MUTE}/></div></button>})}</div></Section>
 <Section no="05" title={t("为什么不是黑箱推荐","Why this is not a black box")}><div style={{fontSize:11.5,color:"#555852",lineHeight:1.7}}>{t("每个结果保留三个层级：问卷分支产生的诊断/画像证据；画像转换后的成分与配方规则；产品数据库中的 INCI、配方体系、成分位置、数据完整度与置信度。没有足够证据的产品不会靠默认中性分伪装成推荐。","Each result preserves three layers: diagnostic/profile evidence from questionnaire branches; ingredient and formula rules derived from that profile; and database evidence including INCI, formula systems, ingredient positions, completeness and confidence. Products without sufficient evidence are not disguised as recommendations with a neutral default score.")}</div></Section>
 <footer style={{borderTop:`1px solid ${LINE}`,paddingTop:11,fontSize:9.8,color:MUTE,lineHeight:1.55}}>{t("本报告用于护肤决策支持，不替代皮肤科诊断。出现持续加重、疼痛、渗出、明显脱屑或其他异常皮损时，应寻求专业医疗评估。","This report supports skincare decisions and does not replace dermatologic diagnosis. Seek professional medical assessment for persistent worsening, pain, oozing, marked scaling, or other unusual lesions.")}</footer>
 </div></>}
function Metric({label,value}:{label:string;value:string}){return <div style={{border:`1px solid ${LINE}`,background:"white",padding:"10px 11px"}}><div style={{fontSize:10,color:MUTE,marginBottom:3}}>{label}</div><b style={{fontSize:16}}>{value}</b></div>}
function Section({no,title,children}:{no:string;title:string;children:React.ReactNode}){return <section style={{padding:"15px 0",borderTop:`1px solid ${LINE}`}}><div style={{display:"flex",gap:8,alignItems:"baseline",marginBottom:9}}><span style={{fontSize:10,color:SAGE,fontWeight:800}}>{no}</span><b style={{fontSize:13.2}}>{title}</b></div>{children}</section>}
function IngredientGroup({title,items,lang,body,muted=false}:{title:string;items:string[];lang:"zh"|"en";body:string;muted?:boolean}){if(!items.length)return null;return <div style={{padding:"9px 0",borderTop:`1px solid ${LINE}`}}><b style={{fontSize:10.5,color:muted?"#8A5A42":SAGE}}>{title}</b><div style={{display:"flex",gap:5,flexWrap:"wrap",marginTop:6}}>{items.map(x=><span key={x} style={{border:`1px solid ${muted?"#D7C2AD":SAGE}`,background:muted?WARM:SOFT,padding:"5px 7px",fontSize:10.8,color:muted?"#7C5A45":SAGE}}>{ing(x,lang)}</span>)}</div><div style={{fontSize:10.8,color:MUTE,lineHeight:1.6,marginTop:5}}>{body}</div></div>}
function Mini({label,value}:{label:string;value:string}){return <div style={{background:"#F7F7F3",padding:"5px 4px",textAlign:"center"}}><div style={{fontSize:8.8,color:MUTE}}>{label}</div><b style={{fontSize:11.2}}>{value}</b></div>}
