import React,{useEffect,useRef,useState}from"react";import{ArrowLeft,ChevronRight,LibraryBig,Sparkles}from"lucide-react";import{useLanguage}from"../lib/i18n";
const INK="#263027",CARD="#FBF6EA",LINE="#D9D0BC",SAGE="#2F5A40",MUSTARD="#D5A92E",MUTE="#6F6A5F";
type Topic="steps"|"barrier"|"oily"|"niacinamide";
const topics=[
{id:"steps" as Topic,title:["护肤步骤金字塔","The skincare pyramid"],sub:["先懂顺序，再谈效果","Order first, actives second"],tags:["护肤入门","Routine"]},
{id:"barrier" as Topic,title:["什么是屏障？为什么重要？","What is the skin barrier?"],sub:["你的皮肤保护层","Your skin's protective layer"],tags:["皮肤屏障","敏感肌"]},
{id:"niacinamide" as Topic,title:["常见成分小科普：烟酰胺","Ingredient 101: Niacinamide"],sub:["多效成分，但不是越高越好","Useful, but more is not always better"],tags:["成分科普","烟酰胺"]},
{id:"oily" as Topic,title:["油皮为什么也会缺水？","Why can oily skin feel dehydrated?"],sub:["水油不平衡才是关键","Oil and water are different"],tags:["油性肌肤","补水保湿"]}
];
const copy:Record<Topic,[string,string][]>={steps:[["护肤不是层数越多越好。最基础的是温和清洁、保湿和白天防晒。精华和针对性护理属于加分项，而不是地基。","More layers do not mean better skincare. Gentle cleansing, moisturising and daytime sunscreen are the foundation. Serums and targeted treatments are optional additions."],["如果皮肤正在泛红、刺痛或明显脱皮，先把金字塔上层拿掉，回到底层。","If skin is red, stinging or visibly peeling, remove the upper layers first and return to the basics."]],barrier:[["皮肤屏障主要位于角质层，可以把它理解成“砖墙”：角质细胞像砖，脂质像水泥。它帮助减少水分流失，也降低外界刺激物进入皮肤的机会。","The skin barrier sits mainly in the stratum corneum. Think of it as a brick wall: skin cells are the bricks and lipids are the mortar. It limits water loss and reduces entry of irritants."],["屏障状态差时，减少刺激、做好保湿，通常比继续叠加强功效产品更重要。","When the barrier is stressed, reducing irritation and moisturising usually matters more than stacking stronger actives."]],oily:[["出油多和含水量不足可以同时发生。皮脂来自皮脂腺，而皮肤含水量主要和角质层保水能力有关，所以“油”不等于“水够”。","Oiliness and dehydration can happen at the same time. Sebum comes from sebaceous glands, while hydration depends largely on the stratum corneum's ability to hold water."],["油皮保湿重点通常不是厚重，而是轻薄保湿剂加适量封闭成分，避免为了控油过度清洁。","For oily skin, moisturising often means light humectants plus enough occlusion, not necessarily a heavy cream. Avoid over-cleansing in the name of oil control."]],niacinamide:[["烟酰胺是维生素B3的一种形式，常见于提亮、屏障支持、控油和整体肤色护理。多数人并不需要追求特别高的浓度。","Niacinamide is a form of vitamin B3 used for brightening, barrier support, oil-control support and overall tone. Most people do not need extremely high concentrations."],["敏感皮肤更适合从温和浓度开始。如果一款产品本身已经包含烟酰胺，不需要为了“叠加功效”再同时用很多高浓度烟酰胺产品。","Sensitive skin is usually better served by moderate concentrations. If one product already contains niacinamide, stacking several high-strength niacinamide products is rarely necessary."]]};
const artFiles:Record<Topic,string>={
steps:"knowledge-routine.webp",
barrier:"knowledge-barrier.webp",
niacinamide:"knowledge-niacinamide.webp",
oily:"knowledge-oily-dehydrated.webp"
};
const artAlt:Record<Topic,[string,string]>={
steps:["护肤基础步骤水彩插画","Watercolor illustration of a simple skincare routine"],
barrier:["皮肤屏障砖墙水彩插画","Watercolor illustration of the skin barrier"],
niacinamide:["烟酰胺精华水彩插画","Watercolor illustration of niacinamide serum"],
oily:["油皮缺水水彩插画","Watercolor portrait illustrating oily, dehydrated skin"]
};
function Art({topic,detail=false}:{topic:Topic;detail?:boolean}){const{language}=useLanguage();const src=`${import.meta.env.BASE_URL}illustrations/${artFiles[topic]}`;return <div style={{width:"100%",aspectRatio:detail?"16/7":"16/7",overflow:"hidden",position:"relative",background:"#F7F1E5"}}><img src={src} alt={artAlt[topic][language==="zh"?0:1]} loading={detail?"eager":"lazy"} decoding="async" width={1600} height={700} style={{width:"100%",height:"100%",display:"block",objectFit:"cover",objectPosition:"center"}}/></div>}
const motionCss=`@keyframes knowledgeRise{from{opacity:0;transform:translateY(24px) scale(.985)}to{opacity:1;transform:none}}@keyframes dropletLift{0%{opacity:0;transform:translateY(10px) scale(.6)}55%{opacity:.9}100%{opacity:0;transform:translateY(-24px) scale(1)}}@keyframes serumGlow{0%,100%{opacity:.18;transform:scale(.7)}50%{opacity:.5;transform:scale(1.15)}}@keyframes petalTurn{from{opacity:0;transform:rotate(-40deg) scale(.3)}to{opacity:.75;transform:rotate(10deg) scale(1)}}.knowledge-reveal{position:relative;opacity:0}.knowledge-reveal.is-visible{animation:knowledgeRise .72s cubic-bezier(.2,.78,.25,1) forwards}.knowledge-reveal button{width:100%}.knowledge-local-motion{position:absolute;z-index:2;pointer-events:none;right:17px;top:16px;width:24px;height:24px;border:1.5px solid rgba(47,90,64,.55);border-radius:60% 40% 65% 35%;opacity:0}.knowledge-reveal.is-visible.knowledge-steps .knowledge-local-motion{animation:petalTurn .75s ease .35s forwards}.knowledge-reveal.is-visible.knowledge-barrier .knowledge-local-motion{background:rgba(139,183,194,.35);border-radius:50% 50% 55% 45%;animation:dropletLift 1.25s ease .4s}.knowledge-reveal.is-visible.knowledge-niacinamide .knowledge-local-motion{background:rgba(213,169,46,.25);border:0;border-radius:50%;animation:serumGlow 2.2s ease .35s 2}.knowledge-reveal.is-visible.knowledge-oily .knowledge-local-motion{background:rgba(139,183,194,.28);border-color:rgba(139,183,194,.6);animation:dropletLift 1.35s ease .45s}@media(prefers-reduced-motion:reduce){.knowledge-reveal{opacity:1}.knowledge-reveal.is-visible,.knowledge-reveal.is-visible .knowledge-local-motion{animation:none!important}.knowledge-local-motion{display:none}}`;
function Reveal({topic,children}:{topic:Topic;children:React.ReactNode}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const node=ref.current;if(!node)return;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){node.classList.add("is-visible");observer.disconnect()}},{threshold:.22});observer.observe(node);return()=>observer.disconnect()},[]);return <div ref={ref} className={`knowledge-reveal knowledge-${topic}`}><span className="knowledge-local-motion"/>{children}</div>}

export default function SkincareKnowledgeCards(){const{t,language}=useLanguage();const[open,setOpen]=useState<Topic|null>(null),[showAll,setShowAll]=useState(false);const zh=language==="zh";if(open){const topic=topics.find(x=>x.id===open)!;return <section style={{marginTop:30,border:`1px solid ${LINE}`,borderRadius:24,background:CARD,overflow:"hidden",boxShadow:"0 7px 22px rgba(40,55,42,.05)"}}><button onClick={()=>setOpen(null)} style={{border:0,background:"transparent",padding:"15px 16px 4px",display:"inline-flex",gap:6,alignItems:"center",color:SAGE,cursor:"pointer"}}><ArrowLeft size={15}/>{t("返回护肤知识","Back to guides")}</button><div style={{padding:"8px 16px 22px"}}><div style={{borderRadius:18,overflow:"hidden",border:`1px solid ${LINE}`,background:"#FAF5E9"}}><Art topic={topic.id} detail/></div><div style={{fontSize:11,fontWeight:600,color:SAGE,letterSpacing:".06em",marginTop:17}}>SKINCARE GUIDE</div><h2 style={{fontFamily:zh?"'Kaiti SC','STKaiti','Newsreader',serif":"'Newsreader',serif",fontSize:27,lineHeight:1.25,margin:"6px 0 7px",color:INK,fontWeight:500}}>{topic.title[zh?0:1]}</h2><p style={{fontSize:14,color:MUTE,lineHeight:1.65,margin:"0 0 16px"}}>{topic.sub[zh?0:1]}</p>{copy[open].map((p,i)=><p key={i} style={{fontSize:14.5,lineHeight:1.78,color:INK,margin:"0 0 13px"}}>{p[zh?0:1]}</p>)}<div style={{display:"flex",gap:7,flexWrap:"wrap",marginTop:15}}>{topic.tags.map(tag=><span key={tag} style={{fontSize:11,color:SAGE,background:"#EAF0E7",border:"1px solid #DDE7D8",borderRadius:999,padding:"5px 9px"}}>{tag}</span>)}</div></div></section>}
const visible=showAll?topics:topics.slice(0,2);return <section style={{marginTop:32}}><style>{motionCss}</style><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10,marginBottom:13}}><div><div style={{display:"flex",alignItems:"center",gap:7,color:SAGE,fontSize:12,fontWeight:600,letterSpacing:".055em"}}><LibraryBig size={16}/>{t("护肤知识","SKINCARE GUIDE")}<Sparkles size={13} color={MUSTARD}/></div><div style={{fontSize:13,color:MUTE,marginTop:4}}>{t("每天懂一点，皮肤好一点","Small lessons for smarter skincare")}</div></div><button onClick={()=>setShowAll(v=>!v)} style={{border:`1px solid ${LINE}`,borderRadius:999,padding:"7px 11px",background:"#FFFDF8",color:SAGE,fontSize:11,cursor:"pointer"}}>{showAll?t("收起","Less"):t("全部","All")}</button></div><div style={{display:"grid",gap:16}}>{visible.map(topic=><Reveal key={topic.id} topic={topic.id}><button onClick={()=>setOpen(topic.id)} style={{padding:0,border:`1px solid ${LINE}`,borderRadius:22,overflow:"hidden",background:"#FFFDF8",textAlign:"left",cursor:"pointer",boxShadow:"0 7px 20px rgba(43,58,46,.04)"}}><Art topic={topic.id}/><div style={{padding:"16px 18px 17px",display:"flex",alignItems:"center",justifyContent:"space-between",gap:14}}><div><div style={{fontFamily:zh?"'Kaiti SC','STKaiti','Newsreader',serif":"'Newsreader',serif",fontSize:21,fontWeight:500,color:INK,lineHeight:1.3}}>{topic.title[zh?0:1]}</div><div style={{fontSize:13,color:MUTE,marginTop:5}}>{topic.sub[zh?0:1]}</div><div style={{display:"flex",gap:7,marginTop:12,flexWrap:"wrap"}}>{topic.tags.map(tag=><span key={tag} style={{fontSize:10.5,color:SAGE,background:"#EDF2EA",borderRadius:999,padding:"4px 8px"}}>{tag}</span>)}</div></div><ChevronRight size={20} color={SAGE}/></div></button></Reveal>)}</div></section>}
