import React,{useMemo,useRef,useState}from"react";
import html2canvas from"html2canvas";
import jsPDF from"jspdf";
import{Download,ChevronRight}from"lucide-react";
import type{SkinProfileRecord}from"../lib/skinProfile";
import{summarizeSkinProfile}from"../lib/skinProfile";
import type{SharedProductRecord}from"../lib/supabase";
import{matchRating,profileConcern,rankForProfile,suitabilityFor,type BrowseConcern}from"../lib/productPresentation";
import{localizeSkinSummary,useLanguage}from"../lib/i18n";
import BilingualProductName from"./BilingualProductName";

const INK="#252724",CARD="#FCFBF8",LINE="#DEDCD5",SAGE="#667A6C",MUTE="#777870",SOFT="#F1F2E9";
const sans="-apple-system,BlinkMacSystemFont,'Segoe UI','PingFang SC','Microsoft YaHei',sans-serif";
const INGREDIENT_ZH:Record<string,string>={"Glycerin":"甘油","Hyaluronic Acid":"透明质酸","Sodium Hyaluronate":"透明质酸钠","Panthenol":"泛醇","Betaine":"甜菜碱","Urea":"尿素","Ceramide":"神经酰胺","Cholesterol":"胆固醇","Phytosphingosine":"植物鞘氨醇","Squalane":"角鲨烷","Niacinamide":"烟酰胺","Centella Asiatica":"积雪草","Madecassoside":"羟基积雪草苷","Allantoin":"尿囊素","Bisabolol":"红没药醇","Beta-Glucan":"β-葡聚糖","Salicylic Acid":"水杨酸","Azelaic Acid":"壬二酸","Zinc PCA":"PCA 锌","Sulfur":"硫磺","Tranexamic Acid":"传明酸","Ascorbic Acid":"维生素C","Alpha-Arbutin":"α-熊果苷","Licorice":"甘草提取物","Retinol":"视黄醇 / A醇","Retinal":"视黄醛","Peptide":"肽类","Adenosine":"腺苷","Alcohol Denat.":"变性乙醇","Fragrance":"香精","Parfum":"香精","Menthol":"薄荷醇","Coconut Oil":"椰子油","Isopropyl Myristate":"肉豆蔻酸异丙酯","Glycolic Acid":"乙醇酸 / 果酸","Lactic Acid":"乳酸"};
function ing(name:string,language:"zh"|"en"){return language==="zh"?(INGREDIENT_ZH[name]||name):name}
function uniq(xs:string[]){return Array.from(new Set(xs)).filter(Boolean)}
function whyText(item:any,language:"zh"|"en"){
 const positives=(item.positiveEvidence||[]).slice(0,2).map((x:any)=>ing(x.name,language));
 const systems=(item.systemEvidence||[]).slice(0,2).map((x:any)=>language==="zh"?x.label:({"屏障修护":"barrier support","补水保湿":"hydration","舒缓维稳":"soothing","抗老紧致":"anti-aging","控油净肤":"oil control","滋润锁水":"lipid support"}[x.label]||x.label));
 if(language==="zh")return positives.length?`命中 ${positives.join("、")}${systems.length?`，同时配方偏向${systems.join("、")}`:""}。`:`配方体系与当前需求的${systems.join("、")||"基础护理"}方向较一致。`;
 return positives.length?`Matches ${positives.join(", ")}${systems.length?` with ${systems.join(" and ")}`:""}.`:`Its formula structure aligns with your current ${systems.join(" and ")||"care"} priorities.`;
}
export default function SkinAnalysisReport({profile,products,onProduct}:{profile:SkinProfileRecord;products:SharedProductRecord[];onProduct:(p:SharedProductRecord,c:BrowseConcern)=>void}){
 const{t,language}=useLanguage();const reportRef=useRef<HTMLDivElement>(null);const[busy,setBusy]=useState(false);
 const summary=localizeSkinSummary(summarizeSkinProfile(profile),language);const concern=profileConcern(profile);const suitability=suitabilityFor(profile,concern);
 const top=useMemo(()=>rankForProfile(products,profile,concern).filter((p:any)=>p.recommendationAvailable&&p.score!=null).slice(0,5),[products,profile,concern]);
 const good=uniq(suitability.good.map(x=>x.name)).slice(0,8);const risky=uniq(suitability.risky.map(x=>x.name)).slice(0,8);const priority=summary.concerns[0]||t("屏障稳定","Barrier stability");
 async function downloadPdf(){if(!reportRef.current||busy)return;setBusy(true);try{const canvas=await html2canvas(reportRef.current,{scale:2,useCORS:true,backgroundColor:"#FCFBF8"});const pdf=new jsPDF("p","mm","a4");const pageW=210,pageH=297,margin=10,imgW=pageW-margin*2,imgH=canvas.height*imgW/canvas.width;const img=canvas.toDataURL("image/png");let y=margin;pdf.addImage(img,"PNG",margin,y,imgW,imgH);let remaining=imgH-(pageH-margin*2);while(remaining>0){pdf.addPage();y=margin-(imgH-remaining);pdf.addImage(img,"PNG",margin,y,imgW,imgH);remaining-=pageH-margin*2}pdf.save(language==="zh"?"我的肤质分析报告.pdf":"My-Skin-Analysis-Report.pdf")}finally{setBusy(false)}}
 return <><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10,margin:"26px 0 10px"}}><div><div style={{fontSize:11,letterSpacing:".1em",color:SAGE,fontWeight:700}}>{t("完整分析报告","FULL REPORT")}</div><div style={{fontSize:20,fontWeight:700,marginTop:4}}>{t("我的肤质分析报告","My Skin Analysis Report")}</div></div><button onClick={()=>void downloadPdf()} disabled={busy} style={{border:`1px solid ${LINE}`,borderRadius:999,padding:"9px 12px",background:CARD,color:SAGE,fontSize:11.5,fontWeight:700,display:"flex",alignItems:"center",gap:6,cursor:"pointer"}}><Download size={14}/>{busy?t("生成中…","Preparing…"):t("下载 PDF","Download PDF")}</button></div>
 <div ref={reportRef} style={{border:`1px solid ${LINE}`,borderRadius:20,padding:18,background:CARD,fontFamily:sans,color:INK}}>
  <div style={{borderBottom:`1px solid ${LINE}`,paddingBottom:14,marginBottom:14}}><div style={{fontSize:10.5,color:SAGE,fontWeight:700,letterSpacing:".12em"}}>SKINCARE101</div><h2 style={{fontSize:26,margin:"5px 0 8px"}}>{t("我的肤质分析报告","My Skin Analysis Report")}</h2><div style={{fontSize:12,color:MUTE}}>{profile.name}</div></div>
  <section style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginBottom:12}}><Box label={t("肤质类型","Skin type")} value={summary.skinType}/><Box label={t("敏感程度","Sensitivity")} value={summary.sensitivity}/></section>
  <Section title={t("当前最优先问题","Current priority")}><div style={{fontSize:20,fontWeight:700,color:SAGE}}>{priority}</div>{summary.concerns.length>1&&<div style={{fontSize:12,color:MUTE,marginTop:5}}>{t("同时关注：","Also watch: ")}{summary.concerns.slice(1).join(" · ")}</div>}</Section>
  <Section title={t("推荐成分方向","Recommended ingredient direction")}><div style={{display:"flex",gap:7,flexWrap:"wrap"}}>{good.map(x=><Chip key={x}>{ing(x,language)}</Chip>)}</div></Section>
  <Section title={t("暂时少用 / 谨慎的成分","Use less / be cautious with")}><div style={{display:"flex",gap:7,flexWrap:"wrap"}}>{risky.length?risky.map(x=><Chip key={x} muted>{ing(x,language)}</Chip>):<span style={{fontSize:12,color:MUTE}}>{t("当前没有特别需要回避的常见成分信号。","No major common ingredient cautions detected for your current profile.")}</span>}</div></Section>
  <Section title={t("基础护理策略","Basic care strategy")}><div style={{display:"grid",gap:8}}>{[[t("先简化","Simplify first"),t("暂停近期新增、明显刺激或与你当前方向冲突的产品。","Pause recently added, clearly irritating, or conflicting products.")],[t("保留基础","Keep the basics"),t("温和清洁、合适保湿和白天防晒先保持稳定。","Keep gentle cleansing, suitable moisturization and daytime sunscreen stable.")],[t("再做选择","Choose next"),t("新增产品优先选择与当前成分方向一致、配方数据完整的产品。","Prioritize products that match your current ingredient direction and have stronger formula data.")]].map(([a,b])=><div key={a} style={{padding:"9px 10px",borderRadius:12,background:SOFT}}><b style={{fontSize:12.5}}>{a}</b><div style={{fontSize:11.5,color:MUTE,lineHeight:1.55,marginTop:2}}>{b}</div></div>)}</div></Section>
  <Section title={t("最适合你的 Top 5 产品","Top 5 products for you")}>
   <div style={{display:"grid",gap:9}}>{top.length?top.map((item:any,index:number)=>{const rating=matchRating(item);return <button key={item.id} onClick={()=>onProduct(item,concern)} style={{border:`1px solid ${LINE}`,borderRadius:14,padding:12,background:"white",textAlign:"left",color:INK,cursor:"pointer",fontFamily:sans}}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"flex-start"}}><div style={{minWidth:0}}><div style={{fontSize:10.5,color:SAGE,fontWeight:700}}>#{index+1} · {rating.label} · {item.score}</div><BilingualProductName product={item} compact/><div style={{fontSize:11.5,color:MUTE,lineHeight:1.55,marginTop:5}}>{whyText(item,language)}</div></div><ChevronRight size={15} color={MUTE}/></div></button>}):<div style={{fontSize:12,color:MUTE}}>{t("当前数据库里还没有足够高置信度的匹配结果。","There are not enough high-confidence matches in the current database yet.")}</div>}</div>
  </Section>
  <div style={{borderTop:`1px solid ${LINE}`,paddingTop:12,fontSize:10.5,color:MUTE,lineHeight:1.6}}>{t("本报告基于你填写的肤质信息与 Skincare101 当前已核验产品数据库生成，用于护肤决策参考，不替代医疗诊断。产品库和配方资料更新后，网页上的推荐排序可能变化。","This report is generated from your skin profile and Skincare101's currently verified product database. It supports skincare decisions and is not a medical diagnosis. Rankings may change as product and formula data are updated.")}</div>
 </div></>}
function Box({label,value}:{label:string;value:string}){return <div style={{border:`1px solid ${LINE}`,borderRadius:14,padding:12,background:"white"}}><div style={{fontSize:10.5,color:MUTE,marginBottom:4}}>{label}</div><div style={{fontSize:18,fontWeight:700}}>{value}</div></div>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section style={{padding:"14px 0",borderTop:`1px solid ${LINE}`}}><div style={{fontSize:12,fontWeight:700,marginBottom:9}}>{title}</div>{children}</section>}
function Chip({children,muted=false}:{children:React.ReactNode;muted?:boolean}){return <span style={{display:"inline-flex",border:`1px solid ${muted?"#D7CDB8":SAGE}`,borderRadius:999,padding:"6px 9px",background:muted?"#FAF7F0":"#EEF2EC",color:muted?MUTE:SAGE,fontSize:11.5}}>{children}</span>}
