import React,{useMemo,useRef,useState}from"react";
import html2canvas from"html2canvas";
import jsPDF from"jspdf";
import{Download,ChevronRight}from"lucide-react";
import type{SkinProfileRecord}from"../lib/skinProfile";
import{summarizeSkinProfile}from"../lib/skinProfile";
import type{SharedProductRecord}from"../lib/supabase";
import{matchRating,profileConcern,rankForProfile,suitabilityFor,type BrowseConcern}from"../lib/productPresentation";
import{localizeSkinSummary,useLanguage}from"../lib/i18n";
import BilingualProductName from"./BilingualProductName";

const INK="#252724",CARD="#FCFBF8",LINE="#D8D6CE",SAGE="#536D5D",MUTE="#777870",SOFT="#F1F2E9",WARM="#F8F3E8";
const sans="-apple-system,BlinkMacSystemFont,'Segoe UI','PingFang SC','Microsoft YaHei',sans-serif";
const INGREDIENT_ZH:Record<string,string>={"Glycerin":"甘油","Hyaluronic Acid":"透明质酸","Sodium Hyaluronate":"透明质酸钠","Panthenol":"泛醇","Betaine":"甜菜碱","Urea":"尿素","Ceramide":"神经酰胺","Cholesterol":"胆固醇","Phytosphingosine":"植物鞘氨醇","Squalane":"角鲨烷","Niacinamide":"烟酰胺","Centella Asiatica":"积雪草","Madecassoside":"羟基积雪草苷","Allantoin":"尿囊素","Bisabolol":"红没药醇","Beta-Glucan":"β-葡聚糖","Salicylic Acid":"水杨酸","Azelaic Acid":"壬二酸","Zinc PCA":"PCA 锌","Sulfur":"硫磺","Tranexamic Acid":"传明酸","Ascorbic Acid":"维生素C","Alpha-Arbutin":"α-熊果苷","Licorice":"甘草提取物","Retinol":"视黄醇 / A醇","Retinal":"视黄醛","Peptide":"肽类","Adenosine":"腺苷","Alcohol Denat.":"变性乙醇","Fragrance":"香精","Parfum":"香精","Menthol":"薄荷醇","Coconut Oil":"椰子油","Isopropyl Myristate":"肉豆蔻酸异丙酯","Glycolic Acid":"乙醇酸 / 果酸","Lactic Acid":"乳酸"};
const SYSTEM_EN:Record<string,string>={"屏障修护":"barrier support","补水保湿":"hydration","舒缓维稳":"soothing","抗老紧致":"anti-aging","控油净肤":"oil control","滋润锁水":"lipid support"};
function ing(name:string,language:"zh"|"en"){return language==="zh"?(INGREDIENT_ZH[name]||name):name}
function uniq(xs:string[]){return Array.from(new Set(xs)).filter(Boolean)}
function whyText(item:any,language:"zh"|"en"){
 const positives=(item.positiveEvidence||[]).slice(0,2).map((x:any)=>ing(x.name,language));
 const systems=(item.systemEvidence||[]).slice(0,2).map((x:any)=>language==="zh"?x.label:(SYSTEM_EN[x.label]||x.label));
 if(language==="zh")return positives.length?`配方证据命中 ${positives.join("、")}${systems.length?`，并覆盖${systems.join("、")}`:""}。`:`配方体系与当前${systems.join("、")||"基础护理"}需求较一致。`;
 return positives.length?`Formula evidence includes ${positives.join(", ")}${systems.length?` and supports ${systems.join(" and ")}`:""}.`:`The formula structure aligns with your current ${systems.join(" and ")||"care"} priorities.`;
}
function cautionText(item:any,language:"zh"|"en"){
 const negatives=(item.negativeEvidence||[]).slice(0,2).map((x:any)=>ing(x.name,language));
 if(negatives.length)return language==="zh"?`注意：配方中同时出现 ${negatives.join("、")}，建议结合耐受度观察。`:`Caution: ${negatives.join(", ")} also appears in the formula; monitor tolerance.`;
 return language==="zh"?"当前评分未发现明显冲突信号；仍建议新产品逐步引入。":"No major conflict signal in the current score; introduce new products gradually.";
}
function confidenceLabel(value:string,language:"zh"|"en"){const zh:Record<string,string>={high:"高",medium:"中",low:"低"};return language==="zh"?(zh[value]||value):value.toUpperCase()}
export default function SkinAnalysisReport({profile,products,onProduct}:{profile:SkinProfileRecord;products:SharedProductRecord[];onProduct:(p:SharedProductRecord,c:BrowseConcern)=>void}){
 const{t,language}=useLanguage();const reportRef=useRef<HTMLDivElement>(null);const[busy,setBusy]=useState(false);
 const summary=localizeSkinSummary(summarizeSkinProfile(profile),language);const concern=profileConcern(profile);const suitability=suitabilityFor(profile,concern);
 const top=useMemo(()=>rankForProfile(products,profile,concern).filter((p:any)=>p.recommendationAvailable&&p.score!=null).slice(0,5),[products,profile,concern]);
 const good=uniq(suitability.good.map(x=>x.name)).slice(0,8);const risky=uniq(suitability.risky.map(x=>x.name)).slice(0,8);const priority=summary.concerns[0]||t("屏障稳定","Barrier stability");
 const primary=good.slice(0,2),secondary=good.slice(2,4),support=good.slice(4,8);
 const tension=language==="zh"?`${priority}管理 × ${summary.sensitivity}耐受平衡`:`${priority} management × ${summary.sensitivity} tolerance`;
 const assessment=language==="zh"?`你的当前护理重点不是单纯追求更强的活性，而是在处理「${priority}」的同时控制刺激负担。基于你填写的肤质与敏感信息，建议先建立稳定、可持续的基础护理，再按优先级加入针对性成分。`:`Your priority is not simply stronger actives. The key is addressing ${priority} while controlling irritation load. Build a stable baseline first, then introduce targeted ingredients by priority.`;
 async function downloadPdf(){if(!reportRef.current||busy)return;setBusy(true);try{const canvas=await html2canvas(reportRef.current,{scale:2,useCORS:true,backgroundColor:"#FCFBF8"});const pdf=new jsPDF("p","mm","a4");const pageW=210,pageH=297,margin=10,imgW=pageW-margin*2,imgH=canvas.height*imgW/canvas.width;const img=canvas.toDataURL("image/png");let y=margin;pdf.addImage(img,"PNG",margin,y,imgW,imgH);let remaining=imgH-(pageH-margin*2);while(remaining>0){pdf.addPage();y=margin-(imgH-remaining);pdf.addImage(img,"PNG",margin,y,imgW,imgH);remaining-=pageH-margin*2}pdf.save(language==="zh"?"我的肤质分析报告.pdf":"My-Skin-Analysis-Report.pdf")}finally{setBusy(false)}}
 return <><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10,margin:"26px 0 10px"}}><div><div style={{fontSize:10.5,letterSpacing:".14em",color:SAGE,fontWeight:800}}>{t("个性化分析报告","PERSONALIZED ANALYSIS")}</div><div style={{fontSize:20,fontWeight:750,marginTop:4}}>{t("我的肤质分析报告","My Skin Analysis Report")}</div></div><button onClick={()=>void downloadPdf()} disabled={busy} style={{border:`1px solid ${LINE}`,borderRadius:10,padding:"9px 12px",background:CARD,color:SAGE,fontSize:11.5,fontWeight:700,display:"flex",alignItems:"center",gap:6,cursor:"pointer"}}><Download size={14}/>{busy?t("生成中…","Preparing…"):t("下载 PDF","Download PDF")}</button></div>
 <div ref={reportRef} style={{border:`1px solid ${LINE}`,borderRadius:12,padding:20,background:CARD,fontFamily:sans,color:INK,boxShadow:"0 8px 28px rgba(37,39,36,.045)"}}>
  <div style={{borderBottom:`2px solid ${SAGE}`,paddingBottom:16,marginBottom:16}}><div style={{fontSize:10.5,color:SAGE,fontWeight:800,letterSpacing:".15em"}}>SKINCARE101 · SKIN PROFILE ANALYSIS</div><h2 style={{fontSize:25,margin:"6px 0 7px",letterSpacing:"-.02em"}}>{t("我的肤质分析报告","My Skin Analysis Report")}</h2><div style={{fontSize:11.5,color:MUTE}}>{profile.name}</div></div>
  <section style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:9,marginBottom:14}}><Metric label={t("肤质类型","Skin type")} value={summary.skinType}/><Metric label={t("敏感程度","Sensitivity")} value={summary.sensitivity}/></section>
  <div style={{borderLeft:`4px solid ${SAGE}`,background:SOFT,padding:"13px 14px",margin:"4px 0 18px"}}><div style={{fontSize:10.5,color:MUTE,fontWeight:700,letterSpacing:".08em"}}>{t("核心判断","CORE ASSESSMENT")}</div><div style={{fontSize:18,fontWeight:800,color:SAGE,margin:"4px 0 6px"}}>{t("核心矛盾：","Key tension: ")}{tension}</div><div style={{fontSize:12.5,lineHeight:1.72,color:"#4E514D"}}>{assessment}</div></div>
  <Section no="01" title={t("当前问题与分析依据","Priority & analysis basis")}><div style={{fontSize:18,fontWeight:800,color:SAGE}}>{priority}</div>{summary.concerns.length>1&&<div style={{fontSize:11.5,color:MUTE,marginTop:4}}>{t("次要关注：","Secondary: ")}{summary.concerns.slice(1).join(" · ")}</div>}<div style={{marginTop:10,fontSize:12.5,lineHeight:1.7,color:"#4E514D"}}>{t("该优先级由你的肤质类型、敏感程度和当前关注问题共同决定。推荐逻辑会同时考虑目标成分、潜在刺激因素和产品配方体系，而不是只看单一明星成分。","This priority combines skin type, sensitivity and stated concerns. Recommendations consider target ingredients, irritation signals and formula systems rather than a single hero ingredient.")}</div></Section>
  <Section no="02" title={t("分级成分策略","Tiered ingredient strategy")}><Strategy label={t("一级优先","PRIMARY")} items={primary} language={language} text={t("优先寻找：与当前核心问题最直接相关，作为选品时的第一层筛选。","First filter: ingredients most directly linked to your current priority.")}/><Strategy label={t("二级辅助","SECONDARY")} items={secondary} language={language} text={t("作为辅助改善方向，不需要为了叠加成分而同时使用多款产品。","Supportive direction; avoid stacking products merely to accumulate actives.")}/><Strategy label={t("维稳底座","SUPPORT")} items={support} language={language} text={t("用于降低刺激负担、维持保湿或屏障稳定，为针对性护理提供耐受基础。","Supports tolerance, hydration or barrier stability around targeted care.")}/></Section>
  <Section no="03" title={t("暂缓 / 谨慎信号","Caution signals")}><div style={{display:"flex",gap:6,flexWrap:"wrap",marginBottom:8}}>{risky.length?risky.map(x=><Chip key={x} muted>{ing(x,language)}</Chip>):<span style={{fontSize:12,color:MUTE}}>{t("当前没有特别需要回避的常见成分信号。","No major common ingredient cautions detected.")}</span>}</div><div style={{fontSize:11.5,lineHeight:1.65,color:MUTE}}>{t("这里代表需要结合浓度、配方位置、使用频率和个人耐受判断，并不等于该成分对你绝对禁用。","These are context-dependent caution signals, not absolute bans; concentration, formula position, frequency and tolerance still matter.")}</div></Section>
  <Section no="04" title={t("基础护理策略","Baseline care strategy")}><div style={{display:"grid",gap:0}}>{[[t("STEP 1 · 稳定","STEP 1 · STABILIZE"),t("先固定温和清洁、合适保湿和白天防晒，避免频繁更换基础产品。","Stabilize gentle cleansing, suitable moisturization and daytime sunscreen.")],[t("STEP 2 · 单点加入","STEP 2 · ADD ONE VARIABLE"),t("针对核心问题一次只新增一个主要活性方向，给皮肤足够观察时间。","Introduce one main active direction at a time and allow enough observation time.")],[t("STEP 3 · 根据反馈调整","STEP 3 · ADJUST"),t("出现持续刺痛、泛红或屏障不稳时，优先降低频率或退回基础护理。","If persistent stinging, redness or instability appears, reduce frequency or return to baseline care.")]].map(([a,b],i)=><div key={a} style={{padding:"10px 0",borderTop:i?`1px solid ${LINE}`:"none"}}><b style={{fontSize:11.5,color:SAGE}}>{a}</b><div style={{fontSize:11.5,color:MUTE,lineHeight:1.6,marginTop:3}}>{b}</div></div>)}</div></Section>
  <Section no="05" title={t("Top 5 个性化产品匹配","Top 5 personalized product matches")}><div style={{display:"grid",gap:10}}>{top.length?top.map((item:any,index:number)=>{const rating=matchRating(item);return <button key={item.id} onClick={()=>onProduct(item,concern)} style={{border:`1px solid ${LINE}`,borderRadius:8,padding:13,background:"white",textAlign:"left",color:INK,cursor:"pointer",fontFamily:sans}}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"flex-start"}}><div style={{minWidth:0,flex:1}}><div style={{display:"flex",gap:7,alignItems:"center",flexWrap:"wrap",marginBottom:4}}><span style={{fontSize:10.5,color:SAGE,fontWeight:800}}>#{index+1}</span><span style={{fontSize:10.5,fontWeight:800,color:SAGE}}>{t("MATCH","MATCH")} {item.score}%</span><span style={{fontSize:10,color:MUTE}}>{rating.label}</span><span style={{fontSize:10,color:MUTE}}>{t("置信度","CONFIDENCE")} {confidenceLabel(item.confidence,language)}</span></div><BilingualProductName product={item} compact/><div style={{marginTop:7,paddingTop:7,borderTop:`1px solid ${LINE}`,fontSize:11.5,lineHeight:1.58,color:"#555852"}}><b>{t("推荐依据：","Why it fits: ")}</b>{whyText(item,language)}</div><div style={{fontSize:10.8,lineHeight:1.55,color:MUTE,marginTop:4}}>{cautionText(item,language)}</div></div><ChevronRight size={15} color={MUTE}/></div></button>}):<div style={{fontSize:12,color:MUTE}}>{t("当前数据库里还没有足够高置信度的匹配结果。","There are not enough high-confidence matches in the current database yet.")}</div>}</div></Section>
  <div style={{borderTop:`1px solid ${LINE}`,paddingTop:12,fontSize:10.2,color:MUTE,lineHeight:1.6}}>{t("方法说明：本报告基于你填写的肤质信息与 Skincare101 当前已核验产品数据库，通过个性化配方匹配规则生成。评分同时考虑正向成分证据、风险信号、配方体系与数据完整度。用于护肤决策参考，不替代医疗诊断。","Methodology: this report combines your skin profile with Skincare101's verified product database and personalized formula-matching rules. Scores consider positive ingredient evidence, risk signals, formula systems and data completeness. It supports skincare decisions and is not a medical diagnosis.")}</div>
 </div></>}
function Metric({label,value}:{label:string;value:string}){return <div style={{border:`1px solid ${LINE}`,padding:"11px 12px",background:"white"}}><div style={{fontSize:10.5,color:MUTE,marginBottom:3,textTransform:"uppercase",letterSpacing:".05em"}}>{label}</div><div style={{fontSize:17,fontWeight:800}}>{value}</div></div>}
function Section({no,title,children}:{no:string;title:string;children:React.ReactNode}){return <section style={{padding:"16px 0",borderTop:`1px solid ${LINE}`}}><div style={{display:"flex",alignItems:"baseline",gap:8,marginBottom:10}}><span style={{fontSize:10,color:SAGE,fontWeight:800}}>{no}</span><div style={{fontSize:13,fontWeight:800}}>{title}</div></div>{children}</section>}
function Strategy({label,items,language,text}:{label:string;items:string[];language:"zh"|"en";text:string}){if(!items.length)return null;return <div style={{padding:"10px 0",borderTop:`1px solid ${LINE}`}}><div style={{fontSize:10.5,fontWeight:800,color:SAGE,marginBottom:6}}>{label}</div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{items.map(x=><Chip key={x}>{ing(x,language)}</Chip>)}</div><div style={{fontSize:11.2,color:MUTE,lineHeight:1.6,marginTop:6}}>{text}</div></div>}
function Chip({children,muted=false}:{children:React.ReactNode;muted?:boolean}){return <span style={{display:"inline-flex",border:`1px solid ${muted?"#D8CDB8":SAGE}`,borderRadius:4,padding:"5px 7px",background:muted?WARM:"#EEF2EC",color:muted?MUTE:SAGE,fontSize:11}}>{children}</span>}
