import React,{useEffect,useMemo,useRef,useState}from"react";
import{ArrowLeft,Search}from"lucide-react";
import type{SharedProductRecord}from"../lib/supabase";
import type{SkinProfileRecord}from"../lib/skinProfile";
import{summarizeSkinProfile}from"../lib/skinProfile";
import{formulaDataLabel,matchesSkinType,oneLineVerdict,personalizedScore,profileConcern,matchRating,confidenceLabel,type BrowseConcern,type BrowseSkinType}from"../lib/productPresentation";
import{useLanguage}from"../lib/i18n";
import{productSearchScore}from"../lib/productSearch";
import{logSearchEvent,logSearchSelection}from"../lib/searchAnalytics";
import{displayCategory,displayConfidence,displayFormulaLabel,displaySkinLabel}from"../lib/displayI18n";
import{getBrandProfile}from"../data/brandProfiles";
import BilingualProductName from"./BilingualProductName";

const INK="#252724",BG="#F6F4EF",CARD="#FCFBF8",LINE="#DEDCD5",SAGE="#667A6C",MUTE="#777870";
const sans="-apple-system, BlinkMacSystemFont, 'Segoe UI', 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', sans-serif";

const LUXURY=new Set(["Chanel","Dior","La Mer","La Prairie","SK-II","Shiseido","Lancôme","Estée Lauder","Clé de Peau Beauté","Helena Rubinstein","Sulwhasoo","YSL Beauty"]);
const EVERYDAY=new Set(["Nivea","Garnier","The Ordinary","Paula's Choice","L'Oréal Paris","Bioré","COSRX","Beauty of Joseon","SKIN1004","Anua","Medicube","ROUND LAB","LANEIGE","KOSÉ","ETUDE","VT","TOCOBO","TIRTIR","PROYA","Pechoin","CHANDO","KANS","OSM","MARUBI"]);
const DERMO=new Set(["La Roche-Posay","Avène","Bioderma","CeraVe","Cetaphil","Eucerin","Vichy","SVR","Uriage","Neutrogena","WINONA","Curél"]);
const NICHE=new Set(["Allies of Skin","Alpha-H","Nuxe","Facetheory","The Inkey List","Purito SEOUL","mixsoon","celimax","haruharu wonder","Abib","numbuzin","PETERSON'S LAB","HomeFacialPro","BIOHYALUX","QUADHA","Dr.Alva","Simpcare","HBN","PMPM","UNISKIN","ma:nyo","ISNTREE","AXIS-Y","Dr.G","Ultraceuticals","Aesop"]);
const KBEAUTY=new Set(["Torriden","TOCOBO","ROUND LAB","ma:nyo","Dr.G","ISNTREE","AXIS-Y","numbuzin","mixsoon","celimax","Abib","haruharu wonder","Purito SEOUL","SKIN1004","Anua","Beauty of Joseon","COSRX","Medicube","LANEIGE","ETUDE","VT","TIRTIR"]);

export type ExploreEntry="forYou"|"explore"|"search"|"brands"|"concerns"|"luxury"|"niche";
type MasterCategory="all"|"moisturizer"|"serum"|"eye"|"cleanser"|"toner"|"sunscreen"|"mask"|"lip"|"treatment";
type Edit="all"|"everyday"|"dermo"|"luxury"|"niche"|"kbeauty";
type PriceFilter="all"|"budget"|"mid"|"premium";
type Sort="match"|"quality"|"brand"|"priceLow"|"priceHigh";

const MASTER_CATEGORIES:MasterCategory[]=["all","moisturizer","serum","eye","cleanser","toner","sunscreen","mask","lip","treatment"];
function masterCategoryLabel(category:MasterCategory,language:"zh"|"en"){
 const labels:Record<MasterCategory,[string,string]>={all:["全部类别","All categories"],moisturizer:["保湿霜 / 面霜","Moisturizer / Cream"],serum:["精华","Serum"],eye:["眼部护理","Eye Care"],cleanser:["洁面 / 卸妆","Cleanser / Makeup Remover"],toner:["化妆水 / 精华水","Toner / Essence"],sunscreen:["防晒","Sunscreen"],mask:["面膜","Mask"],lip:["唇部护理","Lip Care"],treatment:["特殊护理","Special Treatment"]};
 return labels[category][language==="zh"?0:1];
}
function normalizeMasterCategory(raw:string|undefined|null):MasterCategory{const value=(raw||"").trim().toLowerCase().replace(/[_-]+/g," ");if(!value)return"treatment";if(/lip|唇|润唇|护唇/.test(value))return"lip";if(/eye|眼部|眼霜|眼精华|眼膜/.test(value))return"eye";if(/sunscreen|sun screen|spf|防晒/.test(value))return"sunscreen";if(/mask|面膜/.test(value))return"mask";if(/cleanser|cleansing|cleanse|makeup remover|remover|卸妆|洁面|洗面|清洁/.test(value))return"cleanser";if(/toner|essence water|treatment essence|lotion water|爽肤水|化妆水|精华水|柔肤水/.test(value))return"toner";if(/serum|ampoule|booster|concentrate|face oil|facial oil|essence|精华油|面部油|精华|安瓶/.test(value))return"serum";if(/moisturizer|moisturiser|cream|lotion|emulsion|乳液|面霜|保湿霜/.test(value))return"moisturizer";return"treatment"}
function priceBucket(brand:string):Exclude<PriceFilter,"all">{const p=(getBrandProfile(brand).pricePositioning||"").toLowerCase();if(/超高端|高端|luxury|prestige/.test(p))return"premium";if(/中端|中高端|masstige|mid/.test(p))return"mid";return"budget"}
function priceRank(brand:string){const b=priceBucket(brand);return b==="budget"?1:b==="mid"?2:3}
function countryOf(brand:string){return getBrandProfile(brand).country||"其他"}

export default function V3Explore({products,profile,entry="explore",onBack,onProduct}:{products:SharedProductRecord[];profile:SkinProfileRecord|null;entry?:ExploreEntry;onBack:()=>void;onProduct:(p:SharedProductRecord,c:BrowseConcern)=>void}){
 const{t,language}=useLanguage();
 const[query,setQuery]=useState("");const[brand,setBrand]=useState("全部品牌");const[country,setCountry]=useState("全部国家 / 地区");const[price,setPrice]=useState<PriceFilter>("all");const[category,setCategory]=useState<MasterCategory>("all");const[skinType,setSkinType]=useState<BrowseSkinType>("all");const[concern,setConcern]=useState<BrowseConcern>(profile?profileConcern(profile):"all");const[sort,setSort]=useState<Sort>(profile?"match":"quality");const[edit,setEdit]=useState<Edit>(entry==="luxury"?"luxury":entry==="niche"?"niche":"all");const[visible,setVisible]=useState(40);const ref=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(entry==="search")ref.current?.focus()},[entry]);
 const summary=summarizeSkinProfile(profile);
 const countries=useMemo(()=>["全部国家 / 地区",...Array.from(new Set(products.map(p=>countryOf(p.brand))).values()).filter(Boolean).sort((a,b)=>a.localeCompare(b))],[products]);
 const brands=useMemo(()=>["全部品牌",...Array.from(new Set(products.filter(p=>country==="全部国家 / 地区"||countryOf(p.brand)===country).map(p=>p.brand))).sort((a,b)=>a.localeCompare(b))],[products,country]);
 useEffect(()=>{if(brand!=="全部品牌"&&!brands.includes(brand))setBrand("全部品牌")},[country,brands,brand]);
 const skinTypes:Array<[BrowseSkinType,string]>=[["all",t("全部肤质","All skin types")],["dry",t("干性","Dry")],["oily",t("油性","Oily")],["combination",t("混合性","Combination")],["sensitive",t("敏感倾向","Sensitive")],["acne",t("痘肌","Acne-prone")]];
 const concerns:Array<[BrowseConcern,string]>=[["all",t("全部问题","All concerns")],["hydration",t("缺水","Dehydration")],["barrier",t("屏障","Barrier")],["redness",t("泛红","Redness")],["pores",t("毛孔","Pores")],["acne",t("痘痘","Acne")],["pigmentation",t("色沉","Pigmentation")],["aging",t("抗老","Aging")]];
 const filtered=useMemo(()=>products.map(product=>({product,searchScore:query.trim()?productSearchScore(product,query):1})).filter(({product:p,searchScore})=>searchScore>0&&(brand==="全部品牌"||p.brand===brand)&&(country==="全部国家 / 地区"||countryOf(p.brand)===country)&&(price==="all"||priceBucket(p.brand)===price)&&(category==="all"||normalizeMasterCategory(p.category)===category)&&matchesSkinType(p,skinType)&&(edit!=="luxury"||LUXURY.has(p.brand))&&(edit!=="niche"||NICHE.has(p.brand))&&(edit!=="everyday"||EVERYDAY.has(p.brand))&&(edit!=="dermo"||DERMO.has(p.brand))&&(edit!=="kbeauty"||KBEAUTY.has(p.brand))).map(({product,searchScore})=>({product,searchScore,match:personalizedScore(product,profile,concern)})).sort((a,b)=>query.trim()?b.searchScore-a.searchScore:sort==="brand"?`${a.product.brand} ${a.product.name}`.localeCompare(`${b.product.brand} ${b.product.name}`):sort==="quality"?b.product.dataCompleteness-a.product.dataCompleteness:sort==="priceLow"?priceRank(a.product.brand)-priceRank(b.product.brand):sort==="priceHigh"?priceRank(b.product.brand)-priceRank(a.product.brand):(b.match?.score||0)-(a.match?.score||0)),[products,query,brand,country,price,category,skinType,concern,sort,edit,profile]);
 useEffect(()=>{const q=query.trim();if(q.length<2)return;const timer=window.setTimeout(()=>{void logSearchEvent(q,filtered.length,"explore",language).catch(()=>{})},650);return()=>window.clearTimeout(timer)},[query,filtered.length,language]);
 const select={minWidth:0,border:`1px solid ${LINE}`,borderRadius:14,padding:11,background:CARD,fontSize:12,fontFamily:sans,color:INK}as const;
 const ratingLabel=(stars:number)=>stars===5?t("非常适合","Excellent match"):stars===4?t("适合","Good match"):stars===3?t("可以用","Suitable"):stars===2?t("谨慎尝试","Caution"):stars===1?t("不推荐","Not recommended"):t("数据不足","Insufficient data");
 const profileText=profile?`${displaySkinLabel(summary.skinType,language)} · ${displaySkinLabel(summary.sensitivity,language)}${summary.concerns.length?` · ${summary.concerns.map(x=>displaySkinLabel(x,language)).join(" / ")}`:""}`:"";
 const verdict=(p:SharedProductRecord)=>language==="zh"?oneLineVerdict(p):p.ingredientListType==="partial"?`${displayCategory(p.category,language)} with partial formula data; treat the match as provisional until the full INCI is verified.`:`Verified ${displayCategory(p.category,language).toLowerCase()} formula analyzed for hydration, barrier, soothing, oil-control and active-system fit.`;
 function choose(p:SharedProductRecord){const q=query.trim();if(q)void logSearchSelection(q,p.id,filtered.length,"explore",language).catch(()=>{});onProduct(p,concern)}
 return <div style={{minHeight:"100vh",background:BG,color:INK,padding:"22px 18px 54px",fontFamily:sans}}><div style={{maxWidth:680,margin:"0 auto"}}>
  <button onClick={onBack} style={{border:0,background:"transparent",padding:0,color:MUTE,fontSize:13,cursor:"pointer",marginBottom:30,display:"flex",gap:7,alignItems:"center",fontFamily:sans}}><ArrowLeft size={15}/>{t("返回我的肤质","Back to My Skin")}</button>
  <div style={{fontSize:11,letterSpacing:".12em",color:SAGE,fontWeight:700,marginBottom:10}}>{entry==="forYou"?"FOR YOU":"PRODUCT LIBRARY"}</div>
  <h1 style={{fontSize:32,fontWeight:650,lineHeight:1.2,letterSpacing:"-.035em",margin:"0 0 10px"}}>{entry==="forYou"?t("最适合你的，先排在前面","Your best matches, ranked first"):t("找到更适合你的产品","Find products that fit you better")}</h1>
  <p style={{fontSize:14,color:MUTE,lineHeight:1.7,margin:"0 0 12px"}}>{profile?t(`当前档案：${profileText}`,`Current profile: ${profileText}`):t("建立肤质档案后可查看个人五星匹配。","Create a skin profile to see personal five-star matches.")}</p>
  {profile&&<div style={{border:`1px solid ${LINE}`,borderRadius:16,background:"#E9EEE9",padding:"12px 14px",fontSize:12,color:SAGE,lineHeight:1.6,marginBottom:20}}>{t("适配度看肤质和需求；数据完整度只影响可信度。3 星及以上表示可以使用。","Fit is driven by skin needs; data completeness affects confidence only. Three stars and above means suitable.")}</div>}
  <div style={{display:"flex",gap:8,marginBottom:13,flexWrap:"wrap"}}>{[["all",t("全部","All")],["everyday",t("日常常见","Everyday")],["dermo",t("药妆","Dermocosmetic")],["kbeauty",t("韩系热门","K-Beauty Trending")],["luxury",t("高端","Luxury")],["niche",t("小众 / 新锐","Niche / Emerging")]].map(([k,l])=><button key={k} onClick={()=>setEdit(k as Edit)} style={{border:`1px solid ${edit===k?SAGE:LINE}`,borderRadius:999,padding:"8px 11px",background:edit===k?"#E9EEE9":CARD,color:edit===k?SAGE:INK,fontFamily:sans,fontSize:12}}>{l}</button>)}</div>
  <div style={{position:"relative",marginBottom:10}}><Search size={17} color={MUTE} style={{position:"absolute",left:14,top:15}}/><input ref={ref} value={query} onChange={e=>{setQuery(e.target.value);setVisible(40)}} placeholder={t("搜品牌、产品正式名、中文名或昵称，例如 Torriden / 黑金眼霜","Search brands, formal names, local names or nicknames")} style={{width:"100%",boxSizing:"border-box",border:`1px solid ${LINE}`,borderRadius:16,padding:"13px 14px 13px 42px",background:CARD,fontSize:14,fontFamily:sans,outline:"none"}}/></div>
  <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:8}}><select value={country} onChange={e=>setCountry(e.target.value)} style={select}>{countries.map(x=><option key={x} value={x}>{x==="全部国家 / 地区"?t("全部国家 / 地区","All countries / regions"):x}</option>)}</select><select value={brand} onChange={e=>setBrand(e.target.value)} style={select}>{brands.map(x=><option key={x} value={x}>{x==="全部品牌"?t("全部品牌","All brands"):x}</option>)}</select></div>
  <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:8}}><select value={price} onChange={e=>setPrice(e.target.value as PriceFilter)} style={select}><option value="all">{t("全部价位","All price levels")}</option><option value="budget">{t("大众 / 亲民","Budget / Mass")}</option><option value="mid">{t("中端","Mid-range")}</option><option value="premium">{t("高端","Premium / Luxury")}</option></select><select value={skinType} onChange={e=>setSkinType(e.target.value as BrowseSkinType)} style={select}>{skinTypes.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></div>
  <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:10}}><select value={category} onChange={e=>setCategory(e.target.value as MasterCategory)} style={select}>{MASTER_CATEGORIES.map(x=><option key={x} value={x}>{masterCategoryLabel(x,language)}</option>)}</select><select value={concern} onChange={e=>setConcern(e.target.value as BrowseConcern)} style={select}>{concerns.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></div>
  <div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center",marginBottom:14,fontSize:11,color:MUTE}}><span>{t(`${filtered.length} 款产品`,`${filtered.length} products`)}</span><select value={sort} onChange={e=>setSort(e.target.value as Sort)} style={{border:0,background:"transparent",color:MUTE,fontFamily:sans,maxWidth:"62%"}}><option value="match">{t("最适合我","Best match")}</option><option value="priceLow">{t("价位：低 → 高","Price: low → high")}</option><option value="priceHigh">{t("价位：高 → 低","Price: high → low")}</option><option value="quality">{t("数据最完整","Most complete data")}</option><option value="brand">{t("品牌 A–Z","Brand A–Z")}</option></select></div>
  {query.trim()&&filtered.length===0&&<div style={{border:`1px solid ${LINE}`,borderRadius:16,padding:14,background:CARD,color:MUTE,fontSize:12,marginBottom:12}}>{t("没有找到。这个搜索词会作为补库优先级线索记录。","No result. This query is logged as a catalog-expansion signal.")}</div>}
  <div style={{display:"grid",gap:10}}>{filtered.slice(0,visible).map(({product:p,match},rank)=>{const formula=formulaDataLabel(p),rating=matchRating(match);return <button key={p.id} onClick={()=>choose(p)} style={{border:`1px solid ${rank<3&&profile&&!query.trim()?SAGE:LINE}`,borderRadius:20,background:CARD,padding:"16px",textAlign:"left",fontFamily:sans}}>{profile&&rank<3&&!query.trim()&&<div style={{fontSize:10,color:SAGE,fontWeight:700,letterSpacing:".08em",marginBottom:8}}>{rank===0?t("BEST MATCH · 最佳匹配","BEST MATCH"):`ALTERNATIVE ${rank}`}</div>}<div style={{display:"flex",justifyContent:"space-between",gap:14}}><BilingualProductName product={p}/>{profile&&<div style={{textAlign:"right",flexShrink:0}}><div style={{fontSize:15,color:rating.stars>=3?SAGE:"#8B6660",letterSpacing:.5}}>{rating.starsText}</div><div style={{fontSize:11,fontWeight:650,color:INK,marginTop:3}}>{ratingLabel(rating.stars)}</div><div style={{fontSize:9.5,color:MUTE,marginTop:2}}>{t("可信度","Confidence")} {displayConfidence(confidenceLabel(match?.confidence),language)}</div></div>}</div><div style={{fontSize:12,color:MUTE,lineHeight:1.6,margin:"8px 0 7px"}}>{verdict(p)}</div><div style={{display:"flex",gap:6,flexWrap:"wrap",fontSize:11,color:MUTE}}><span>{countryOf(p.brand)}</span><span>·</span><span>{displayCategory(p.category,language)}</span><span>·</span><span>{displayFormulaLabel(formula.label,language)}</span></div></button>})}</div>
  {filtered.length>visible&&<button onClick={()=>setVisible(v=>v+40)} style={{width:"100%",marginTop:12,border:`1px solid ${LINE}`,borderRadius:16,padding:12,background:CARD,fontFamily:sans}}>{t("再显示 40 款","Show 40 more")}</button>}
 </div></div>
}
