import React,{useMemo,useState}from"react";
import{ChevronRight,Clock3,ExternalLink,FlaskConical,Heart,ShieldCheck,Shuffle,Sparkles,UserRound,WandSparkles,Search}from"lucide-react";
import type{SkinProfileRecord}from"../lib/skinProfile";
import type{SharedProductRecord}from"../lib/supabase";
import{matchRating,personalizedScore,profileConcern}from"../lib/productPresentation";
import{useLanguage}from"../lib/i18n";
import{HandDrawnHero,SketchSprig,SketchUnderline}from"./HandDrawnVisuals";
import BilingualProductName from"./BilingualProductName";
import SkincareKnowledgeCards from"./SkincareKnowledgeCards";
import BlogEntry from "./BlogEntry";

const INK="#263027",PAPER="transparent",CARD="#FBF6EA",LINE="#D9D0BC",SAGE="#2F5A40",MUSTARD="#D5A92E",MUTE="#6F6A5F",ROSE="#A96F68";
const SANS="'IBM Plex Sans','PingFang SC','Hiragino Sans GB','Microsoft YaHei',system-ui,sans-serif";
const XIAOHONGSHU_PROFILE_URL="https://xhslink.cn/m/ADVwicJCqyb";
const NIUMA_TEST_URL="/play/niuma/";

function CoreCard({icon,eyebrow,title,body,onClick,disabled=false,compact=false}:any){return <button onClick={disabled?undefined:onClick} disabled={disabled} style={{width:"100%",textAlign:"left",border:`1px solid ${LINE}`,borderRadius:compact?19:24,padding:compact?"15px 14px":"20px 18px",background:CARD,cursor:disabled?"default":"pointer",opacity:disabled?.48:1,boxShadow:"0 7px 22px rgba(40,55,42,.05)",fontFamily:SANS,position:"relative",overflow:"hidden"}}><div style={{position:"absolute",right:-7,bottom:-10,opacity:.14,transform:"rotate(5deg)"}}><SketchSprig size={compact?48:62}/></div><div style={{position:"absolute",left:0,top:0,bottom:0,width:4,background:MUSTARD,opacity:.8}}/><div style={{display:"flex",alignItems:"center",gap:compact?11:15,position:"relative"}}><div style={{width:compact?38:46,height:compact?38:46,borderRadius:13,background:"#E9EFE7",display:"grid",placeItems:"center",color:SAGE,flexShrink:0,border:"1px solid #D9E1D5"}}>{icon}</div><div style={{minWidth:0,flex:1}}><div style={{fontSize:10.5,fontWeight:600,letterSpacing:".06em",color:SAGE,marginBottom:3}}>{eyebrow}</div><div style={{fontSize:compact?16:20,fontWeight:600,letterSpacing:"-.015em",lineHeight:1.28,color:INK,marginBottom:compact?3:6}}>{title}</div><div style={{fontSize:compact?12.5:14,color:MUTE,lineHeight:1.55}}>{body}</div></div>{!disabled&&<ChevronRight size={17} color={SAGE} style={{flexShrink:0}}/>}</div></button>}

function NiumaEntry({compact=false,t}:{compact?:boolean;t:(zh:string,en:string)=>string}){return <a href={NIUMA_TEST_URL} style={{display:"block",textDecoration:"none",color:"inherit",marginTop:compact?0:12}}><div style={{border:"1px solid #D7B3B0",borderRadius:compact?19:24,padding:compact?"15px 14px":"18px 17px",background:"linear-gradient(145deg,#FFF0F2,#FBE6D9)",boxShadow:"0 7px 22px rgba(96,55,55,.06)",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",right:12,top:9,fontSize:compact?28:36,opacity:.9}}>🐮</div><div style={{fontSize:10.5,fontWeight:800,letterSpacing:".11em",color:ROSE,marginBottom:5}}>PLAY · 牛籍鉴定</div><div style={{fontSize:compact?16:20,fontWeight:700,color:INK,lineHeight:1.25,paddingRight:44}}>{t("测测你是牛来，还是牛马？","Are you niulai or just niuma?")}</div><div style={{fontSize:compact?12.5:13.5,color:MUTE,lineHeight:1.55,marginTop:5,paddingRight:32}}>{t("2026 职场十二牲肖 · 12 道离谱但真实的职场题","2026 workplace zodiac · 12 absurdly real office questions")}</div><div style={{display:"inline-flex",alignItems:"center",gap:5,marginTop:9,fontSize:12,fontWeight:700,color:ROSE}}>{t("开始鉴定你的牛籍","Check your 牛籍")}<ChevronRight size={14}/></div></div></a>}

export default function V3Home({goTo,profile=null,products=[],onCreateProfile,onProduct}:{goTo:(target:string)=>void;profile:SkinProfileRecord|null;products:SharedProductRecord[];onCreateProfile:()=>void;onProduct:(product:SharedProductRecord)=>void}){
 const{t}=useLanguage();
 const hasProfile=Boolean(profile);
 const[luckySeed,setLuckySeed]=useState(()=>Math.floor(Math.random()*1000000));
 const luckyPicks=useMemo(()=>{
  if(!products.length)return[];
  const concern=profile?profileConcern(profile):"all";
  const scored=products.filter(p=>(p.dataCompleteness||0)>=50).map(product=>({product,match:personalizedScore(product,profile,concern)}));
  const eligible=profile?scored.filter(x=>matchRating(x.match).stars>=3):scored;
  const preferred=profile?eligible.filter(x=>matchRating(x.match).stars>=4):eligible;
  const source=(preferred.length>=2?preferred:eligible).slice(0,Math.min(80,(preferred.length>=2?preferred:eligible).length));
  if(!source.length)return[];
  if(source.length===1)return source;
  const first=source[luckySeed%source.length];
  const alternatives=source.filter(x=>x.product.id!==first.product.id&&x.product.brand!==first.product.brand);
  const secondPool=alternatives.length?alternatives:source.filter(x=>x.product.id!==first.product.id);
  const second=secondPool[(Math.floor(luckySeed/11)+7)%secondPool.length];
  return[first,second];
 },[products,profile,luckySeed]);
 const luckySection=luckyPicks.length>0&&<section style={{border:"1px solid #D9C58A",borderRadius:24,background:"linear-gradient(145deg,#FFF9E8,#FBF3D9)",padding:16,margin:"0 0 24px",boxShadow:"0 8px 24px rgba(86,69,21,.06)"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"flex-start",marginBottom:12}}><div><div style={{fontSize:10.5,letterSpacing:".12em",fontWeight:800,color:"#9C791F",marginBottom:4}}>TODAY YOU GOT LUCKY</div><div style={{fontSize:17,fontWeight:700}}>{t("今天给你抽到这两款","Two lucky picks for you")}</div><div style={{fontSize:11.5,color:MUTE,lineHeight:1.55,marginTop:4}}>{hasProfile?t("先按你的肤质筛掉明显不合适的，再留一点随机惊喜。","Skin-fit comes first; the surprise comes second."):t("先随机认识两款产品。建档后会自动加入肤质适配。","Meet two random products. Create a profile to add skin-fit filtering.")}</div></div><button onClick={()=>setLuckySeed(Math.floor(Math.random()*1000000))} style={{border:"1px solid #D9C58A",borderRadius:999,background:"#FFFDF5",padding:"8px 10px",fontFamily:SANS,color:"#9C791F",fontSize:11,fontWeight:700,cursor:"pointer",display:"flex",alignItems:"center",gap:5,flexShrink:0}}><Shuffle size={13}/>{t("再摇一次","Roll again")}</button></div><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:8}}>{luckyPicks.map(({product,match})=>{const rating=matchRating(match);return <button key={product.id} onClick={()=>onProduct(product)} style={{minWidth:0,border:"1px solid #E5D8AA",borderRadius:17,background:"rgba(255,255,255,.7)",padding:12,textAlign:"left",fontFamily:SANS,cursor:"pointer"}}><BilingualProductName product={product}/>{hasProfile&&<div style={{fontSize:11,color:SAGE,marginTop:7}}>{rating.starsText} · {rating.stars>=4?t("适合你","Good match"):t("可以尝试","Suitable")}</div>}<div style={{fontSize:10.5,color:MUTE,marginTop:6}}>{product.brand}</div></button>})}</div></section>;
 return <div style={{padding:"16px 0 60px",fontFamily:SANS,color:INK,background:PAPER}}>
  <header style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,marginBottom:24,paddingRight:90}}><div><div style={{display:"flex",alignItems:"baseline",gap:8,whiteSpace:"nowrap"}}><div className="peaced-brand" aria-label="peaced. by Rae">peaced.</div><span style={{fontSize:12,fontWeight:500,letterSpacing:".04em",color:MUTE}}>by Rae</span></div><SketchUnderline width={150}/><div style={{fontSize:10.5,fontWeight:500,letterSpacing:".09em",color:MUTE,marginTop:3}}>PERSONALIZED SKINCARE INTELLIGENCE</div></div><button onClick={()=>goTo("account")} style={{border:`1px solid ${LINE}`,borderRadius:15,width:44,height:44,background:CARD,display:"grid",placeItems:"center",cursor:"pointer",color:SAGE}} aria-label={t("个人中心","Profile & account")}><UserRound size={18}/></button></header>

  {!hasProfile?<>
   <button onClick={()=>goTo("account")} style={{width:"100%",border:`1px solid ${LINE}`,borderRadius:15,padding:"12px 13px",background:CARD,color:MUTE,fontFamily:SANS,fontSize:13,cursor:"pointer",marginBottom:20}}>{t("已经建过档？从个人中心登录找回 →","Already have a profile? Sign in from your profile center →")}</button>
   <section style={{padding:"18px 16px 14px",borderRadius:26,background:"linear-gradient(145deg,#2B523B,#234631)",color:"#FFF9EC",boxShadow:"0 12px 30px rgba(35,70,49,.14)",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",right:-14,top:-15,opacity:.35}}><SketchSprig size={98}/></div><div style={{fontSize:11.5,fontWeight:600,color:"#E3C65A",letterSpacing:".065em",marginBottom:13}}>PERSONAL SKINCARE, WITHOUT THE NOISE</div><h1 style={{fontSize:"clamp(32px,8vw,39px)",fontWeight:600,lineHeight:1.17,letterSpacing:"-.035em",margin:"0 0 15px",maxWidth:400,color:"#FFF9EC"}}>{t("让皮肤恢复平静，也不用再为买护肤品焦虑。","Calmer skin. Smarter choices. Less skincare anxiety.")}</h1><p style={{fontSize:15,color:"#E8E5D8",lineHeight:1.72,margin:0,maxWidth:420}}>{t("看懂你的皮肤、产品和配方，再决定真正需要什么。","Understand your skin, products, and formulas before deciding what you really need.")}</p><div style={{width:72,height:5,borderRadius:999,background:MUSTARD,marginTop:18}}/></section>
   <HandDrawnHero/>
   <div style={{display:"flex",gap:20,color:MUTE,fontSize:12.5,margin:"0 2px 23px",flexWrap:"wrap"}}><span style={{display:"inline-flex",gap:7,alignItems:"center"}}><Clock3 size={14} color={SAGE}/>{t("约3分钟建档","About 3 minutes")}</span><span style={{display:"inline-flex",gap:7,alignItems:"center"}}><ShieldCheck size={14} color={SAGE}/>{t("不是医疗诊断","Not medical diagnosis")}</span></div>
   <div style={{display:"grid",gap:12}}><CoreCard icon={<UserRound size={18}/>} eyebrow="01  MY SKIN" title={t("先认识你的皮肤","Know My Skin")} body={t("完成肤质分析，建立贯穿整个 PEACED 的个人档案","Create the skin profile that powers PEACED")} onClick={onCreateProfile}/><CoreCard icon={<Search size={18}/>} eyebrow="02  DISCOVER" title={t("先逛逛产品","Discover Products")} body={t("按品牌、品类和护肤问题探索产品库","Browse by brand, category, and concern")} onClick={()=>goTo("explore")}/><CoreCard icon={<FlaskConical size={18}/>} eyebrow="03  CHECK" title={t("手上有产品？直接查","Check a Product")} body={t("搜索产品、查成分，或拍摄配料表","Search a product, inspect ingredients, or scan a label")} onClick={()=>goTo("upload")}/></div>
   <NiumaEntry t={t}/>
   <div style={{marginTop:24}}>{luckySection}</div>
   <SkincareKnowledgeCards/>
   <BlogEntry/>
   <section aria-label={t("关于作者","About the author")} style={{marginTop:22,border:"1px solid "+LINE,borderRadius:24,padding:"18px 17px",background:"linear-gradient(145deg,#FFF9ED,#F1E9D8)",boxShadow:"0 7px 22px rgba(40,55,42,.05)"}}><div style={{display:"flex",alignItems:"flex-start",gap:13}}><div style={{width:45,height:45,borderRadius:"50%",background:"#E7D7CF",display:"grid",placeItems:"center",color:ROSE,border:"1px solid #DEC8BF",flexShrink:0}}><Heart size={19} fill="currentColor"/></div><div><div style={{fontSize:11,fontWeight:600,letterSpacing:".07em",color:SAGE,marginBottom:4}}>{t("PEACED 作者","BY THE CREATOR OF PEACED")}</div><div style={{fontSize:18,fontWeight:600}}>{t("小红书｜杨园街首席分析师","Xiaohongshu · 杨园街首席分析师")}</div><p style={{fontSize:13,color:MUTE,lineHeight:1.65,margin:"7px 0 13px"}}>{t("配方拆解、产品点评和不绕弯的护肤判断","Formula breakdowns, product reviews, and straight skincare analysis")}</p><a href={XIAOHONGSHU_PROFILE_URL} target="_blank" rel="noopener noreferrer" style={{display:"inline-flex",alignItems:"center",gap:7,borderRadius:999,padding:"9px 13px",background:ROSE,color:"#fff",fontSize:13,fontWeight:600,textDecoration:"none"}}>{t("去小红书关注我","Follow me on Xiaohongshu")}<ExternalLink size={14}/></a></div></div></section>
  </>:<>
   <section style={{padding:"19px 17px",borderRadius:25,background:"linear-gradient(145deg,#2B523B,#234631)",color:"#FFF9EC",marginBottom:17,position:"relative",overflow:"hidden"}}><div style={{position:"absolute",right:-8,top:-16,opacity:.28}}><SketchSprig size={92}/></div><div style={{fontSize:10.5,fontWeight:700,letterSpacing:".1em",color:"#E3C65A",marginBottom:7}}>{t("你的护肤主页","YOUR SKINCARE HOME")}</div><h1 style={{fontSize:27,lineHeight:1.25,letterSpacing:"-.025em",margin:"0 0 8px",fontWeight:600}}>{t("今天想从哪里开始？","What does your skin need today?")}</h1><p style={{fontSize:13.5,lineHeight:1.65,color:"#E8E5D8",margin:0,maxWidth:390}}>{t("你的肤质档案已经连接产品匹配、成分判断和早晚 Routine。","Your profile now connects product matching, ingredient checks, and your AM/PM routine.")}</p></section>
   <div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:9,marginBottom:12}}><CoreCard compact icon={<UserRound size={16}/>} eyebrow="MY SKIN" title={t("我的肤质","My Skin")} body={t("状态与建议","Profile & guidance")} onClick={()=>goTo("mySkin")}/><CoreCard compact icon={<Sparkles size={16}/>} eyebrow="DISCOVER" title={t("发现产品","Discover")} body={t("推荐、搜索、分类","Matches & search")} onClick={()=>goTo("recommend")}/><CoreCard compact icon={<WandSparkles size={16}/>} eyebrow="ROUTINE" title={t("早晚护肤","Routine")} body={t("组合与步骤","AM / PM plan")} onClick={()=>goTo("routine")}/><CoreCard compact icon={<FlaskConical size={16}/>} eyebrow="CHECK" title={t("查产品","Check")} body={t("成分与配方判断","Formula check")} onClick={()=>goTo("upload")}/></div>
   <div style={{marginBottom:22}}><NiumaEntry compact t={t}/></div>
   {luckySection}

   <SkincareKnowledgeCards/>
   <BlogEntry/>
  </>}
 </div>;
}
