import React,{useMemo,useRef,useState}from"react";
import{ArrowLeft,Camera,ChevronDown,ChevronUp,Image,Search,ScanText}from"lucide-react";
import type{SkinProfileRecord}from"../lib/skinProfile";
import{summarizeSkinProfile}from"../lib/skinProfile";
import{useLanguage}from"../lib/i18n";
import{displaySkinLabel}from"../lib/displayI18n";

const INK="#211F1B",PAPER="#F7F3EC",LINE="#DDD6CA",SAGE="#718276",ROSE="#C9958F",MUTE="#777065",CARD="#FFF9ED";
type IngredientRule={name:string;aliases:string[];family?:string;kind?:"cosmetic"|"drug";functionZh:string;functionEn:string;goodFor?:string[];cautionFor?:string[];strongCautionFor?:string[]};

const RULES:IngredientRule[]=[
{name:"Niacinamide / 烟酰胺",aliases:["niacinamide","nicotinamide","烟酰胺"],family:"brightening",functionZh:"帮助屏障、控油，并可辅助改善色沉。",functionEn:"Supports the barrier and oil control, and may help with uneven pigmentation.",goodFor:["barrier","oily","acne","pigmentation","pores"]},
{name:"Glycerin / 甘油",aliases:["glycerin","glycerol","甘油"],family:"humectant",functionZh:"经典吸湿保湿剂，通常耐受性较好。",functionEn:"A classic humectant that is generally well tolerated.",goodFor:["barrier","dry","sensitive","dehydrated"]},
{name:"Panthenol / 泛醇",aliases:["panthenol","provitamin b5","维生素原b5","泛醇"],family:"soothing",functionZh:"保湿并支持屏障修护，常用于舒缓配方。",functionEn:"Hydrates and supports barrier recovery; often used in soothing formulas.",goodFor:["barrier","sensitive","redness","dry"]},
{name:"Ceramide / 神经酰胺",aliases:["ceramide","ceramide np","ceramide ap","ceramide eop","神经酰胺"],family:"barrier lipid",functionZh:"补充皮肤屏障脂质，适合干燥和屏障脆弱状态。",functionEn:"Replenishes barrier lipids and is useful for dry or barrier-compromised skin.",goodFor:["barrier","dry","sensitive"]},
{name:"Squalane / 角鲨烷",aliases:["squalane","角鲨烷"],family:"emollient",functionZh:"轻度封闭与润肤，帮助减少水分流失。",functionEn:"An emollient with light occlusive properties that helps reduce water loss.",goodFor:["barrier","dry","sensitive"]},
{name:"Hyaluronic Acid / 透明质酸",aliases:["hyaluronic acid","sodium hyaluronate","玻尿酸","透明质酸","透明质酸钠"],family:"humectant",functionZh:"吸湿保湿，主要帮助补水和改善紧绷感。",functionEn:"A humectant mainly used to improve hydration and tightness.",goodFor:["dry","dehydrated","barrier"]},
{name:"Centella / 积雪草",aliases:["centella asiatica","madecassoside","asiaticoside","积雪草","羟基积雪草苷","羟基积雪草甙"],family:"soothing",functionZh:"常用于舒缓和屏障支持。",functionEn:"Commonly used for soothing and barrier support.",goodFor:["sensitive","redness","barrier"]},
{name:"Azelaic Acid / 壬二酸",aliases:["azelaic acid","壬二酸","杜鹃花酸"],family:"acne active",functionZh:"兼具抗炎、角质调节和色沉改善潜力。",functionEn:"Has anti-inflammatory, keratinization-regulating and pigmentation-support potential.",goodFor:["acne","redness","pigmentation"],cautionFor:["verySensitive"]},
{name:"Salicylic Acid / 水杨酸",aliases:["salicylic acid","bha","beta hydroxy acid","水杨酸"],family:"exfoliant",functionZh:"亲脂性角质调节成分，更适合黑头、油脂和粉刺问题。",functionEn:"A lipophilic exfoliant useful for blackheads, excess oil and clogged pores.",goodFor:["acne","oily","pores"],cautionFor:["sensitive","barrier","dry"],strongCautionFor:["verySensitive"]},
{name:"Glycolic Acid / 甘醇酸",aliases:["glycolic acid","aha","甘醇酸","乙醇酸"],family:"exfoliant",functionZh:"AHA 焕肤成分，可改善粗糙和暗沉，但刺激潜力较高。",functionEn:"An AHA that can improve roughness and dullness but has higher irritation potential.",goodFor:["dullness","pigmentation"],cautionFor:["sensitive","barrier","dry"],strongCautionFor:["verySensitive","redness"]},
{name:"Lactic Acid / 乳酸",aliases:["lactic acid","aha","乳酸"],family:"exfoliant",functionZh:"相对温和的 AHA，兼具一定保湿属性。",functionEn:"A relatively gentle AHA with some humectant properties.",goodFor:["dullness","dry"],cautionFor:["sensitive","barrier"]},
{name:"Retinol / 视黄醇",aliases:["retinol","vitamin a1","视黄醇","维a醇","维a醇类"],family:"retinoid",kind:"cosmetic",functionZh:"经典维A类护肤活性，用于抗老与痤疮辅助；需要逐步建立耐受。",functionEn:"A classic cosmetic retinoid used for aging and acne support; gradual tolerance building matters.",goodFor:["aging","acne"],cautionFor:["sensitive","barrier","redness","dry"],strongCautionFor:["verySensitive","pregnancy"]},
{name:"Retinal / 视黄醛",aliases:["retinal","retinaldehyde","视黄醛","维a醛"],family:"retinoid",kind:"cosmetic",functionZh:"维A醇下游的护肤活性，通常比维A醇更直接，也更需要关注耐受。",functionEn:"A cosmetic retinoid downstream of retinol; often more direct and more tolerance-dependent.",goodFor:["aging","acne"],cautionFor:["sensitive","barrier","redness","dry"],strongCautionFor:["verySensitive","pregnancy"]},
{name:"Tretinoin / 维A酸",aliases:["tretinoin","retinoic acid","all-trans retinoic acid","all trans retinoic acid","atra","维a酸","维A酸","全反式维a酸","全反式维A酸"],family:"retinoid",kind:"drug",functionZh:"处方级外用维A酸，可用于痤疮和光老化；刺激性和用药要求都明显高于普通护肤维A类。",functionEn:"A prescription topical retinoid used for acne and photoaging; irritation and medication requirements are meaningfully higher than cosmetic retinoids.",goodFor:["aging","acne"],cautionFor:["sensitive","barrier","redness","dry"],strongCautionFor:["verySensitive","pregnancy"]},
{name:"Adapalene / 阿达帕林",aliases:["adapalene","阿达帕林","达芙文"],family:"retinoid",kind:"drug",functionZh:"药用维A酸类，常用于粉刺和痤疮治疗；需要按药品说明或医生建议使用。",functionEn:"A medicinal retinoid commonly used for comedonal acne; use should follow medication guidance or clinician advice.",goodFor:["acne"],cautionFor:["sensitive","barrier","redness","dry"],strongCautionFor:["verySensitive","pregnancy"]},
{name:"Isotretinoin / 异维A酸",aliases:["isotretinoin","13-cis retinoic acid","异维a酸","异维A酸"],family:"retinoid",kind:"drug",functionZh:"主要作为处方药用于重度痤疮，尤其口服制剂具有明确系统性风险，不属于普通护肤成分。",functionEn:"A prescription retinoid mainly used for severe acne; oral formulations carry important systemic risks and are not ordinary skincare ingredients.",goodFor:["acne"],strongCautionFor:["pregnancy"]},
{name:"Retinyl Palmitate / 视黄醇棕榈酸酯",aliases:["retinyl palmitate","vitamin a palmitate","视黄醇棕榈酸酯","棕榈酸视黄酯"],family:"retinoid",kind:"cosmetic",functionZh:"较温和的维A酯类，通常转化链更长、活性更弱。",functionEn:"A gentler retinyl ester with a longer conversion pathway and generally lower activity.",goodFor:["aging"],cautionFor:["verySensitive"],strongCautionFor:["pregnancy"]},
{name:"Vitamin C / 维生素C",aliases:["ascorbic acid","l-ascorbic acid","3-o-ethyl ascorbic acid","ascorbyl glucoside","维生素c","维c","抗坏血酸"],family:"brightening",functionZh:"抗氧化并帮助提亮、改善色沉。",functionEn:"Provides antioxidant support and may help brighten uneven pigmentation.",goodFor:["pigmentation","dullness","aging"],cautionFor:["verySensitive"]},
{name:"Tranexamic Acid / 传明酸",aliases:["tranexamic acid","传明酸","氨甲环酸"],family:"brightening",functionZh:"主要用于色沉和肤色不均方向。",functionEn:"Primarily used for pigmentation and uneven skin tone.",goodFor:["pigmentation","dullness"]},
{name:"Alpha-Arbutin / α-熊果苷",aliases:["alpha-arbutin","alpha arbutin","arbutin","熊果苷","α-熊果苷","阿尔法熊果苷"],family:"brightening",functionZh:"常用于淡斑和色沉管理。",functionEn:"Commonly used to support dark-spot and pigmentation management.",goodFor:["pigmentation","dullness"]},
{name:"Peptides / 胜肽",aliases:["peptide","peptides","palmitoyl tripeptide","palmitoyl tetrapeptide","acetyl hexapeptide","胜肽","多肽"],family:"anti-aging",functionZh:"偏抗老和修护方向，通常刺激性较低。",functionEn:"Typically positioned for anti-aging and repair with relatively low irritation potential.",goodFor:["aging","barrier"]},
{name:"Alcohol Denat. / 变性酒精",aliases:["alcohol denat","alcohol denat.","sd alcohol","ethanol","变性酒精","乙醇"],family:"solvent",functionZh:"可改善清爽感和渗透感；高位出现时对部分敏感或屏障脆弱肤质可能偏刺激。",functionEn:"Can improve a light skin feel; when high in the list it may irritate some sensitive or barrier-compromised skin.",cautionFor:["sensitive","barrier","redness","dry"],strongCautionFor:["verySensitive"]},
{name:"Fragrance / 香精",aliases:["fragrance","parfum","perfume","香精","香料"],family:"fragrance",functionZh:"主要提供气味体验，不是功效成分；敏感人群可减少不必要暴露。",functionEn:"Primarily provides scent rather than skincare benefit; sensitive users may prefer less exposure.",cautionFor:["sensitive","redness","barrier"],strongCautionFor:["verySensitive"]},
{name:"Essential Oils / 精油",aliases:["lavender oil","peppermint oil","citrus peel oil","tea tree oil","essential oil","精油"],family:"fragrance",functionZh:"部分精油有感官或辅助作用，但也可能增加刺激负担。",functionEn:"Some essential oils have sensory or supportive roles but may increase irritation burden.",cautionFor:["sensitive","redness","barrier"],strongCautionFor:["verySensitive"]},
{name:"Petrolatum / 凡士林",aliases:["petrolatum","petroleum jelly","凡士林"],family:"occlusive",functionZh:"强封闭型润肤剂，帮助减少经皮水分流失。",functionEn:"A strongly occlusive emollient that helps reduce transepidermal water loss.",goodFor:["dry","barrier"],cautionFor:["oily"]},
{name:"Benzoyl Peroxide / 过氧化苯甲酰",aliases:["benzoyl peroxide","bpo","过氧化苯甲酰"],family:"acne active",kind:"drug",functionZh:"痤疮常用抗菌活性，效果明确但也容易干燥刺激。",functionEn:"A well-established antimicrobial acne active that can also be drying and irritating.",goodFor:["acne"],cautionFor:["dry","sensitive","barrier"],strongCautionFor:["verySensitive"]}
];

function normalize(text:string){return text.trim().toLowerCase().replace(/[·•_,，。()（）\-\/]+/g," ").replace(/\s+/g," ")}
function profileSignals(profile:SkinProfileRecord|null){const s=new Set<string>(),a=profile?.skinAnswers||{},y=profile?.selectedSymptoms||[];if(a.wash==="dry"||a.oil==="dry")s.add("dry");if(a.wash==="oily"||a.oil==="oily")s.add("oily");if(a.sensitive==="yes"){s.add("sensitive");s.add("verySensitive")}if(y.includes("redness")||y.includes("sensitivity"))s.add("redness");for(const k of ["acne","pores","pigmentation","aging"])if(y.includes(k))s.add(k);if(y.includes("dryness"))s.add("dehydrated");if(a.sensitive==="yes"||y.includes("redness"))s.add("barrier");if(profile?.profileAnswers?.pregnancy==="yes")s.add("pregnancy");return s}
function findRule(text:string){const q=normalize(text);if(!q)return null;return RULES.find(r=>[r.name,...r.aliases].some(a=>{const n=normalize(a);return n===q||n.includes(q)||q.includes(n)}))||null}
function scoreSuggestion(rule:IngredientRule,q:string){const nq=normalize(q);if(!nq)return 0;const terms=[rule.name,...rule.aliases].map(normalize);let score=0;for(const term of terms){if(term===nq)score=Math.max(score,100);else if(term.startsWith(nq)||nq.startsWith(term))score=Math.max(score,80);else if(term.includes(nq)||nq.includes(term))score=Math.max(score,65);else{const qTokens=nq.split(" "),tTokens=term.split(" "),overlap=qTokens.filter(x=>tTokens.some(y=>y.includes(x)||x.includes(y))).length;score=Math.max(score,overlap*18)}}if(rule.family==="retinoid"&&/(维.?a|视黄|retin|tret|adapal|isotret)/i.test(q))score+=28;if(rule.family==="exfoliant"&&/(酸|aha|bha|exfol)/i.test(q))score+=10;return score}
function suggestionsFor(text:string,selected:IngredientRule|null){if(!text.trim())return[];const family=selected?.family;return RULES.map(r=>({rule:r,score:scoreSuggestion(r,text)+(family&&r.family===family?25:0)})).filter(x=>x.rule!==selected&&x.score>12).sort((a,b)=>b.score-a.score).slice(0,5).map(x=>x.rule)}
const starsText=(n:number)=>`${"★".repeat(n)}${"☆".repeat(5-n)}`;

export default function V3IngredientCheck({profile,onBack}:{profile:SkinProfileRecord|null;onBack:()=>void}){
 const{t,language}=useLanguage();
 const[query,setQuery]=useState(""),[ocrText,setOcrText]=useState(""),[ocrStatus,setOcrStatus]=useState<"idle"|"reading"|"done"|"error">("idle"),[ocrProgress,setOcrProgress]=useState(0),[preview,setPreview]=useState(""),[ocrOpen,setOcrOpen]=useState(false);
 const cameraRef=useRef<HTMLInputElement>(null),albumRef=useRef<HTMLInputElement>(null),summary=summarizeSkinProfile(profile);
 const selected=useMemo(()=>findRule(query),[query]);
 const suggestions=useMemo(()=>suggestionsFor(query,selected),[query,selected]);
 const ocrRules=useMemo(()=>{const text=normalize(ocrText);return RULES.filter(r=>r.aliases.some(a=>text.includes(normalize(a)))).slice(0,20)},[ocrText]);
 function rate(rule:IngredientRule){const s=profileSignals(profile),g=(rule.goodFor||[]).filter(x=>s.has(x)),c=(rule.cautionFor||[]).filter(x=>s.has(x)),h=(rule.strongCautionFor||[]).filter(x=>s.has(x));if(h.length)return{stars:1,label:t("不建议优先使用","Not a priority"),detail:t("与你当前档案存在较明显冲突或刺激风险。","There is a meaningful mismatch or irritation risk for your current profile."),tone:"risk" as const};if(c.length&&!g.length)return{stars:2,label:t("谨慎尝试","Use with caution"),detail:t("存在一定不匹配或潜在刺激风险，建议先局部试用。","There is some mismatch or irritation potential; patch testing is advisable."),tone:"risk" as const};if(g.length>=2&&!c.length)return{stars:5,label:t("非常适合","Excellent match"),detail:t("这个成分同时匹配你当前多个主要需求。","This ingredient aligns with several of your current priorities."),tone:"good" as const};if(g.length&&!c.length)return{stars:4,label:t("适合","Good match"),detail:t("与当前至少一个主要肤质或需求方向一致。","It aligns with at least one major skin need in your profile."),tone:"good" as const};if(g.length&&c.length)return{stars:3,label:t("可以用","Suitable"),detail:t("既有潜在帮助，也有需要结合浓度和耐受权衡的地方。","It may help, but concentration and tolerance still matter."),tone:"neutral" as const};return{stars:3,label:t("可以用","Suitable"),detail:t("目前没有发现与你档案的明显冲突，但它也不是当前最核心的需求。","No clear conflict is identified, though it is not a core priority for you."),tone:"neutral" as const}}
 const rating=selected?rate(selected):null;
 const profileLine=profile?`${displaySkinLabel(summary.skinType,language)} · ${displaySkinLabel(summary.sensitivity,language)}${summary.concerns.length?` · ${summary.concerns.map(x=>displaySkinLabel(x,language)).join(" / ")}`:""}`:"";
 async function readImage(file?:File){if(!file)return;setOcrStatus("reading");setOcrProgress(0);const reader=new FileReader();reader.onload=()=>setPreview(String(reader.result||""));reader.readAsDataURL(file);try{const{createWorker}=await import("tesseract.js");const worker=await createWorker("chi_sim+eng",1,{logger:m=>{if(m.status==="recognizing text")setOcrProgress(Math.round((m.progress||0)*100))}});const result=await worker.recognize(file);await worker.terminate();setOcrText(result.data.text.trim());setOcrStatus("done")}catch{setOcrStatus("error")}}
 return <div style={{minHeight:"100vh",background:PAPER,color:INK,padding:"22px 16px 54px"}}><div style={{maxWidth:620,margin:"0 auto"}}>
  <button onClick={onBack} style={back}><ArrowLeft size={14}/>{t("返回","Back")}</button>
  <div style={{color:SAGE,fontSize:10,letterSpacing:".08em",marginBottom:7}}>INGREDIENT MATCH</div>
  <h1 style={{fontSize:34,fontWeight:650,lineHeight:1.08,margin:"0 0 10px"}}>{t("查一个成分，看它适不适合你","Search an ingredient and see if it fits you")}</h1>
  <p style={{fontSize:14,color:MUTE,lineHeight:1.7,margin:"0 0 18px"}}>{t("支持中文名、英文名和常见别名。查不到时会给你相近成分，而不是直接空白。","Search Chinese, English or common aliases. If there is no exact match, we show nearby ingredients instead of a dead end.")}</p>
  {profileLine&&<div style={{fontSize:12,color:SAGE,marginBottom:14}}>{t("按你的档案判断：","Based on your profile: ")}{profileLine}</div>}
  <div style={{position:"relative",marginBottom:12}}><Search size={17} color={SAGE} style={{position:"absolute",left:14,top:16}}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t("例如：维A酸 / tretinoin / 烟酰胺","e.g. 维A酸 / tretinoin / niacinamide")} style={input}/></div>
  {selected&&rating&&<section style={card}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"flex-start"}}><div><div style={{fontSize:19,fontWeight:700,color:SAGE}}>{selected.name}</div>{selected.kind==="drug"&&<div style={{fontSize:11,color:ROSE,fontWeight:700,marginTop:5}}>{t("药用 / 处方级活性","Medicinal / prescription-level active")}</div>}</div><div style={{fontSize:13,color:rating.tone==="risk"?ROSE:SAGE,fontWeight:700,whiteSpace:"nowrap"}}>{starsText(rating.stars)} · {rating.label}</div></div><p style={{fontSize:14,lineHeight:1.7,color:MUTE,margin:"14px 0 7px"}}>{language==="zh"?selected.functionZh:selected.functionEn}</p><p style={{fontSize:13,lineHeight:1.65,color:MUTE,margin:0}}>{rating.detail}</p></section>}
  {query.trim()&&suggestions.length>0&&<section style={{marginTop:14}}><div style={{fontSize:13,fontWeight:700,color:SAGE,marginBottom:8}}>{selected?t("同类 / 相近成分","Related ingredients"):t("你可能想找","You may mean")}</div><div style={{display:"grid",gap:8}}>{suggestions.map(r=><button key={r.name} onClick={()=>setQuery(r.aliases[0]||r.name)} style={suggestionButton}><div style={{fontWeight:650}}>{r.name}</div><div style={{fontSize:11,color:MUTE,marginTop:4}}>{r.family||t("相关成分","Related")}{r.kind==="drug"?` · ${t("药用","Medicinal")}`:""}</div></button>)}</div></section>}
  {query.trim()&&!selected&&suggestions.length===0&&<div style={{...card,marginTop:12}}><div style={{fontWeight:700,color:SAGE,marginBottom:6}}>{t("暂时没有精确收录","No exact entry yet")}</div><div style={{fontSize:13,color:MUTE,lineHeight:1.65}}>{t("可以换用英文 INCI、缩短关键词，或使用下方的图片识别 Beta。这个缺口后续应该进入成分词典补全，而不是让搜索直接结束。","Try the English INCI name, shorten the keyword, or use the image-recognition Beta below. This gap should feed the ingredient dictionary instead of ending the search.")}</div></div>}
  <div style={{marginTop:24,borderTop:`1px solid ${LINE}`,paddingTop:14}}><button onClick={()=>setOcrOpen(x=>!x)} style={ocrToggle}><span style={{display:"flex",gap:8,alignItems:"center"}}><ScanText size={15}/>{t("拍照识别 Beta","Image recognition Beta")}</span>{ocrOpen?<ChevronUp size={15}/>:<ChevronDown size={15}/>}</button>{ocrOpen&&<div style={{marginTop:10,padding:14,border:`1px solid ${LINE}`,borderRadius:16,background:CARD}}><div style={{fontSize:12,color:MUTE,lineHeight:1.6,marginBottom:10}}>{t("只作为辅助：弧形瓶身、反光和小字会明显降低识别率。优先搜索文字；识别结果也需要你确认。","Auxiliary only: curved packaging, glare and small text reduce accuracy. Text search is preferred, and OCR results should be reviewed.")}</div><input ref={cameraRef} type="file" accept="image/*" capture="environment" onChange={e=>readImage(e.target.files?.[0])} style={{display:"none"}}/><input ref={albumRef} type="file" accept="image/*" onChange={e=>readImage(e.target.files?.[0])} style={{display:"none"}}/><div style={{display:"flex",gap:8}}><button onClick={()=>cameraRef.current?.click()} style={smallButton}><Camera size={14}/>{t("拍照","Photo")}</button><button onClick={()=>albumRef.current?.click()} style={smallButton}><Image size={14}/>{t("相册","Album")}</button></div>{ocrStatus==="reading"&&<div style={{fontSize:12,color:SAGE,marginTop:10}}>{t("识别中","Reading")} {ocrProgress}%</div>}{ocrStatus==="error"&&<div style={{fontSize:12,color:ROSE,marginTop:10}}>{t("这张图没有可靠识别出来。建议直接搜索或粘贴成分名。","No reliable result from this image. Search or paste the ingredient name instead.")}</div>}{preview&&<img src={preview} alt="preview" style={{width:"100%",maxHeight:180,objectFit:"contain",marginTop:10,borderRadius:12}}/>}{ocrStatus==="done"&&<><textarea value={ocrText} onChange={e=>setOcrText(e.target.value)} style={textarea} placeholder={t("识别文字，可在这里校对","Recognized text — review here")}/>{ocrRules.length>0?<div style={{display:"flex",flexWrap:"wrap",gap:6,marginTop:8}}>{ocrRules.map(r=><button key={r.name} onClick={()=>{setQuery(r.aliases[0]||r.name);setOcrOpen(false)}} style={chip}>{r.name}</button>)}</div>:<div style={{fontSize:12,color:MUTE,marginTop:8}}>{t("没有从图片中可靠匹配到已收录成分。","No reliable ingredient match was found in the image.")}</div>}</>}</div>}</div>
 </div></div>
}

const back:React.CSSProperties={border:0,background:"transparent",padding:0,color:MUTE,fontSize:12,cursor:"pointer",marginBottom:22,display:"flex",gap:6,alignItems:"center"};
const input:React.CSSProperties={width:"100%",boxSizing:"border-box",border:`1px solid ${LINE}`,borderRadius:16,padding:"14px 14px 14px 42px",background:CARD,fontSize:15,color:INK,outline:"none"};
const card:React.CSSProperties={border:`1px solid ${LINE}`,borderRadius:18,padding:16,background:CARD,boxShadow:"0 6px 18px rgba(40,55,42,.04)"};
const suggestionButton:React.CSSProperties={width:"100%",textAlign:"left",border:`1px solid ${LINE}`,borderRadius:14,padding:"11px 13px",background:CARD,color:INK,cursor:"pointer"};
const ocrToggle:React.CSSProperties={width:"100%",border:0,background:"transparent",padding:"8px 0",color:SAGE,fontSize:13,fontWeight:650,cursor:"pointer",display:"flex",justifyContent:"space-between",alignItems:"center"};
const smallButton:React.CSSProperties={border:`1px solid ${LINE}`,borderRadius:12,padding:"9px 11px",background:"#fff",color:SAGE,fontSize:12,fontWeight:650,cursor:"pointer",display:"flex",gap:6,alignItems:"center"};
const textarea:React.CSSProperties={width:"100%",boxSizing:"border-box",minHeight:90,border:`1px solid ${LINE}`,borderRadius:12,padding:10,background:"#fff",fontSize:12,color:INK,marginTop:10};
const chip:React.CSSProperties={border:`1px solid ${LINE}`,borderRadius:999,padding:"6px 9px",background:"#fff",color:SAGE,fontSize:11,cursor:"pointer"};