import React from "react";
import { ArrowLeft, ChevronRight, FlaskConical, ListChecks, Search, Sparkles } from "lucide-react";
import type { SkinProfileRecord } from "../lib/skinProfile";
import { summarizeSkinProfile } from "../lib/skinProfile";
const INK="#252724",BG="#F6F4EF",CARD="#FCFBF8",LINE="#DEDCD5",SAGE="#667A6C",MUTE="#777870";
const sans="-apple-system, BlinkMacSystemFont, 'Segoe UI', 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', sans-serif";
function Chip({children}:{children:React.ReactNode}){return <span style={{display:"inline-flex",border:`1px solid ${LINE}`,borderRadius:999,padding:"7px 10px",background:BG,fontSize:12,color:INK}}>{children}</span>}
function Action({icon,title,body,onClick}:{icon:React.ReactNode;title:string;body:string;onClick:()=>void}){return <button onClick={onClick} style={{width:"100%",border:`1px solid ${LINE}`,background:CARD,borderRadius:18,padding:"16px",display:"flex",alignItems:"center",justifyContent:"space-between",textAlign:"left",cursor:"pointer",color:INK,fontFamily:sans,marginBottom:10}}><span style={{display:"flex",alignItems:"flex-start",gap:12}}><span style={{width:34,height:34,borderRadius:12,background:"#E9EEE9",display:"grid",placeItems:"center",color:SAGE,flexShrink:0}}>{icon}</span><span><b style={{display:"block",fontSize:14,marginBottom:4}}>{title}</b><span style={{fontSize:12,color:MUTE,lineHeight:1.55}}>{body}</span></span></span><ChevronRight size={16} color={MUTE}/></button>}
export default function V3MySkin({profile,onBack,onRetake,onFindProducts,onBuildRoutine,onOpenLegacyReport}:{profile:SkinProfileRecord|null;onBack:()=>void;onRetake:()=>void;onFindProducts:()=>void;onBuildRoutine:()=>void;onOpenLegacyReport:()=>void;}){const summary=summarizeSkinProfile(profile);return <div style={{minHeight:"100vh",background:BG,color:INK,padding:"22px 18px 52px",fontFamily:sans}}><div style={{maxWidth:560,margin:"0 auto"}}>
<button onClick={onBack} style={{border:0,padding:0,background:"transparent",display:"flex",alignItems:"center",gap:7,color:MUTE,fontSize:13,cursor:"pointer",marginBottom:30,fontFamily:sans}}><ArrowLeft size={15}/> 返回首页</button><div style={{fontSize:11,letterSpacing:".12em",color:SAGE,fontWeight:700,marginBottom:10}}>MY SKIN</div><h1 style={{fontWeight:650,fontSize:32,lineHeight:1.2,letterSpacing:"-.035em",margin:"0 0 10px"}}>我的肤质</h1><p style={{margin:"0 0 26px",color:MUTE,fontSize:14,lineHeight:1.7}}>你的肤质档案、当前需求，以及下一步应该关注的产品和成分。</p>
{!profile?<section style={{border:`1px solid ${LINE}`,background:CARD,borderRadius:20,padding:20}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:8}}><Sparkles size={16} color={SAGE}/><b style={{fontSize:14}}>还没有保存的肤质档案</b></div><p style={{fontSize:13,color:MUTE,lineHeight:1.65,margin:"0 0 15px"}}>先完成肤质分析，之后推荐、成分判断和 Routine 都会使用同一份档案。</p><button onClick={onRetake} style={{border:0,borderRadius:999,padding:"10px 15px",background:SAGE,color:"white",fontSize:13,cursor:"pointer"}}>开始肤质分析</button></section>:<>
<section style={{border:`1px solid ${LINE}`,borderRadius:20,padding:18,background:CARD,marginBottom:12}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14}}><div><div style={{fontSize:10.5,color:MUTE,marginBottom:5}}>肤质类型</div><div style={{fontSize:20,fontWeight:650}}>{summary.skinType}</div></div><div><div style={{fontSize:10.5,color:MUTE,marginBottom:5}}>敏感程度</div><div style={{fontSize:20,fontWeight:650}}>{summary.sensitivity}</div></div></div><div style={{marginTop:17,paddingTop:15,borderTop:`1px solid ${LINE}`}}><div style={{fontSize:11,color:MUTE,marginBottom:9}}>当前关注</div><div style={{display:"flex",gap:7,flexWrap:"wrap"}}>{summary.concerns.length?summary.concerns.map(item=><Chip key={item}>{item}</Chip>):<span style={{fontSize:12,color:MUTE}}>暂未记录主要问题</span>}</div></div></section>
<div style={{fontSize:11,letterSpacing:".1em",color:MUTE,fontWeight:700,margin:"26px 0 10px"}}>下一步</div><Action icon={<FlaskConical size={16}/>} title="看成分方向" body="了解应该优先找什么，以及哪些需要谨慎。" onClick={onOpenLegacyReport}/><Action icon={<Search size={16}/>} title="查看为我排序的产品" body="按同一套五星匹配规则浏览产品。" onClick={onFindProducts}/><Action icon={<ListChecks size={16}/>} title="建立早晚 Routine" body="把适合你的产品组合成清晰步骤。" onClick={onBuildRoutine}/><button onClick={onRetake} style={{width:"100%",border:0,background:"transparent",color:MUTE,padding:12,fontSize:12,cursor:"pointer",fontFamily:sans}}>重新分析并更新档案</button>{profile.updatedAt&&<div style={{marginTop:10,textAlign:"center",fontSize:10.5,color:MUTE}}>更新于 {new Date(profile.updatedAt).toLocaleDateString()}</div>}
</>}</div></div>}
