import React,{useEffect,useMemo,useState}from"react";
import{ArrowLeft,ExternalLink}from"lucide-react";
import{analyzeFormulaDna,FORMULA_SYSTEM_ORDER,type FormulaSystemKey}from"../intelligence/formulaDna";
import{approximatePriceGuide,getBrandProfile,priceTierForBrand}from"../data/brandProfiles";
import{loadProductDetail,loadPublicProductExperiences,savePublicProductExperience,type ProductDetailRecord,type PublicProductExperience,type SharedProductRecord}from"../lib/supabase";
import{summarizeSkinProfile,type SkinProfileRecord}from"../lib/skinProfile";
import{marketingReality,personalizedScore,rankForProfile,type BrowseConcern}from"../lib/productPresentation";
import{loadProductExperience,saveProductExperience,type ProductReaction}from"../lib/productFeedback";
import{consumerAliases}from"../lib/productNames";
import{useLanguage}from"../lib/i18n";
import BilingualIngredientList from"./BilingualIngredientList";
import ProductReadingLinks from './ProductReadingLinks';
import{SketchPageAccent,SketchUnderline}from"./HandDrawnVisuals";
import FormulaRadar from"./FormulaRadar";

const INK="#211F1B",PAPER="#F7F3EC",LINE="#DDD6CA",SAGE="#718276",ROSE="#C9958F",MUTE="#777065";
const HAS_CJK=/[\u3400-\u9fff]/;
const SYSTEM_COPY:Record<FormulaSystemKey,[string,string]>={barrier:["屏障修护","Barrier support"],hydration:["补水保湿","Hydration"],soothing:["舒缓维稳","Soothing"],antiAging:["抗老紧致","Anti-aging"],oilControl:["控油净肤","Oil control"],lipid:["脂质滋润","Lipid replenishment"],preservation:["防腐体系","Preservation"]};
const COUNTRY_EN:Record<string,string>={中国:"China",日本:"Japan",韩国:"South Korea",法国:"France",德国:"Germany",瑞士:"Switzerland",美国:"United States",加拿大:"Canada",英国:"United Kingdom",澳大利亚:"Australia",西班牙:"Spain",意大利:"Italy"};
function Badge({children,tone="neutral"}:{children:React.ReactNode;tone?:"neutral"|"sage"|"rose"}){const colors=tone==="sage"?["#EDF1EA",SAGE]:tone==="rose"?["#F6ECE8","#8E665F"]:["white",MUTE];return <span style={{display:"inline-flex",maxWidth:"100%",boxSizing:"border-box",overflowWrap:"anywhere",border:`1px solid ${tone==="neutral"?LINE:colors[1]}`,borderRadius:999,padding:"5px 8px",background:colors[0],color:colors[1],fontSize:10.5}}>{children}</span>}
function categoryCopy(raw:string,language:"zh"|"en"){const v=(raw||"").toLowerCase();if(/serum|ampoule|精华/.test(v))return language==="zh"?"精华":"Serum";if(/moist|cream|lotion|乳液|面霜/.test(v))return language==="zh"?"面霜 / 乳液":"Moisturizer";if(/toner|essence|化妆水|爽肤/.test(v))return language==="zh"?"化妆水 / 精华水":"Toner / Essence";if(/clean|洁面/.test(v))return language==="zh"?"洁面":"Cleanser";if(/sun|spf|防晒/.test(v))return language==="zh"?"防晒":"Sunscreen";if(/mask|面膜/.test(v))return language==="zh"?"面膜":"Mask";if(/eye|眼/.test(v))return language==="zh"?"眼部护理":"Eye care";return language==="zh"?(raw||"护肤品"):"Skincare"}
function audienceFromDna(dna:ReturnType<typeof analyzeFormulaDna>,language:"zh"|"en"){const best:string[]=[];if(dna.systems.hydration.score>=2)best.push(language==="zh"?"缺水肌":"Dehydrated skin");if(dna.systems.barrier.score>=2||dna.systems.lipid.score>=2)best.push(language==="zh"?"偏干或屏障脆弱肌":"Dry or barrier-impaired skin");if(dna.systems.soothing.score>=2)best.push(language==="zh"?"易泛红或容易受刺激的肌肤":"Redness-prone or easily irritated skin");if(dna.systems.antiAging.score>=3)best.push(language==="zh"?"有初老或细纹需求的肌肤":"Skin with early aging or fine-line concerns");if(dna.systems.oilControl.score>=3)best.push(language==="zh"?"偏油或在意毛孔的肌肤":"Oily skin or visible-pore concerns");if(!best.length)best.push(language==="zh"?"希望进行基础日常护理的人":"Straightforward daily-care routines");return best.slice(0,5)}
function safeEditorial(items:string[]|undefined,language:"zh"|"en"){return(items||[]).map(x=>x.trim()).filter(Boolean).filter(x=>language==="zh"?HAS_CJK.test(x):!HAS_CJK.test(x))}
function ratingCopy(stars:number,language:"zh"|"en"){const zh=["数据不足","不推荐","谨慎尝试","可以用","适合","非常适合"],en=["Insufficient data","Not recommended","Use with caution","Suitable","Good match","Excellent match"];const detailsZh=["现有配方证据不足，暂不强行判断。","与当前肤质或需求存在明显冲突。","存在一定不匹配或潜在刺激风险。","没有明显不适配，但未必是当前最优选择。","整体匹配良好。","与你当前的肤质和需求高度匹配。"],detailsEn=["There is not enough formula evidence to force a rating.","There are clear conflicts with your current skin profile or goals.","There is some mismatch or potential irritation risk.","No major mismatch, though it may not be your best current option.","Overall fit is good.","The formula aligns very well with your current skin profile and goals."];return{label:(language==="zh"?zh:en)[stars],detail:(language==="zh"?detailsZh:detailsEn)[stars]}}
function formulaCopy(p:SharedProductRecord,language:"zh"|"en"){if(p.ingredientListType==="full"&&p.dataCompleteness>=85)return language==="zh"?{label:"完整配方已核验",detail:"完整 INCI 已保存，可进行完整配方结构分析。",tone:"good"}:{label:"Full formula verified",detail:"The complete INCI is stored and can support full formula-structure analysis.",tone:"good"};if(p.ingredientListType==="full")return language==="zh"?{label:"完整配方 · 待复核",detail:"已保存完整列表，但来源或版本仍需进一步复核。",tone:"warn"}:{label:"Full formula · review pending",detail:"A full list is stored, but the source or version still needs review.",tone:"warn"};if(p.ingredients.length)return language==="zh"?{label:"部分配方",detail:"目前只有部分成分证据，结论会相应保守。",tone:"warn"}:{label:"Partial formula",detail:"Only partial ingredient evidence is available, so conclusions are conservative.",tone:"warn"};return language==="zh"?{label:"配方待补充",detail:"尚无足够 INCI 数据，不进入优先推荐。",tone:"warn"}:{label:"Formula data missing",detail:"There is not enough INCI data for priority recommendations.",tone:"warn"}}
function alcoholCopy(level:string,language:"zh"|"en"){if(language==="zh")return level==="high"?"酒精偏高":level==="medium"?"含一定酒精":"酒精低 / 未见高位酒精";return level==="high"?"Higher alcohol":level==="medium"?"Some alcohol":"Low / no high-position alcohol"}

export default function V3ProductDetail({product,products,profile,concern,onBack,onProduct}:{product:SharedProductRecord;products:SharedProductRecord[];profile:SkinProfileRecord|null;concern?:BrowseConcern;onBack:()=>void;onProduct:(product:SharedProductRecord,concern:BrowseConcern)=>void}){
 const{language,t}=useLanguage();
 const[detail,setDetail]=useState<ProductDetailRecord|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(false);
 const[reaction,setReaction]=useState<ProductReaction>("neutral"),[texture,setTexture]=useState<"love"|"okay"|"dislike">("okay"),[repurchase,setRepurchase]=useState<"yes"|"maybe"|"no">("maybe"),[note,setNote]=useState("");
 const[feedbackStatus,setFeedbackStatus]=useState<"idle"|"saving"|"saved"|"error">("idle"),[feedbackMessage,setFeedbackMessage]=useState(""),[experiences,setExperiences]=useState<PublicProductExperience[]>([]);
 useEffect(()=>{let active=true;setLoading(true);setError(false);loadProductDetail(product.id).then(row=>{if(active)setDetail(row)}).catch(()=>{if(active)setError(true)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[product.id]);
 useEffect(()=>{const x=loadProductExperience(product.id);setReaction(x?.reaction||"neutral");setTexture(x?.texture||"okay");setRepurchase(x?.repurchase||"maybe");setNote(x?.note||"");setFeedbackStatus("idle")},[product.id]);
 useEffect(()=>{let active=true;loadPublicProductExperiences(product.id).then(rows=>{if(active)setExperiences(rows)}).catch(()=>{if(active)setExperiences([])});return()=>{active=false}},[product.id]);
 const current=detail||product,dna=useMemo(()=>analyzeFormulaDna(current),[current]),match=personalizedScore(product,profile,concern),formula=formulaCopy(current,language),reality=marketingReality(current,language,dna),brand=getBrandProfile(product.brand),fullIngredients=detail?.fullIngredients||product.ingredients,profileSummary=summarizeSkinProfile(profile);
 const score=match?.recommendationAvailable&&match.score!=null?match.score:null,stars=score==null?0:score>=85?5:score>=70?4:score>=55?3:score>=35?2:1,rating=ratingCopy(stars,language),bonus=stars>=3&&!!match&&(match.positiveEvidence.length+match.systemEvidence.filter(e=>e.score>=3).length)>=4&&match.negativeEvidence.length===0&&match.formulaPenalty>=0;
 const visibleSystems=FORMULA_SYSTEM_ORDER.map(key=>({key,score:dna.systems[key].score})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);
 const alternatives=useMemo(()=>rankForProfile(products.filter(c=>c.id!==product.id&&c.category===product.category),profile,concern).filter(c=>c.recommendationAvailable),[products,product.id,product.category,profile,concern]);
 const similar=alternatives[0],budgetAlternative=alternatives.find(c=>priceTierForBrand(c.brand)==="budget"),premiumAlternative=alternatives.find(c=>priceTierForBrand(c.brand)==="premium");
 const aliases=consumerAliases(product),localName=product.productLocalName||product.name,englishName=product.productEnglishName||(!HAS_CJK.test(product.name)?product.name:""),displayName=language==="zh"?localName:(englishName||product.brandEnglishName||product.brand),displayBrand=language==="zh"?(product.brandLocalName||product.brand):(product.brandEnglishName||product.brand),displayCountry=language==="zh"?brand.country:(COUNTRY_EN[brand.country]||"International"),displayCategory=categoryCopy(product.category,language);
 const audienceBest=[...safeEditorial(current.editorial?.bestFor,language),...audienceFromDna(dna,language)].filter((x,i,a)=>a.indexOf(x)===i).slice(0,6),audienceNot=safeEditorial(current.editorial?.notIdealFor,language).slice(0,5),audienceCaveats=[...safeEditorial(current.editorial?.caveats,language),...(current.ingredientListType!=="full"?[t("等待完整 INCI 核验","Full INCI verification is still pending")]:[]),...(dna.alcohol.level==="high"?[t("敏感或屏障不稳时需留意高位酒精","Reactive or barrier-impaired skin should note the high-position alcohol")]:[])].filter((x,i,a)=>a.indexOf(x)===i).slice(0,4);
 const reactionLabel={better:t("皮肤有改善","Skin improved"),neutral:t("没有明显变化","No clear change"),irritated:t("出现刺激 / 不适","Irritation / discomfort")},textureLabel={love:t("喜欢肤感","Liked the texture"),okay:t("肤感一般","Texture was okay"),dislike:t("不喜欢肤感","Disliked the texture")},repurchaseLabel={yes:t("会回购","Would repurchase"),maybe:t("可能回购","Might repurchase"),no:t("不会回购","Would not repurchase")};
 async function submitExperience(){if(!profileSummary.isComplete){setFeedbackStatus("error");setFeedbackMessage(t("请先建立肤质档案，这样别人才能理解这条体验来自什么肤质。","Create a skin profile first so other users can understand the context of your experience."));return}setFeedbackStatus("saving");setFeedbackMessage("");try{await savePublicProductExperience({productKey:product.id,skinType:profileSummary.skinType,sensitivity:profileSummary.sensitivity,concerns:profileSummary.concerns,reaction,texture,repurchase,note});saveProductExperience({productId:product.id,reaction,texture,repurchase,note:note.trim()});setExperiences(await loadPublicProductExperiences(product.id));setFeedbackStatus("saved");setFeedbackMessage(t("已匿名公开。别人只会看到肤质标签和使用感。","Published anonymously. Other users only see skin-profile tags and your experience."))}catch(e){setFeedbackStatus("error");setFeedbackMessage(e instanceof Error?e.message:t("暂时无法提交，请稍后重试。","Unable to submit right now. Please try again later."))}}
 const card={width:"100%",minWidth:0,boxSizing:"border-box" as const,border:`1px solid ${LINE}`,borderRadius:17,padding:17,background:"rgba(255,255,255,.68)",marginBottom:12};
 return <div style={{minHeight:"100vh",width:"100%",maxWidth:"100vw",boxSizing:"border-box",background:PAPER,color:INK,padding:"22px 18px 54px",overflowX:"hidden"}}><div style={{width:"100%",maxWidth:620,minWidth:0,boxSizing:"border-box",margin:"0 auto"}}>
  <button onClick={onBack} style={{border:0,background:"transparent",padding:0,color:MUTE,fontSize:12,cursor:"pointer",marginBottom:24,display:"flex",gap:6,alignItems:"center"}}><ArrowLeft size={14}/>{t("返回产品库","Back to products")}</button>
  <div style={{fontSize:10,color:SAGE,letterSpacing:".08em",marginBottom:7}}>{displayBrand} · {displayCountry} · {displayCategory}</div><h1 style={{fontFamily:"'Newsreader', serif",fontSize:34,fontWeight:500,lineHeight:1.08,margin:0,overflowWrap:"anywhere"}}>{displayName}</h1><SketchUnderline width={135}/>{language==="zh"&&englishName&&englishName!==localName?<div style={{fontSize:12,color:MUTE,lineHeight:1.5,marginTop:8}}>{englishName}</div>:null}{aliases.length>0&&<div style={{display:"flex",gap:6,flexWrap:"wrap",margin:"9px 0 4px"}}>{aliases.slice(0,3).map(alias=><Badge key={alias} tone="sage">{t("常用昵称","Nickname")} · {alias}</Badge>)}</div>}
  <p style={{fontFamily:"'Newsreader', serif",fontSize:19,lineHeight:1.45,margin:"14px 0 2px",color:"#49443D"}}>{language==="zh"?`这是一款以${visibleSystems.slice(0,2).map(x=>SYSTEM_COPY[x.key][0]).join(" + ")||"基础护理"}为主的${displayCategory}。`:`This ${displayCategory.toLowerCase()} is primarily structured around ${visibleSystems.slice(0,2).map(x=>SYSTEM_COPY[x.key][1].toLowerCase()).join(" + ")||"basic daily care"}.`}</p><SketchPageAccent kind="formula"/>

  <ProductReadingLinks productId={product.id}/>
  <section style={card}><div style={{fontSize:10,color:SAGE,letterSpacing:".08em",marginBottom:11}}>{t("这款产品本身适合谁","Who this product suits")}</div><div style={{fontSize:11,fontWeight:650,marginBottom:6}}>{t("更适合","Best for")}</div><div style={{display:"flex",gap:6,flexWrap:"wrap",marginBottom:audienceNot.length||audienceCaveats.length?10:0}}>{audienceBest.map(x=><Badge key={x} tone="sage">✓ {x}</Badge>)}</div>{audienceNot.length>0&&<><div style={{fontSize:11,fontWeight:650,marginBottom:6}}>{t("不太适合","Less ideal for")}</div><div style={{display:"flex",gap:6,flexWrap:"wrap",marginBottom:10}}>{audienceNot.map(x=><Badge key={x} tone="rose">× {x}</Badge>)}</div></>}{audienceCaveats.length>0&&<><div style={{fontSize:11,fontWeight:650,marginBottom:5}}>{t("使用提醒","Notes")}</div>{audienceCaveats.map(x=><div key={x} style={{fontSize:10.5,color:MUTE,lineHeight:1.55,marginTop:3}}>· {x}</div>)}</>}</section>

  <section style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) minmax(0,1fr)",gap:10,marginBottom:14}}><div style={{border:`1px solid ${stars>=3?SAGE:stars>0?ROSE:LINE}`,borderRadius:16,padding:15,background:stars>=3?"#EDF1EA":stars>0?"#F6ECE8":"rgba(255,255,255,.65)"}}><div style={{fontSize:9.5,color:stars>=3?SAGE:stars>0?ROSE:MUTE,letterSpacing:".08em",marginBottom:7}}>MATCH FOR YOU</div><div style={{fontSize:23,letterSpacing:".04em",marginBottom:3}}>{stars?`${"★".repeat(stars)}${"☆".repeat(5-stars)}`:"☆☆☆☆☆"}</div><div style={{fontSize:12.5,fontWeight:600,color:stars>=3?"#4E6254":"#8E665F",marginBottom:5}}>{rating.label}{bonus?" · Bonus":""}</div><div style={{fontSize:10.5,color:MUTE,lineHeight:1.5,marginBottom:5}}>{rating.detail}</div><div style={{fontSize:9.5,color:MUTE,lineHeight:1.45}}>{t("3 星及以上 = 可以使用。星级只表示与你当前肤质和需求的匹配程度。","3 stars or above means the product is broadly usable for your current profile. The rating reflects fit, not clinical efficacy.")}</div></div><div style={{border:`1px solid ${formula.tone==="good"?SAGE:ROSE}`,borderRadius:16,padding:15,background:formula.tone==="good"?"#F2F4EF":"#F6ECE8"}}><div style={{fontSize:9.5,color:formula.tone==="good"?SAGE:ROSE,letterSpacing:".08em",marginBottom:7}}>FORMULA DATA</div><div style={{fontSize:17,marginBottom:5}}>{formula.label}</div><div style={{fontSize:10.5,color:MUTE,lineHeight:1.5}}>{formula.detail}</div><div style={{fontSize:10.5,color:MUTE,marginTop:6}}>{t("数据可信度","Data confidence")} · {current.dataCompleteness>=85?t("高","High"):current.dataCompleteness>=65?t("中","Medium"):t("较低","Lower")}</div></div></section>

  {match?.recommendationAvailable&&<section style={card}><div style={{fontSize:10,color:SAGE,letterSpacing:".08em",marginBottom:10}}>{t("为什么这样判断","Why this rating")}</div>{match.positiveEvidence.slice(0,3).map(e=><div key={e.name} style={{fontSize:12,color:"#40594A",lineHeight:1.55,marginBottom:5}}>✓ {e.name} · {t("配料位置靠前","appears relatively high in the ingredient list")}</div>)}{match.systemEvidence.slice(0,2).map(e=><div key={e.key} style={{fontSize:12,color:"#40594A",lineHeight:1.55,marginBottom:5}}>✓ {SYSTEM_COPY[e.key as FormulaSystemKey]?.[language==="zh"?0:1]||e.key} · {t("与你的目标一致","aligns with your goal")}</div>)}{match.negativeEvidence.slice(0,3).map(e=><div key={e.name} style={{fontSize:12,color:"#8A5F58",lineHeight:1.55,marginTop:5}}>△ {e.name} · {t("需要考虑耐受","tolerance should be considered")}</div>)}</section>}

  <section style={{...card,overflow:"hidden"}}><div style={{fontSize:10,color:MUTE,letterSpacing:".08em",marginBottom:8}}>{t("配方重点","Formula profile")}</div><FormulaRadar dna={dna}/><div style={{display:"flex",gap:7,flexWrap:"wrap"}}>{visibleSystems.slice(0,6).map(x=><Badge key={x.key} tone={x.score>=3?"sage":"neutral"}>{SYSTEM_COPY[x.key][language==="zh"?0:1]} · {x.score>=4?t("重点体系","Core system"):x.score>=2?t("辅助体系","Supporting system"):t("轻度支持","Light support")}</Badge>)}</div><div style={{marginTop:13,paddingTop:11,borderTop:`1px solid ${LINE}`,display:"flex",gap:6,flexWrap:"wrap"}}><Badge>{displayCategory}</Badge><Badge tone={dna.alcohol.level==="high"?"rose":"sage"}>{alcoholCopy(dna.alcohol.level,language)}</Badge></div></section>

  <section style={{...card,background:"#F1F3EE"}}><div style={{fontSize:10,color:SAGE,letterSpacing:".08em",marginBottom:5}}>{t("品牌怎么说 vs 配方怎么看","MARKETING CLAIMS vs FORMULA EVIDENCE")}</div><div style={{fontFamily:"'Newsreader', serif",fontSize:21,lineHeight:1.3,marginBottom:10}}>Marketing Reality Check</div><div style={{fontSize:10.5,color:MUTE,lineHeight:1.55,marginBottom:12}}>{reality.sourceNote}</div><div style={{display:"grid",gap:8,marginBottom:12}}>{reality.items.map(item=><div key={item.label} style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) auto",gap:10,alignItems:"center",borderTop:`1px solid ${LINE}`,paddingTop:8}}><div style={{fontSize:12,fontWeight:600}}>{item.label}</div><div style={{display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:11,color:item.support==="weak"?ROSE:SAGE}}>{"★".repeat(Math.max(1,item.score))}{"☆".repeat(Math.max(0,5-Math.max(1,item.score)))}</span><span style={{fontSize:9.5,color:MUTE,minWidth:58,textAlign:"right"}}>{item.support==="strong"?t("强支持","Strong"):item.support==="moderate"?t("有支持","Supported"):t("偏弱","Weak")}</span></div></div>)}</div><div style={{borderTop:`1px solid ${LINE}`,paddingTop:11,fontSize:12.5,lineHeight:1.65,color:"#44483F"}}><b>{t("一句话：","Bottom line: ")}</b>{reality.summary}</div></section>

  <section style={card}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"baseline",marginBottom:9}}><div style={{fontSize:10,color:MUTE,letterSpacing:".08em"}}>{t("完整成分 · INCI / 中文对应","Full ingredients · INCI")}</div><div style={{fontSize:10,color:MUTE}}>{fullIngredients.length} ingredients</div></div>{loading?<div style={{fontSize:11.5,color:MUTE}}>{t("正在读取完整配方…","Loading the full stored formula…")}</div>:error?<div style={{fontSize:11.5,color:ROSE}}>{t("无法加载详情，暂时显示当前已保存成分。","Unable to load full details; showing the currently stored ingredients.")}</div>:null}<BilingualIngredientList ingredients={fullIngredients}/><div style={{fontSize:10.5,color:MUTE,lineHeight:1.55,marginTop:10}}>{t("标准 INCI 是主键；中文名、常用名和作用来自 Ingredient Dictionary。尚未映射的成分保留原始 INCI，不临时猜译。","Standard INCI is the canonical key. Functions and plain-language notes come from the Ingredient Dictionary; unmapped ingredients remain as original INCI rather than being guessed.")}</div></section>

  <section style={{...card,margin:"18px 0"}}><div style={{fontSize:9.5,color:SAGE,letterSpacing:".08em",marginBottom:6}}>{displayCountry} · {brand.segment}</div><div style={{fontFamily:"'Newsreader', serif",fontSize:22,marginBottom:6}}>{t("关于","About")} {brand.name}</div><div style={{fontSize:11.5,color:MUTE,lineHeight:1.6}}>{language==="zh"?brand.description:`${brand.name} is classified as ${brand.segment} in the Skincare101 catalog. Product-level recommendations are based on the verified formula rather than brand positioning alone.`}</div><div style={{fontSize:11.5,marginTop:9}}><b>{t("代表性产品 / 系列：","Known for: ")}</b>{brand.knownFor}</div><div style={{fontSize:11.5,marginTop:5}}><b>{t("更适合：","Best for: ")}</b>{language==="zh"?brand.bestFor:"Use the product-level formula fit and your skin profile as the primary decision basis."}</div><div style={{fontSize:11.5,marginTop:5}}><b>{t("价格：","Price: ")}</b>{approximatePriceGuide(brand,product.category)}</div><div style={{fontSize:9.5,color:MUTE,lineHeight:1.5,marginTop:4}}>{t("这是用于预算筛选的估算区间，不是实时售价；促销、容量和零售渠道会造成差异。","This is a budgeting guide, not a live price. Promotions, size and retailer can materially change the actual price.")}</div></section>

  {(similar||budgetAlternative||premiumAlternative)&&<section style={card}><div style={{fontSize:10,color:MUTE,letterSpacing:".08em",marginBottom:10}}>{t("替代选择","ALTERNATIVES")}</div>{[[t("相似配方","Similar formula match"),similar],[t("平价替代","Budget alternative"),budgetAlternative],[t("高端替代","Premium alternative"),premiumAlternative]] .map(([label,candidate])=>{const c=candidate as SharedProductRecord|undefined;if(!c)return null;const cName=language==="zh"?(c.productLocalName||c.name):(c.productEnglishName||(!HAS_CJK.test(c.name)?c.name:c.brandEnglishName||c.brand));return <button key={`${label}-${c.id}`} onClick={()=>onProduct(c,concern||"all")} style={{width:"100%",border:0,borderTop:`1px solid ${LINE}`,background:"transparent",padding:"10px 0",textAlign:"left",cursor:"pointer"}}><div style={{fontSize:9.5,color:SAGE,marginBottom:3}}>{label as string}</div><div style={{fontSize:11.5}}>{language==="zh"?(c.brandLocalName||c.brand):(c.brandEnglishName||c.brand)} · {cName}</div></button>})}</section>}

  <section style={card}><div style={{fontSize:10,color:SAGE,letterSpacing:".08em",marginBottom:5}}>{t("真实使用体验","Real-world experiences")}</div><div style={{fontFamily:"'Newsreader', serif",fontSize:21,marginBottom:5}}>{experiences.length?t(`${experiences.length} 位用户分享`,`${experiences.length} user experiences`):t("还没有人分享","No experiences yet")}</div><div style={{fontSize:10.5,color:MUTE,lineHeight:1.5,marginBottom:13}}>{t("按肤质查看个体体验，不把它当作医疗证据。","Read experiences in the context of each skin profile; they are not medical evidence.")}</div>{experiences.map(item=><article key={item.id} style={{borderTop:`1px solid ${LINE}`,padding:"12px 0"}}><div style={{display:"flex",gap:6,flexWrap:"wrap",fontSize:10.5,marginBottom:item.note?7:0}}><span>✓ {reactionLabel[item.reaction]}</span><span>· {textureLabel[item.texture]}</span><span>· {repurchaseLabel[item.repurchase]}</span></div>{item.note&&<div style={{fontSize:11.5,color:"#514D45",lineHeight:1.55}}>{item.note}</div>}</article>)}</section>

  <section style={card}><div style={{fontSize:10,color:SAGE,letterSpacing:".08em",marginBottom:5}}>{t("分享你的使用体验","Share your experience")}</div><div style={{display:"grid",gridTemplateColumns:"1fr",gap:7,marginBottom:8}}><select aria-label={t("使用后的皮肤变化","Skin response")} value={reaction} onChange={e=>setReaction(e.target.value as ProductReaction)}><option value="better">{t("皮肤有改善","Skin improved")}</option><option value="neutral">{t("没有明显变化","No clear change")}</option><option value="irritated">{t("出现刺激或不适","Irritation or discomfort")}</option></select><select aria-label={t("产品肤感","Texture")} value={texture} onChange={e=>setTexture(e.target.value as typeof texture)}><option value="love">{t("喜欢肤感","Liked the texture")}</option><option value="okay">{t("肤感一般","Texture was okay")}</option><option value="dislike">{t("不喜欢肤感","Disliked the texture")}</option></select><select aria-label={t("是否回购","Repurchase")} value={repurchase} onChange={e=>setRepurchase(e.target.value as typeof repurchase)}><option value="yes">{t("会回购","Would repurchase")}</option><option value="maybe">{t("可能回购","Might repurchase")}</option><option value="no">{t("不会回购","Would not repurchase")}</option></select></div><textarea maxLength={500} value={note} onChange={e=>setNote(e.target.value)} placeholder={t("例如：用了多久、什么天气、是否闷痘或刺痛……","For example: how long you used it, climate, breakouts, stinging or other reactions…")} style={{width:"100%",boxSizing:"border-box",minHeight:78,resize:"vertical",border:`1px solid ${LINE}`,borderRadius:10,padding:9,fontSize:11,marginBottom:8}}/><button disabled={feedbackStatus==="saving"} onClick={submitExperience} style={{width:"100%",border:0,borderRadius:999,padding:10,background:SAGE,color:"white",fontSize:11,cursor:feedbackStatus==="saving"?"wait":"pointer",opacity:feedbackStatus==="saving"?.65:1}}>{feedbackStatus==="saving"?t("正在提交…","Submitting…"):feedbackStatus==="saved"?t("已公开，可继续修改","Published — you can still edit it"):t("匿名公开我的体验","Publish anonymously")}</button>{feedbackMessage&&<div style={{fontSize:9.5,color:feedbackStatus==="error"?ROSE:SAGE,marginTop:7}}>{feedbackMessage}</div>}<div style={{fontSize:9.5,color:MUTE,marginTop:7}}>{t("需要登录才能提交；不会公开姓名、邮箱或账号信息。","Sign-in is required to submit. Your name, email and account details are not displayed.")}</div></section>

  <a href={current.sourceUrl} target="_blank" rel="noreferrer" style={{width:"100%",boxSizing:"border-box",borderRadius:999,padding:"11px 14px",background:INK,color:"white",textDecoration:"none",display:"flex",alignItems:"center",justifyContent:"center",gap:7,fontSize:12}}>{t("查看配方来源 / 购买页面","View formula source / purchase page")} <ExternalLink size={13}/></a>
 </div></div>
}
