import React,{useMemo,useState}from"react";
import{ArrowLeft,Check,PackageCheck}from"lucide-react";
import type{SkinProfileRecord}from"../lib/skinProfile";
import{summarizeSkinProfile}from"../lib/skinProfile";
import type{SharedProductRecord}from"../lib/supabase";
import{rankForProfile,matchRating,personalizedScore,type BrowseConcern}from"../lib/productPresentation";
import{priceTierForBrand,type ProductPriceTier}from"../data/brandProfiles";
import{buildRoutine,categoryForRoutineStep,routineGuardrails,ROUTINE_GOALS,ROUTINE_TEMPLATES,type ActiveTolerance,type RoutineComplexity,type RoutineGoal}from"../intelligence/routineEngine";
import{useLanguage}from"../lib/i18n";
import{displayGoal,displayGuardrail,displayRoutineNote,displayRoutineStep,displaySkinLabel}from"../lib/displayI18n";
import{brandNames,productNames}from"../lib/productNames";
import{loadShelf}from"../lib/myShelf";
import{DayWatercolor,RoutineWatercolor,WatercolorTabMark}from"./WatercolorMotifs";
const INK="#252724",BG="#F6F4EF",CARD="#FCFBF8",LINE="#DEDCD5",SAGE="#667A6C",MUTE="#777870",GOLD="#B78D28";const sans="-apple-system, BlinkMacSystemFont, 'Segoe UI', 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', sans-serif";
export default function V3RoutineBuilder({profile,products,onBack,onExplore,onProduct}:{profile:SkinProfileRecord|null;products:SharedProductRecord[];onBack:()=>void;onExplore:()=>void;onProduct:(product:SharedProductRecord,concern:BrowseConcern)=>void;}){
 const{t,language}=useLanguage();const[goal,setGoal]=useState<RoutineGoal>("Barrier"),[complexity,setComplexity]=useState<RoutineComplexity>("standard"),[tolerance,setTolerance]=useState<ActiveTolerance>("beginner"),[budget,setBudget]=useState<ProductPriceTier|"all">("all");
 const summary=summarizeSkinProfile(profile),routine=useMemo(()=>buildRoutine(goal,complexity),[goal,complexity]),concern=ROUTINE_TEMPLATES[goal].concern,guardrails=routineGuardrails(profile,goal,tolerance),ranked=useMemo(()=>rankForProfile(products,profile,concern).filter(p=>p.recommendationAvailable),[products,profile,concern]);
 const shelfEntries=useMemo(()=>loadShelf(),[]),ownedIds=useMemo(()=>new Set(shelfEntries.map(x=>x.productId)),[shelfEntries]),ownedProducts=useMemo(()=>products.filter(p=>ownedIds.has(p.id)),[products,ownedIds]);
 function rec(step:string){const category=categoryForRoutineStep(step);const c=ranked.filter(p=>p.category===category),owned=c.filter(p=>ownedIds.has(p.id)),budgetOwned=budget==="all"?owned:owned.filter(x=>priceTierForBrand(x.brand)===budget),budgetAll=budget==="all"?c:c.filter(x=>priceTierForBrand(x.brand)===budget),pool=budgetOwned.length?budgetOwned:owned.length?owned:budgetAll.length?budgetAll:c;const best=pool[0],alternative=(owned.length?owned:c).find(x=>x.id!==best?.id&&x.brand!==best?.brand);return{best,alternative,isOwned:Boolean(best&&ownedIds.has(best.id)),hasOwnedMatch:owned.length>0}}
 const chip=(s:boolean)=>({border:`1px solid ${s?SAGE:LINE}`,borderRadius:999,padding:"8px 11px",background:s?"#E9EEE9":CARD,color:s?SAGE:INK,fontSize:12,cursor:"pointer",fontFamily:sans})as const,select={border:`1px solid ${LINE}`,borderRadius:14,padding:11,background:CARD,fontSize:12,fontFamily:sans,color:INK}as const;
 const ratingLabel=(stars:number)=>stars===5?t("非常适合","Excellent match"):stars===4?t("适合","Good match"):stars===3?t("可以用","Suitable"):stars===2?t("谨慎尝试","Caution"):t("不推荐","Not recommended");
 const profileLine=profile?`${displaySkinLabel(summary.skinType,language)} · ${displaySkinLabel(summary.sensitivity,language)}`:"";
 const productLine=(p:SharedProductRecord)=>{const b=brandNames(p,language),n=productNames(p,language);return `${b.primary} · ${n.primary}`};
 return <div style={{minHeight:"100vh",background:BG,color:INK,padding:"22px 18px 54px",fontFamily:sans}}><div style={{maxWidth:580,margin:"0 auto"}}>
 <button onClick={onBack} style={{border:0,background:"transparent",padding:0,color:MUTE,fontSize:13,cursor:"pointer",marginBottom:30,display:"flex",gap:7,alignItems:"center",fontFamily:sans}}><ArrowLeft size={15}/>{t("返回首页","Back to home")}</button>
 <div style={{fontSize:11,letterSpacing:".12em",color:SAGE,fontWeight:700,marginBottom:10}}>MY ROUTINE</div><h1 style={{fontSize:32,fontWeight:650,lineHeight:1.2,letterSpacing:"-.035em",margin:"0 0 10px"}}>{t("先把你已经有的用顺，再补真正缺的。","Use what you own first, then fill real gaps.")}</h1>
 <p style={{fontSize:14,color:MUTE,lineHeight:1.7,margin:"0 0 18px"}}>{profile?t(`基于当前档案：${profileLine}`,`Based on your current profile: ${profileLine}`):t("没有肤质档案也可以先组合；建档后会加入敏感与耐受限制。","You can start without a profile; once created, sensitivity and tolerance guardrails will be applied.")}</p>
 <section style={{border:`1px solid ${ownedProducts.length?"#D4C38A":LINE}`,borderRadius:18,padding:"13px 14px",background:ownedProducts.length?"#FFF9E8":CARD,marginBottom:20}}><div style={{display:"flex",gap:9,alignItems:"center"}}><PackageCheck size={17} color={ownedProducts.length?GOLD:SAGE}/><div><div style={{fontSize:12.5,fontWeight:700}}>{ownedProducts.length?t(`已读取你的护肤柜 · ${ownedProducts.length} 个产品`,`My Shelf connected · ${ownedProducts.length} products`):t("你的护肤柜还是空的","Your shelf is empty")}</div><div style={{fontSize:11.5,color:MUTE,lineHeight:1.55,marginTop:3}}>{ownedProducts.length?t("每一步都会优先从你已经拥有、且适合当前目标的产品中选择。没有合适的，才会推荐新产品。","Each step first looks for products you already own that fit this goal. New products appear only when needed."):t("先去 My Shelf 加入手上的产品，Routine 就会优先用现有产品。","Add what you own in My Shelf and Routine will prioritize those products first.")}</div></div></div></section>
 <div style={{fontSize:12,fontWeight:650,marginBottom:10}}>{t("你最想改善什么？","What do you want to improve most?")}</div><div style={{display:"flex",flexWrap:"wrap",gap:8,marginBottom:20}}>{ROUTINE_GOALS.map(x=><button key={x} onClick={()=>setGoal(x)} style={chip(goal===x)}>{displayGoal(x,language)}<WatercolorTabMark active={goal===x}/></button>)}</div>
 <div style={{display:"flex",gap:8,marginBottom:10}}><button onClick={()=>setComplexity("minimal")} style={{...chip(complexity==="minimal"),flex:1,borderRadius:14}}>{t("精简护肤","Minimal routine")}<WatercolorTabMark active={complexity==="minimal"}/></button><button onClick={()=>setComplexity("standard")} style={{...chip(complexity==="standard"),flex:1,borderRadius:14}}>{t("标准护肤","Standard routine")}<WatercolorTabMark active={complexity==="standard"}/></button></div>
 <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:20}}><select value={tolerance} onChange={e=>setTolerance(e.target.value as ActiveTolerance)} style={select}><option value="none">{t("不使用强功效成分","No strong actives")}</option><option value="beginner">{t("功效成分新手","Active beginner")}</option><option value="experienced">{t("已建立耐受","Experienced with actives")}</option></select><select value={budget} onChange={e=>setBudget(e.target.value as ProductPriceTier|"all")} style={select}><option value="all">{t("不限预算","Any budget")}</option><option value="budget">{t("平价","Budget")}</option><option value="mid">{t("中档","Mid-range")}</option><option value="premium">{t("高端","Premium")}</option></select></div>
 {profile?.skinAnswers?.sensitive==="yes"&&<div style={{border:`1px solid ${LINE}`,background:"#F1ECE8",borderRadius:16,padding:"12px 14px",fontSize:12,color:MUTE,lineHeight:1.6,marginBottom:14}}>{t("已启用敏感倾向限制：强酸和维 A 类会更保守地加入，而不是单纯追求功效强度。","Sensitivity guardrails are active: strong acids and retinoids are introduced conservatively instead of maximizing strength.")}</div>}
 {[["AM",routine.am],["PM",routine.pm]].map(([period,steps])=><section key={period as string} style={{border:`1px solid ${LINE}`,borderRadius:22,padding:18,background:CARD,marginBottom:14,boxShadow:"0 8px 24px rgba(46,64,48,.035)"}}><div style={{display:"flex",alignItems:"center",gap:9,marginBottom:10}}><DayWatercolor period={period as "AM"|"PM"}/><div><div style={{fontSize:11,letterSpacing:".1em",fontWeight:700,color:SAGE}}>{period==="AM"?t("早间护肤","AM ROUTINE"):t("晚间护肤","PM ROUTINE")}</div><div style={{fontSize:11,color:MUTE,marginTop:2}}>{period==="AM"?t("清爽、防护、稳定","Light · protect · support"):t("修护、功效、恢复","Repair · treat · recover")}</div></div></div>{(steps as string[]).map((step,i)=>{const c=rec(step),r=c.best?matchRating(personalizedScore(c.best,profile,concern)):null;return <div key={step} style={{padding:"12px 0",borderTop:i?`1px solid ${LINE}`:"none"}}><div style={{display:"flex",gap:10,alignItems:"center"}}><RoutineWatercolor step={step}/><span style={{width:22,height:22,border:`1px solid ${LINE}`,borderRadius:"50%",display:"grid",placeItems:"center",fontSize:10,color:MUTE,flexShrink:0}}>{i+1}</span><b style={{fontSize:13}}>{displayRoutineStep(step,language)}</b></div>{c.best?<div style={{margin:"9px 0 0 66px"}}><button onClick={()=>onProduct(c.best!,concern)} style={{border:0,padding:0,background:"transparent",textAlign:"left",fontFamily:sans,cursor:"pointer"}}><span style={{fontSize:12,color:INK}}>{productLine(c.best)}</span>{c.isOwned&&<span style={{display:"inline-block",marginLeft:7,border:"1px solid #D4C38A",borderRadius:999,padding:"2px 6px",background:"#FFF8DE",color:GOLD,fontSize:9.5,fontWeight:700}}>{t("你已有","OWNED")}</span>}{r&&<span style={{display:"block",fontSize:12,color:SAGE,marginTop:4,letterSpacing:.5}}>{r.starsText} · {ratingLabel(r.stars)}</span>}</button>{c.alternative&&<button onClick={()=>onProduct(c.alternative!,concern)} style={{display:"block",border:0,padding:"6px 0 0",background:"transparent",color:MUTE,textAlign:"left",fontSize:11,fontFamily:sans,cursor:"pointer"}}>{c.hasOwnedMatch?t("你已有的替代","Owned alternative"):t("替代","Alternative")}: {productLine(c.alternative)}</button>}</div>:<div style={{margin:"9px 0 0 66px",fontSize:11.5,color:MUTE,lineHeight:1.55}}>{t("你的护肤柜里暂时没有合适产品，这一步才需要考虑补充。","Nothing suitable on your shelf for this step; this is where a new product may actually be useful.")}</div>}</div>})}</section>)}
 <div style={{fontSize:12,color:MUTE,lineHeight:1.65,margin:"14px 0"}}>{displayRoutineNote(routine.note,language)}</div><div style={{borderTop:`1px solid ${LINE}`,paddingTop:12,marginBottom:18}}>{guardrails.map(n=><div key={n} style={{fontSize:11.5,color:MUTE,lineHeight:1.6,marginBottom:5}}>△ {displayGuardrail(n,language)}</div>)}</div>
 <button onClick={onExplore} style={{width:"100%",border:0,borderRadius:16,padding:"13px 15px",background:SAGE,color:"white",fontSize:13,fontWeight:650,cursor:"pointer",display:"flex",justifyContent:"center",alignItems:"center",gap:7,fontFamily:sans}}><Check size={15}/>{t(ownedProducts.length?"只看我真正缺的产品":"查看这些步骤的产品",ownedProducts.length?"Find only what I'm missing":"Find products for these steps")}</button></div></div>}
