import React,{useEffect,useMemo,useState}from"react";
import{ArrowLeft,Bookmark,RefreshCw,UsersRound}from"lucide-react";
import{loadPublicRoutines,savePublicRoutine,type RoutineListItem}from"../lib/routines";
import{useLanguage}from"../lib/i18n";
const INK="#252724",BG="#F6F4EF",CARD="#FCFBF8",LINE="#DEDCD5",SAGE="#667A6C",MUTE="#777870";const sans="-apple-system, BlinkMacSystemFont, 'Segoe UI', 'PingFang SC', sans-serif";
function skinLabel(r:RoutineListItem){const a=r.skinProfile?.skin_answers||{};const bits=[a.skinType||a.skin_type,a.sensitive==="yes"?"Sensitive":null].filter(Boolean);return bits.join(" · ");}
export default function V3RoutineCommunity({onBack}:{onBack:()=>void}){const{t}=useLanguage();const[items,setItems]=useState<RoutineListItem[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[goal,setGoal]=useState("all"),[saving,setSaving]=useState<string|null>(null),[saved,setSaved]=useState<string[]>([]);
 async function refresh(){setLoading(true);setError("");try{setItems(await loadPublicRoutines())}catch(e){setError(e instanceof Error?e.message:t("暂时无法读取社区 Routine","Unable to load community routines"))}finally{setLoading(false)}}useEffect(()=>{void refresh()},[]);
 const goals=useMemo(()=>Array.from(new Set(items.flatMap(i=>i.goals))).filter(Boolean),[items]);const shown=goal==="all"?items:items.filter(i=>i.goals.includes(goal));
 async function save(id:string){setSaving(id);try{await savePublicRoutine(id);setSaved(x=>x.includes(id)?x:[...x,id])}catch(e){setError(e instanceof Error?e.message:t("收藏失败，请先登录","Unable to save; please sign in"))}finally{setSaving(null)}}
 return <div style={{minHeight:"100vh",background:BG,color:INK,padding:"22px 18px 54px",fontFamily:sans}}><div style={{maxWidth:620,margin:"0 auto"}}><button onClick={onBack} style={{border:0,background:"transparent",padding:0,color:MUTE,fontSize:13,cursor:"pointer",marginBottom:28,display:"flex",gap:7,alignItems:"center"}}><ArrowLeft size={15}/>{t("返回首页","Back to home")}</button><div style={{display:"flex",gap:12,alignItems:"center",marginBottom:8}}><UsersRound size={22} color={SAGE}/><div style={{fontSize:11,letterSpacing:".12em",color:SAGE,fontWeight:700}}>ROUTINE COMMUNITY</div></div><h1 style={{fontSize:31,fontWeight:650,letterSpacing:"-.035em",lineHeight:1.18,margin:"0 0 10px"}}>{t("看看和你肤质相似的人在用什么","See what similar skin types actually use")}</h1><p style={{fontSize:13.5,color:MUTE,lineHeight:1.65,margin:"0 0 20px"}}>{t("这里展示用户主动公开的完整早晚组合，而不是单个产品的孤立评分。","These are voluntarily published AM/PM combinations, not isolated product ratings.")}</p>
 <div style={{display:"flex",gap:7,overflowX:"auto",paddingBottom:8,marginBottom:12}}><button onClick={()=>setGoal("all")} style={chip(goal==="all")}>{t("全部","All")}</button>{goals.map(g=><button key={g} onClick={()=>setGoal(g)} style={chip(goal===g)}>{g}</button>)}</div>
 {error&&<div style={{border:`1px solid #E8D3CF`,background:"#FFF9F7",borderRadius:14,padding:12,fontSize:12,color:"#9A625C",marginBottom:12}}>{error}</div>}{loading?<div style={{padding:"48px 0",textAlign:"center",color:MUTE,fontSize:12}}>{t("正在读取公开 Routine…","Loading public routines…")}</div>:shown.length===0?<div style={{border:`1px solid ${LINE}`,borderRadius:18,padding:22,background:CARD,color:MUTE,fontSize:13,lineHeight:1.6}}>{t("还没有符合条件的公开 Routine。第一批用户发布以后，这里会自动出现。","No matching public routines yet. Published routines will appear here automatically.")}<button onClick={()=>void refresh()} style={{display:"flex",gap:6,alignItems:"center",marginTop:12,border:0,background:"transparent",color:SAGE,cursor:"pointer"}}><RefreshCw size={13}/>{t("刷新","Refresh")}</button></div>:<div style={{display:"grid",gap:12}}>{shown.map(r=><article key={r.id} style={{border:`1px solid ${LINE}`,borderRadius:20,padding:17,background:CARD}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><div><div style={{fontSize:18,fontWeight:650,letterSpacing:"-.02em"}}>{r.title}</div><div style={{fontSize:11.5,color:MUTE,marginTop:5}}>{skinLabel(r)||t("肤质信息未公开","Skin profile not shown")}{r.climate?` · ${r.climate}`:""}{r.usageWeeks?` · ${r.usageWeeks} ${t("周","weeks")}`:""}</div></div>{r.overallRating&&<div style={{fontSize:12,color:SAGE,whiteSpace:"nowrap"}}>{"★".repeat(r.overallRating)}{"☆".repeat(5-r.overallRating)}</div>}</div>{r.goals.length>0&&<div style={{display:"flex",gap:6,flexWrap:"wrap",marginTop:11}}>{r.goals.map(g=><span key={g} style={{fontSize:10.5,border:`1px solid ${LINE}`,borderRadius:999,padding:"5px 8px",color:SAGE}}>{g}</span>)}</div>}{r.description&&<p style={{fontSize:12.5,color:MUTE,lineHeight:1.6,margin:"12px 0 6px"}}>{r.description}</p>}{(["AM","PM"] as const).map(period=>{const rows=r.items.filter(i=>i.period===period);return rows.length?<div key={period} style={{borderTop:`1px solid ${LINE}`,paddingTop:10,marginTop:10}}><div style={{fontSize:10.5,fontWeight:700,color:SAGE,letterSpacing:".08em",marginBottom:6}}>{period}</div>{rows.map(i=><div key={i.id} style={{fontSize:12.2,lineHeight:1.65}}><span style={{color:MUTE,display:"inline-block",minWidth:76}}>{i.stepCategory}</span>{i.product?`${i.product.brand} · ${i.product.name}`:i.customProductName}</div>)}</div>:null})}<button onClick={()=>void save(r.id)} disabled={saving===r.id||saved.includes(r.id)} style={{width:"100%",marginTop:14,border:`1px solid ${saved.includes(r.id)?SAGE:LINE}`,borderRadius:13,padding:"10px 12px",background:saved.includes(r.id)?"#E9EEE9":"white",color:SAGE,fontSize:12,fontWeight:650,cursor:"pointer",display:"flex",justifyContent:"center",gap:7,alignItems:"center"}}><Bookmark size={14}/>{saved.includes(r.id)?t("已收藏","Saved"):t("收藏这套 Routine","Save this routine")}</button></article>)}</div>}</div></div>}
function chip(active:boolean):React.CSSProperties{return{border:`1px solid ${active?SAGE:LINE}`,borderRadius:999,padding:"7px 10px",background:active?"#E9EEE9":CARD,color:active?SAGE:INK,fontSize:11.5,cursor:"pointer",whiteSpace:"nowrap"}}
