import fs from 'node:fs/promises';
import path from 'node:path';
import {articles,sources,art} from '../data/blog-articles.mjs';
import {translations,sourceNotes} from '../data/blog-articles-en.mjs';
import {origin,esc,locale,productRoute,blogRoute,directoryRoute} from './static-languages.mjs';
const css=":root{color-scheme:light;--ink:#263027;--green:#2f5a40;--paper:#fbf6ea;--line:#d9d0bc}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;color:var(--ink);background:var(--paper);font:17px/1.85 system-ui,-apple-system,\"PingFang SC\",\"Microsoft YaHei\",sans-serif}a{color:var(--green);text-underline-offset:4px}a:focus-visible,summary:focus-visible{outline:3px solid #9a6e04;outline-offset:5px}header{max-width:1120px;margin:auto;padding:24px;display:flex;justify-content:space-between;align-items:center;gap:20px;border-bottom:1px solid var(--line)}.brand{font:italic 30px Georgia,serif;text-decoration:none}nav{display:flex;flex-wrap:wrap;gap:18px;font-size:14px}main{max-width:820px;margin:auto;padding:36px 24px 72px}.wide{max-width:1120px}.eyebrow{font-size:14px;letter-spacing:.12em;color:var(--green)}h1{font-family:Georgia,\"Songti SC\",serif;font-size:clamp(30px,5vw,48px);line-height:1.3;letter-spacing:-.025em;margin:12px 0 22px}h2{font-size:25px;line-height:1.45;margin:38px 0 14px}h3{font-size:20px;line-height:1.5}p{margin:0 0 18px}li{margin:8px 0}.meta,.refs,figcaption{font-size:14px;color:#615e54}.refs{margin-top:8px}figure{margin:26px 0}.cover{display:block;width:100%;height:auto;aspect-ratio:3/2;object-fit:cover;border-radius:16px}figcaption{margin-top:8px}.answer{border-left:4px solid var(--green);background:#eaf0e6;padding:22px;margin:26px 0}.answer p:last-child{margin:0}.toc{border:1px solid var(--line);padding:16px 22px;border-radius:12px}.toc summary{cursor:pointer;font-weight:600}.toc ol{margin-bottom:0}section{scroll-margin-top:20px}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse;font-size:16px;margin:20px 0}th,td{padding:12px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top;min-width:125px}th{background:#eaf0e6}.cta{display:flex;flex-wrap:wrap;gap:12px;margin:24px 0}.cta a{padding:10px 16px;border:1px solid var(--green);border-radius:24px;text-decoration:none}.cta a:first-child{background:var(--green);color:white}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:28px 22px}.card{min-width:0}.card a{text-decoration:none}.card h2{font-size:22px;margin:12px 0}.card p{font-size:15px;line-height:1.65}.card .cover{border-radius:12px}.card a:hover h2{text-decoration:underline}.notice{border-top:1px solid var(--line);padding-top:22px;font-size:14px;color:#615e54;margin-top:32px}.related{display:grid;gap:12px}.sources li{overflow-wrap:anywhere;font-size:14px}footer{max-width:1120px;margin:auto;border-top:1px solid var(--line);padding:24px;font-size:14px}.intro{max-width:680px;margin-bottom:36px}@media(max-width:760px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}header{align-items:flex-start;flex-direction:column;gap:10px}}@media(max-width:480px){.grid{grid-template-columns:1fr}main{padding:24px 18px 56px}header{padding:18px}.answer{padding:18px}body{font-size:16px}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}";
const json=x=>JSON.stringify(x).replaceAll('<','\\u003c');
const categories={'新加坡日常':'Singapore daily life','产品选择':'Choosing products','精简护肤':'Simple routines'};
const alts={climate:'Illustration of a woman arranging skincare between a tropical city and an indoor room',routine:'Illustration of a simple cleanser, moisturiser and sunscreen routine',shopping:'Illustration of a woman thoughtfully comparing two skincare bottles'};
const image=(key,en,lazy=false)=>`<img class="cover" src="/illustrations/blog/${art[key].file}" width="1536" height="1024" alt="${esc(en?alts[key]:art[key].alt)}" ${lazy?'loading="lazy"':'fetchpriority="high"'} decoding="async">`;
function shell(en,l,title,description,route,body,schema){
 return `<!doctype html><html lang="${en?'en':'zh-CN'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | Peacedskin</title><meta name="description" content="${esc(description)}">${l.head}<meta property="og:type" content="${schema['@type']==='BlogPosting'?'article':'website'}"><meta property="og:site_name" content="Peacedskin"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${origin}${route}"><meta name="twitter:card" content="summary"><script type="application/ld+json">${json({'@context':'https://schema.org',...schema})}</script><link rel="stylesheet" href="/blog/blog.css"></head><body><header><a class="brand" href="/">Peacedskin</a><nav aria-label="${l.pick('网站导航','Site navigation')}"><a href="${blogRoute('',en)}">${l.pick('护肤指南','Skincare guides')}</a><a href="${directoryRoute(en)}">${l.pick('产品成分','Product ingredients')}</a><a href="/?view=profileBuilder">${l.pick('肤质测试','Skin profile')}</a></nav></header>${body}<footer><a href="${blogRoute('',en)}">${l.pick('全部护肤指南','All skincare guides')}</a> · <a href="/">Peacedskin</a></footer></body></html>`;
}
function validatePair(zh,en,index){
 if(!en||!en.title||en.sections.length!==zh.sections.length)throw Error('Missing article translation '+index);
 zh.sections.forEach((s,i)=>{
  const e=en.sections[i];if(!e.heading)throw Error('Missing heading');
  for(const key of ['paragraphs','bullets'])if((s[key]?.length||0)!==(e[key]?.length||0))throw Error(`Translation shape: ${index}:${i}:${key}`);
  if(s.table&&(!e.table||s.table.headers.length!==e.table.headers.length||s.table.rows.length!==e.table.rows.length||s.table.rows.some((row,j)=>row.length!==e.table.rows[j].length)))throw Error('Translation table shape '+index);
 });
}
articles.forEach((a,i)=>validatePair(a,translations[i],i));
await fs.mkdir('dist/blog',{recursive:true});await fs.writeFile('dist/blog/blog.css',css);
let sitemap=await fs.readFile('dist/sitemap.xml','utf8');
async function publish(route,html){
 const dir=path.join('dist',route);await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,'index.html'),html);
 if(!sitemap.includes(`<loc>${origin}${route}</loc>`))sitemap=sitemap.replace('</urlset>',`<url><loc>${origin}${route}</loc></url>\n</urlset>`);
}
for(const en of [false,true]){
 for(let a=0;a<articles.length;a++){
  const zh=articles[a],english=translations[a],l=locale(en,blogRoute(zh.slug),blogRoute(zh.slug,true)),t=l.text;
  const route=blogRoute(zh.slug,en),keys=[...new Set(zh.sections.flatMap(s=>s.sources||[]))];
  const blocks=zh.sections.map((s,i)=>{
   const e=english.sections[i];
   const table=s.table?`<div class="table-wrap"><table><thead><tr>${s.table.headers.map((h,j)=>`<th scope="col">${t(h,e.table.headers[j])}</th>`).join('')}</tr></thead><tbody>${s.table.rows.map((row,j)=>`<tr>${row.map((cell,k)=>`<td>${t(cell,e.table.rows[j][k])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'';
   return `<section id="section-${i+1}">${t(s.heading,e.heading,'h2')}${(s.paragraphs||[]).map((p,j)=>t(p,e.paragraphs[j],'p')).join('')}${s.bullets?`<ul>${s.bullets.map((p,j)=>t(p,e.bullets[j],'li')).join('')}</ul>`:''}${table}${s.sources?`<p class="refs">${l.pick('依据：','Sources: ')}${s.sources.map(k=>`<a href="${esc(sources[k].url)}">${esc(sources[k].label)}</a>`).join(' · ')}</p>`:''}</section>`;
  }).join('');
  const body=`<main>${l.controls}<article><div class="eyebrow">${t(zh.category,categories[zh.category])} · PEACEDSKIN JOURNAL</div>${t(zh.title,english.title,'h1')}${t(zh.excerpt,english.excerpt,'p')}<p class="meta">${t('Peacedskin 内容整理 · AI 辅助撰写','Peacedskin editorial · AI-assisted writing and translation')} · <time datetime="${zh.date}">${zh.date}</time>${zh.modified?` · ${t("更新：","Updated: ")}<time datetime="${zh.modified}">${zh.modified}</time>`:""}</p><figure>${image(zh.art,en)}<figcaption>${t('AI 生成专题插画；不是产品实拍或效果对比。','AI-generated editorial illustration; not a product photograph or before-and-after comparison.')}</figcaption></figure><aside class="answer">${t('先说结论','The key point','strong')}${t(zh.answer,english.answer,'p')}</aside><details class="toc"><summary>${t('这篇会回答什么？','In this guide')}</summary><ol>${zh.sections.map((s,i)=>`<li><a href="#section-${i+1}">${t(s.heading,english.sections[i].heading)}</a></li>`).join('')}</ol></details>${blocks}<section>${t('把判断用到你的护肤里','Put the information to use','h2')}${t(zh.next,english.next,'p')}<div class="cta"><a href="/?view=profileBuilder">${t('了解我的肤质','Find my skin profile')}</a><a href="${directoryRoute(en)}">${t('查看产品成分目录','Browse product ingredients')}</a></div>${(zh.products||[]).map((p,i)=>`<p><a href="${en?p.url:'/zh'+p.url}">${t(p.label,english.products[i])}</a></p>`).join('')}</section><section>${t('接着读','Read next','h2')}<div class="related">${zh.related.map(slug=>{const i=articles.findIndex(x=>x.slug===slug);return `<a href="${blogRoute(slug,en)}">${t(articles[i].title,translations[i].title)}</a>`}).join('')}</div></section><section class="sources">${t('资料来源与说明','Sources and editorial notes','h2')}<ol>${keys.map(key=>`<li><a href="${esc(sources[key].url)}">${esc(sources[key].label)}</a> — ${t(sources[key].note,sourceNotes[key])}</li>`).join('')}</ol>${t('资料核对日期：'+zh.date+'。文中的场景安排、购物清单和记录方法是 Peacedskin 的编辑建议，不是上述机构的产品背书。','Sources checked: '+zh.date+'. The scenarios, shopping checklists and recording methods are Peacedskin editorial suggestions, not product endorsements by the cited organisations.','p')}</section><aside class="notice">${t('本文为一般护肤教育与选购信息，未经过医生逐篇医学审阅，不构成诊断或治疗建议。持续或加重的红、痒、疼痛、渗液请就医；出现呼吸困难或明显面部肿胀应及时寻求急救。处方治疗请遵循医生指导，不因本文自行停药。产品版本与配方可能改变，请以手中包装为准。','This is general skincare education and shopping information, not individually medically reviewed advice, diagnosis or treatment. Seek medical care for persistent or worsening redness, itching, pain or oozing; seek urgent help for difficulty breathing or significant facial swelling. Follow your prescriber’s advice and do not stop prescribed treatment because of this article. Formulas and versions can change; check your packaging.')}</aside></article></main>`;
  await publish(route,shell(en,l,l.pick(zh.title,english.title),l.pick(zh.excerpt,english.excerpt),route,body,{'@type':'BlogPosting',headline:l.pick(zh.title,english.title),description:l.pick(zh.excerpt,english.excerpt),inLanguage:en?'en':'zh-CN',datePublished:zh.date,dateModified:zh.modified||zh.date,mainEntityOfPage:origin+route,author:{'@type':'Organization',name:'Peacedskin',url:origin+'/'},publisher:{'@type':'Organization',name:'Peacedskin',url:origin+'/'},image:origin+'/illustrations/blog/'+art[zh.art].file,citation:keys.map(k=>sources[k].url)}));
 }
 const route=blogRoute('',en),l=locale(en,blogRoute(),blogRoute('',true)),t=l.text;
 const cards=articles.map((a,i)=>`<article class="card"><a href="${blogRoute(a.slug,en)}">${image(a.art,en,true)}<p class="eyebrow">${t(a.category,categories[a.category])}</p>${t(a.title,translations[i].title,'h2')}</a>${t(a.excerpt,translations[i].excerpt,'p')}</article>`).reverse().join('');
 const body=`<main class="wide">${l.controls}<div class="intro"><div class="eyebrow">PEACEDSKIN JOURNAL</div>${t('少一点猜测，多一点适合自己。','Less guessing. More of what suits you.','h1')}${t('从新加坡的日常场景出发，讨论怎么买、怎么用，以及什么时候不该继续加产品。','Practical Singapore skincare: what to choose, how to use it and when to stop adding products.','p')}${t(`${articles.length} 篇完整指南，每篇附资料来源。可选择中文、英文或中英对照阅读。`,`${articles.length} complete guides with sources. Read in Chinese, English or both.`,'p')}</div><div class="grid">${cards}</div></main>`;
 await publish(route,shell(en,l,l.pick('护肤指南','Skincare Guides'),l.pick('新加坡日常护肤、产品选择与精简护肤指南，提供中英文阅读。','Practical skincare guides for Singapore: daily routines, product choices and simple care. Available in English and Chinese.'),route,body,{'@type':'CollectionPage',name:l.pick('Peacedskin 护肤指南','Peacedskin Skincare Guides'),url:origin+route,inLanguage:en?'en':'zh-CN'}));
}
for(const a of articles.filter(a=>a.modified))for(const en of [false,true]){
 const loc=`<loc>${origin}${blogRoute(a.slug,en)}</loc>`;
 sitemap=sitemap.replace(loc,loc+`<lastmod>${a.modified}</lastmod>`);
}
await fs.writeFile('dist/sitemap.xml',sitemap);
console.log(`Generated ${articles.length} complete guides in Chinese and English, with paired reading.`);
