import fs from 'node:fs/promises';
import path from 'node:path';
import { articles, sources, art } from '../data/blog-articles.mjs';

const origin = (process.env.SITE_URL || 'https://peacedskin.com').replace(/\/$/, '');
const esc = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');
const json = value => JSON.stringify(value).replaceAll('<', '\\u003c');
const ref = keys => keys?.length ? `<p class="refs">依据：${keys.map(key => `<a href="${esc(sources[key].url)}">${esc(sources[key].label)}</a>`).join(' · ')}</p>` : '';
const image = (key, lazy = false) => `<img class="cover" src="/illustrations/blog/${art[key].file}" width="1536" height="1024" alt="${esc(art[key].alt)}" ${lazy ? 'loading="lazy"' : 'fetchpriority="high"'} decoding="async">`;
const nav = `<header><a class="brand" href="/">Peacedskin</a><nav aria-label="网站导航"><a href="/blog/">护肤指南</a><a href="/products/">产品成分</a><a href="/?view=profileBuilder">肤质测试</a></nav></header>`;
const css = `:root{color-scheme:light;--ink:#263027;--green:#2f5a40;--paper:#fbf6ea;--line:#d9d0bc}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;color:var(--ink);background:var(--paper);font:17px/1.85 system-ui,-apple-system,"PingFang SC","Microsoft YaHei",sans-serif}a{color:var(--green);text-underline-offset:4px}a:focus-visible,summary:focus-visible{outline:3px solid #9a6e04;outline-offset:5px}header{max-width:1120px;margin:auto;padding:24px;display:flex;justify-content:space-between;align-items:center;gap:20px;border-bottom:1px solid var(--line)}.brand{font:italic 30px Georgia,serif;text-decoration:none}nav{display:flex;flex-wrap:wrap;gap:18px;font-size:14px}main{max-width:820px;margin:auto;padding:36px 24px 72px}.wide{max-width:1120px}.eyebrow{font-size:14px;letter-spacing:.12em;color:var(--green)}h1{font-family:Georgia,"Songti SC",serif;font-size:clamp(30px,5vw,48px);line-height:1.3;letter-spacing:-.025em;margin:12px 0 22px}h2{font-size:25px;line-height:1.45;margin:38px 0 14px}h3{font-size:20px;line-height:1.5}p{margin:0 0 18px}li{margin:8px 0}.meta,.refs,figcaption{font-size:14px;color:#615e54}.refs{margin-top:8px}figure{margin:26px 0}.cover{display:block;width:100%;height:auto;aspect-ratio:3/2;object-fit:cover;border-radius:16px}figcaption{margin-top:8px}.answer{border-left:4px solid var(--green);background:#eaf0e6;padding:22px;margin:26px 0}.answer p:last-child{margin:0}.toc{border:1px solid var(--line);padding:16px 22px;border-radius:12px}.toc summary{cursor:pointer;font-weight:600}.toc ol{margin-bottom:0}section{scroll-margin-top:20px}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse;font-size:16px;margin:20px 0}th,td{padding:12px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top;min-width:125px}th{background:#eaf0e6}.cta{display:flex;flex-wrap:wrap;gap:12px;margin:24px 0}.cta a{padding:10px 16px;border:1px solid var(--green);border-radius:24px;text-decoration:none}.cta a:first-child{background:var(--green);color:white}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:28px 22px}.card{min-width:0}.card a{text-decoration:none}.card h2{font-size:22px;margin:12px 0}.card p{font-size:15px;line-height:1.65}.card .cover{border-radius:12px}.card a:hover h2{text-decoration:underline}.notice{border-top:1px solid var(--line);padding-top:22px;font-size:14px;color:#615e54;margin-top:32px}.related{display:grid;gap:12px}.sources li{overflow-wrap:anywhere;font-size:14px}footer{max-width:1120px;margin:auto;border-top:1px solid var(--line);padding:24px;font-size:14px}.intro{max-width:680px;margin-bottom:36px}@media(max-width:760px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}header{align-items:flex-start;flex-direction:column;gap:10px}}@media(max-width:480px){.grid{grid-template-columns:1fr}main{padding:24px 18px 56px}header{padding:18px}.answer{padding:18px}body{font-size:16px}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}`;
function shell(title, description, route, body, schema) {
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | Peacedskin</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${origin}${route}"><meta property="og:type" content="${schema['@type'] === 'BlogPosting' ? 'article' : 'website'}"><meta property="og:site_name" content="Peacedskin"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${origin}${route}"><meta name="twitter:card" content="summary"><script type="application/ld+json">${json({'@context':'https://schema.org',...schema})}</script><link rel="stylesheet" href="/blog/blog.css"></head><body>${nav}${body}<footer><a href="/blog/">全部护肤指南</a> · <a href="/">返回 Peacedskin</a><p>理解你的皮肤，再决定买什么。</p></footer></body></html>`;
}
const table = data => !data ? '' : `<div class="table-wrap"><table><thead><tr>${data.headers.map(h => `<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${data.rows.map(row => `<tr>${row.map(cell => `<td>${esc(cell)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const section = (block, index) => `<section id="section-${index + 1}"><h2>${esc(block.heading)}</h2>${(block.paragraphs || []).map(p => `<p>${esc(p)}</p>`).join('')}${block.bullets ? `<ul>${block.bullets.map(p => `<li>${esc(p)}</li>`).join('')}</ul>` : ''}${table(block.table)}${ref(block.sources)}</section>`;

await fs.mkdir('dist/blog', { recursive:true });
await fs.writeFile('dist/blog/blog.css', css);
for (const article of articles) {
  const route = `/blog/${article.slug}/`;
  const keys = [...new Set(article.sections.flatMap(s => s.sources || []))];
  const related = article.related.map(slug => articles.find(a => a.slug === slug));
  if (related.some(a => !a)) throw new Error(`Broken related article: ${article.slug}`);
  const length = article.sections.reduce((n,b) => n + JSON.stringify(b).length, 0);
  const body = `<main><article><div class="eyebrow">${esc(article.category)} · PEACEDSKIN JOURNAL</div><h1>${esc(article.title)}</h1><p>${esc(article.excerpt)}</p><p class="meta">Peacedskin 内容整理 · AI 辅助撰写｜发布于 <time datetime="${article.date}">${article.date}</time>｜约 ${Math.max(3, Math.ceil(length / 450))} 分钟阅读</p><figure>${image(article.art)}<figcaption>AI 生成专题插画；不是产品实拍或效果对比。</figcaption></figure><aside class="answer"><strong>先说结论</strong><p>${esc(article.answer)}</p></aside><details class="toc"><summary>这篇会回答什么？</summary><ol>${article.sections.map((s,i) => `<li><a href="#section-${i+1}">${esc(s.heading)}</a></li>`).join('')}</ol></details>${article.sections.map(section).join('')}<section><h2>把判断用到你的护肤里</h2><p>${esc(article.next)}</p><div class="cta"><a href="/?view=profileBuilder">了解我的肤质</a><a href="/products/">查看产品成分目录</a></div>${(article.products || []).map(p => `<p><a href="${esc(p.url)}">${esc(p.label)}</a></p>`).join('')}</section><section><h2>接着读</h2><div class="related">${related.map(a=>`<a href="/blog/${a.slug}/">${esc(a.title)}</a>`).join('')}</div></section><section class="sources"><h2>资料来源与说明</h2><ol>${keys.map(key => `<li><a href="${esc(sources[key].url)}">${esc(sources[key].label)}</a> — ${esc(sources[key].note)}</li>`).join('')}</ol><p class="meta">资料核对日期：${article.date}。文中的场景安排、购物清单和记录方法是 Peacedskin 的编辑建议，不是上述机构的产品背书。</p></section><aside class="notice">本文为一般护肤教育与选购信息，未经过医生逐篇医学审阅，不构成诊断或治疗建议。持续或加重的红、痒、疼痛、渗液请就医；出现呼吸困难或明显面部肿胀应及时寻求急救。处方治疗请遵循医生指导，不因本文自行停药。产品版本与配方可能改变，请以手中包装为准。</aside></article></main>`;
  await fs.mkdir(path.join('dist', route), { recursive:true });
  await fs.writeFile(path.join('dist', route, 'index.html'), shell(article.title, article.excerpt, route, body, {
    '@type':'BlogPosting', headline:article.title, description:article.excerpt, inLanguage:'zh-CN', datePublished:article.date, dateModified:article.date,
    mainEntityOfPage:origin+route, author:{'@type':'Organization',name:'Peacedskin',url:origin+'/'}, publisher:{'@type':'Organization',name:'Peacedskin',url:origin+'/'},
    image:origin+'/illustrations/blog/'+art[article.art].file, citation:keys.map(key=>sources[key].url)
  }));
}
const cards = articles.map(a=>`<article class="card"><a href="/blog/${a.slug}/">${image(a.art,true)}<p class="eyebrow">${esc(a.category)}</p><h2>${esc(a.title)}</h2></a><p>${esc(a.excerpt)}</p></article>`).join('');
await fs.writeFile('dist/blog/index.html',shell('护肤指南：新加坡日常、产品选择与精简护肤','12 篇实用护肤指南：湿热天气保湿、通勤防晒、产品成分与试用方法。结合公开资料，把护肤问题变成可执行的选择。','/blog/',`<main class="wide"><div class="intro"><div class="eyebrow">PEACEDSKIN JOURNAL · 中文指南</div><h1>少一点猜测，<br>多一点适合自己。</h1><p>从新加坡的日常场景出发，讨论怎么买、怎么用，以及什么时候不该继续加产品。</p><p class="meta">${articles.length} 篇完整指南 · 保留原有首页知识卡 · 每篇附资料来源</p></div><div class="grid">${cards}</div></main>`,{'@type':'CollectionPage',name:'Peacedskin 护肤指南',url:origin+'/blog/',inLanguage:'zh-CN'}));
let sitemap=await fs.readFile('dist/sitemap.xml','utf8');
for(const route of ['/blog/',...articles.map(a=>`/blog/${a.slug}/`)]) {
  const loc = `${origin}${route}`;
  if(!sitemap.includes(`<loc>${loc}</loc>`)) sitemap=sitemap.replace('</urlset>',`  <url><loc>${esc(loc)}</loc></url>\n</urlset>`);
}
await fs.writeFile('dist/sitemap.xml',sitemap);
console.log(`Generated blog index and ${articles.length} source-backed articles.`);
