import {origin,esc,locale,productRoute,blogRoute,directoryRoute} from './static-languages.mjs';
import {productEditorial} from '../data/product-editorial.mjs';
const styles=`body{margin:0;background:#fbf6ea;color:#263027;font:17px/1.8 system-ui,sans-serif}main{max-width:850px;margin:auto;padding:28px 22px 80px}a{color:#2f5a40}h1{font-size:clamp(28px,5vw,44px);line-height:1.3;overflow-wrap:anywhere}h2{font-size:25px;line-height:1.4}section{border-top:1px solid #d9d0bc;padding:24px 0}li{margin:10px 0;overflow-wrap:anywhere}.meta{display:flex;flex-wrap:wrap;gap:12px;font-size:15px}.cta{display:inline-block;margin:12px 0;padding:10px 18px;border-radius:24px;background:#2f5a40;color:white;text-decoration:none}.note{font-size:15px}.inci{overflow-wrap:anywhere}.table-wrap{overflow-x:auto}table{border-collapse:collapse;width:100%}td,th{padding:12px;text-align:left;border-bottom:1px solid #d9d0bc;vertical-align:top;min-width:120px}`;
export const normalize = s=>String(s).toLocaleLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9\u3400-\u9fff]+/g,'');
const categories={serum:'精华',essence:'精华水',toner:'化妆水',moisturizer:'保湿产品',cream:'面霜',cleanser:'洁面',sunscreen:'防晒',mask:'面膜',eye_care:'眼部护理',eye_cream:'眼霜',lotion:'乳液',makeup_remover:'卸妆产品'};
const categoryEn=raw=>({'精华':'Serum','精华水':'Essence','化妆水':'Toner','爽肤水':'Toner','保湿霜':'Moisturiser','面霜':'Cream','修复霜':'Repair cream','洁面':'Cleanser','防晒':'Sunscreen','面膜':'Mask','乳液':'Lotion','眼霜':'Eye cream','卸妆':'Makeup remover'}[raw] || (/[^\x00-\x7F]/.test(raw||'')?'Skincare':raw||'Skincare'));
const categoryZh=raw=>/[\u3400-\u9fff]/.test(raw)?raw:categories[String(raw).toLowerCase()]||(/eye/i.test(raw)?'眼部护理':/mask/i.test(raw)?'面膜':/sun/i.test(raw)?'防晒':/serum/i.test(raw)?'精华':/cream|moist/i.test(raw)?'保湿产品':/toner|essence/i.test(raw)?'化妆水 / 精华水':/clean/i.test(raw)?'洁面':'护肤品');
function shell(en,title,description,l,body,schema='',indexable=true){
 return `<!doctype html><html lang="${en?'en':'zh-CN'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}">${l.head}${indexable?'':'<meta name="robots" content="noindex,follow">'}<meta property="og:type" content="website"><meta property="og:site_name" content="Peacedskin"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta name="twitter:card" content="summary"><style>${styles}</style>${schema}</head><body><main><nav><a href="/">Peacedskin</a> · <a href="${directoryRoute(en)}">${l.pick('产品成分目录','Ingredient directory')}</a> · <a href="${blogRoute('',en)}">${l.pick('护肤指南','Skincare guides')}</a></nav>${l.controls}${body}</main></body></html>`;
}
export function productHtml(row,dictionary,en=true){
 const l=locale(en,productRoute(row.__slug),productRoute(row.__slug,true)),t=l.text;
 const ingredients=Array.isArray(row.ingredient_names)?row.ingredient_names.filter(Boolean).slice():[];
 if(row.__slug==='beauty-of-joseon-relief-sun-rice-probiotics')for(let i=0;i<ingredients.length-1;i++)if(ingredients[i].trim()==='1'&&/^2-hexanediol$/i.test(ingredients[i+1].trim()))ingredients.splice(i,2,'1,2-Hexanediol');
 const editorial=productEditorial[row.__slug];
 const editorialHtml=editorial?`<section>${t('版本与选用重点','Version and decision notes','h2')}${editorial.sections.map(p=>t(p.zh,p.en,'p')).join('')}<p>${t('资料核对：2026-09-02；来源：','Checked: 2026-09-02; source: ')}<a href="${esc(editorial.source)}">${esc(editorial.sourceLabel)}</a>${editorial.ingredientSource?` · <a href="${esc(editorial.ingredientSource)}">${t('品牌地区成分表','Regional brand ingredient list')}</a>`:''}</p><p><a href="${blogRoute(editorial.guide,en)}">${t(editorial.guideZh,editorial.guideEn)}</a></p></section>`:'';
 const complete=Number(row.data_completeness||0),type=row.ingredient_list_type||'unknown';
 const nameZh=row.product_local_name||row.name;
 const title=l.pick(`${row.brand} ${nameZh}｜成分表与配方资料 | Peacedskin`,`${row.brand} ${row.name}: Ingredients & Formula Facts | Peacedskin`);
 const description=l.pick(`查看 ${row.brand} ${nameZh} 的已收录成分、中英文名称与配方完整度，并打开主站同款产品详情。`,`Explore the indexed ingredients, formula completeness and Chinese ingredient names for ${row.brand} ${row.name}, with a link to the same product in Peacedskin.`);
 const names=items=>items.map(item=>{const entry=dictionary.get(normalize(item));const zh=entry?.name_zh_cn&&!/^(配方成分|油脂\/润肤成分)[（(]/.test(entry.name_zh_cn)?entry.name_zh_cn:null;return `<li>${t(zh||item,item)}${!zh?` <small>${l.pick('（保留原始名称，中文待核对）','(original name; Chinese mapping pending)')}</small>`:''}</li>`}).join('');
 const body=`${t(nameZh,row.name,'h1')}${t(`${categoryZh(row.category)}的配方资料与成分目录。`,`${categoryEn(row.category)} formula facts and ingredient index.`,'p')}<div class="meta">${t(`资料完整度：${complete}%`,`Data completeness: ${complete}%`)}${t(`市场版本：${row.market||'Global'}`,`Market: ${row.market||'Global'}`)}${t(`成分列表：${type==='full'?'完整':type==='partial'?'部分':'类型待核对'}`,`Ingredient list: ${type}`)}</div>
 <a class="cta" href="/?view=product&amp;product=${encodeURIComponent(row.id)}">${t('打开主站同款产品：配方分析与肤质匹配','Open this product: formula analysis and skin matching')}</a>
 ${editorialHtml}
 <section>${t('配方速览：已收录的前 12 项成分','Formula at a glance: first 12 indexed ingredients','h2')}${ingredients.length?`<ol>${names(ingredients.slice(0,12))}</ol>`:t('成分表正在核对。','The ingredient list is being verified.','p')}</section>
 <section id="ingredients">${t('全部已收录成分','All indexed ingredients','h2')}${t('中文名称来自主站同一成分词典；点击“中英对照”即可逐项对照原始 INCI。未匹配的名称保留原文，不猜译。','Chinese names use the same ingredient dictionary as the main app. Select Chinese + English to compare each name with the original INCI. Unmapped names are left unchanged.','p')}${ingredients.length?`<ol class="inci">${names(ingredients)}</ol>`:t('暂无足够成分数据。','Not enough ingredient data is available.','p')}${t('不同市场和改版可能使用不同配方，请以手中包装为准。列表标为部分时，不应当作完整配方。','Ingredients can vary by market and reformulation. Check your packaging. A partial list must not be treated as a complete formula.','p')}${row.verified_at?t(`目录核对日期：${String(row.verified_at).slice(0,10)}`,`Catalog verification date: ${String(row.verified_at).slice(0,10)}`,'p'):''}</section>
 <section>${t('这是什么产品？','What is this product?','h2')}${t(`Peacedskin 当前将它归为${categoryZh(row.category)}。本页展示产品库中已收录的配方资料；数据完整度不是功效分数或医学认证。`,`Peacedskin currently lists this as ${categoryEn(row.category).toLowerCase()}. This page shows the formula information stored in the catalog. Data completeness is not an efficacy score or medical certification.`,'p')}</section>
 <section>${t('如何使用这些信息','How to interpret the information','h2')}${t('成分表可以帮助理解配方组成，但不能单独证明临床功效、致痘性或个人耐受。肤质、敏感程度、气候、使用方式及具体版本都会影响选择。本网站不提供医学诊断。','Ingredient lists help explain composition but do not alone establish clinical efficacy, comedogenicity or personal tolerance. Skin type, sensitivity, climate, routine and formula version all matter. This site does not provide medical diagnoses.','p')}<p><a href="/?view=profileBuilder">${t('了解我的肤质','Find my skin profile')}</a> · <a href="/?view=explore">${t('主站筛选产品','Filter products in the app')}</a></p></section>
 <section>${t('相关护肤指南','Related skincare guides','h2')}<ul><li><a href="${blogRoute('ingredient-list-how-to-read',en)}">${t('怎么看懂成分表，哪些不能靠成分猜？','What can an ingredient list tell you—and what can it not?')}</a></li><li><a href="${blogRoute('how-to-test-new-skincare',en)}">${t('新产品怎么试用？','How to introduce a new skincare product')}</a></li>${/cicaplast-baume-b5|avene-cicalfate$/.test(row.__slug)?`<li><a href="${blogRoute('cicaplast-b5-vs-cicalfate',en)}">${t('Cicaplast B5+ 与 Cicalfate+ 比较','Cicaplast B5+ vs Cicalfate+')}</a></li>`:''}</ul></section>`;
 const schema={'@context':'https://schema.org','@type':'Product',name:en?row.name:nameZh,brand:{'@type':'Brand',name:row.brand},category:row.category,url:origin+productRoute(row.__slug,en),description};
 return shell(en,title,description,l,body,`<script type="application/ld+json">${JSON.stringify(schema).replaceAll('<','\\u003c')}</script>`,ingredients.length>0);
}
export function directoryHtml(products,en=false){
 const l=locale(en,directoryRoute(false),directoryRoute(true)),t=l.text;
 const groups=new Map();for(const p of products){if(!groups.has(p.brand))groups.set(p.brand,[]);groups.get(p.brand).push(p)}
 const sortedGroups=[...groups].sort(([a],[b])=>a.localeCompare(b));
 const body=`${t('护肤品成分目录','Skincare ingredient directory','h1')}${t(`当前公开目录包含 ${products.length} 款产品。按品牌查看已收录配方，并打开主站同款产品进行分析。这不是产品效果排名。`,`Browse ${products.length} public product pages by brand, then open the same product in the app for analysis. This is not an efficacy ranking.`,'p')}<p><a href="/?view=explore">${t('打开主站产品筛选工具','Open product filters in the app')}</a></p><nav aria-label="${l.pick('按品牌跳转','Jump to brand')}" class="meta">${sortedGroups.map(([brand],i)=>`<a href="#brand-${i+1}">${esc(brand)}</a>`).join(' · ')}</nav>${sortedGroups.map(([brand,items],i)=>`<section id="brand-${i+1}"><h2>${esc(brand)}</h2><ul>${items.map(p=>`<li><a href="${productRoute(p.__slug,en)}">${t(p.product_local_name||p.name,p.name)}</a> · ${t(categoryZh(p.category),categoryEn(p.category))}<br><a href="/?view=product&amp;product=${encodeURIComponent(p.id)}">${t('主站产品详情','Product details in the app')}</a></li>`).join('')}</ul></section>`).join('')}${t('成分资料不等于临床功效或个人使用结果；请核对手中包装。','Ingredient data is not clinical efficacy evidence or a prediction of individual results. Check your packaging.','p')}`;
 return shell(en,l.pick('护肤品成分目录 | Peacedskin','Skincare Ingredient Directory | Peacedskin'),l.pick('按品牌浏览护肤品成分、中英文名称与配方完整度。','Browse skincare ingredients, Chinese names and formula completeness by brand.'),l,body);
}
