alter table public.ingredients add column if not exists name_zh_cn text;
alter table public.ingredients add column if not exists common_names text[] not null default '{}';
alter table public.ingredients add column if not exists functions text[] not null default '{}';
alter table public.ingredients add column if not exists ingredient_family text;
alter table public.ingredients add column if not exists plain_language_zh text;
alter table public.ingredients add column if not exists plain_language_en text;
alter table public.ingredients add column if not exists evidence_level text;

create table if not exists public.product_aliases (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products(id) on delete cascade,
  alias text not null,
  locale text not null default 'zh-CN',
  alias_type text not null default 'consumer_nickname' check (alias_type in ('consumer_nickname','official_local_name','spelling_variant','abbreviation','legacy_name')),
  verified boolean not null default false,
  source text,
  created_at timestamptz not null default now(),
  unique(product_id, alias, locale)
);
create index if not exists product_aliases_alias_lower_idx on public.product_aliases (lower(alias));
create index if not exists product_aliases_product_idx on public.product_aliases (product_id);
alter table public.product_aliases enable row level security;
drop policy if exists "product aliases public read" on public.product_aliases;
create policy "product aliases public read" on public.product_aliases for select to anon, authenticated using (verified = true);
grant select on public.product_aliases to anon, authenticated;

create table if not exists public.search_events (
  id bigint generated by default as identity primary key,
  query text not null,
  normalized_query text not null,
  result_count integer not null default 0,
  selected_product_id uuid references public.products(id) on delete set null,
  source text not null default 'product_search',
  locale text,
  created_at timestamptz not null default now()
);
create index if not exists search_events_normalized_query_idx on public.search_events (normalized_query, created_at desc);
alter table public.search_events enable row level security;
drop policy if exists "search events public insert" on public.search_events;
create policy "search events public insert" on public.search_events for insert to anon, authenticated with check (char_length(query) between 1 and 200 and char_length(normalized_query) between 1 and 200 and result_count between 0 and 1000);
grant insert on public.search_events to anon, authenticated;

create or replace view public.approved_product_catalog_summary
with (security_invoker = true)
as
select p.id, p.brand, p.name, p.brand_local_name, p.brand_english_name,
  p.product_local_name, p.product_english_name, p.source_locale, p.category,
  coalesce(f.source_url, p.source_url) as source_url,
  f.ingredient_names[1:15] as ingredient_names,
  f.ingredient_list_type, f.data_completeness,
  p.popularity_sources, p.popularity_tier, p.asia_availability_status,
  p.marketing_positioning, p.intended_skin_types, p.intended_concerns, p.intended_use_context,
  f.formula_function_summary, f.formula_best_for, f.formula_also_works_for,
  f.formula_less_ideal_for, f.formula_caveats, f.formula_verdict,
  coalesce((select array_agg(pa.alias order by pa.alias) from public.product_aliases pa where pa.product_id = p.id and pa.verified), '{}')::text[] as search_aliases
from public.products p
join public.product_formulas f on f.product_id = p.id and f.is_current
where p.archived_at is null;
grant select on public.approved_product_catalog_summary to anon, authenticated;